In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt

In [2]:
file_path = 'data/2010_UI_UER.xlsx'
df = pd.read_excel(file_path)

In [3]:
df

,Name_of_Regions,Unnamed: 1,Year,UrbanDistrictArea,UrbanDistrictPopulation,UrbanDistrictTemporaryPopulation,UrbanArea,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,...,Industrial_sulphur_dioxide_emissions_(tonnes),Industrial_fume_emissions_(tonnes),城市,Comprehensive_industrial_solid_waste_utilisation_rate(%),Urban_domestic_sewage_treatment_rate(%),Rate_of_non_hazardous_treatment_of_domestic_waste(%),CITY,Greening_coverage_in_builtup_areas,Unnamed: 45,Parkland_per_capita
0,北京,Beijing,2010,16410.00,1961.20,0.00,12187.00,1685.90,0.00,1186.00,...,56844.0,21266.0,北京市,65.82,80.98,96.95,北京市,55.10,北京市,11.28
1,天津,Tianjin,2010,7398.86,807.02,38.44,2236.12,587.40,27.89,686.71,...,217620.0,53831.0,天津市,98.37,83.00,100.00,天津市,32.04,天津市,8.56
2,河北,Hebei,2010,32147.79,2703.43,127.28,6521.74,1454.60,80.82,1619.67,...,994138.0,322623.0,河北省,83333.00,979.46,1074.28,NaN,NaN,NaN,14.23
3,石家庄,Shijiazhuang,2010,455.80,245.35,20.74,212.54,227.60,17.67,202.90,...,137934.0,32631.0,石家庄市,93.36,95.30,100.00,石家庄市,43.01,石家庄市,14.39
4,唐山,Tangshan,2010,3874.00,305.62,4.00,1230.20,193.08,4.00,234.00,...,238061.0,98670.0,唐山市,80.55,94.11,100.00,唐山市,46.00,唐山市,15.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,固原,Guyuan,2010,4489.00,47.00,7.28,34.62,15.30,5.58,34.62,...,4210.0,1000.0,固原市,99.20,60.00,100.00,固原市,28.31,固原市,8.52
315,中卫,Zhongwei,2010,5358.10,39.59,0.86,52.00,18.30,0.12,32.04,...,46111.0,27833.0,中卫市,60.61,77.83,45.09,中卫市,26.03,中卫市,11.62
316,新疆,xinjiang,2010,240068.23,854.99,98.25,1267.62,549.12,81.76,838.21,...,128370.0,39003.0,新疆维吾尔自治区,47.50,149.46,70.58,NaN,36.40,NaN,8.61
317,乌鲁木齐,Urumuchi,2010,14216.30,279.20,36.16,342.67,243.04,36.16,342.67,...,94146.0,32993.0,乌鲁木齐市,68.20,57.34,87.40,乌鲁木齐市,34.77,乌鲁木齐市,7.39
318,克拉玛依,Kelamayi,2010,9548.00,26.13,8.73,57.16,26.13,8.73,57.16,...,34224.0,6010.0,克拉玛依市,63.55,92.12,94.87,克拉玛依市,50.68,克拉玛依市,9.04

In [4]:
# Removes rows containing NaN values in the specified columns
columns_to_check = [ 
    'Total_population_of_the_region', 
    'First_sector_of_GDP', 
    'GDP', 
    'Citycode', 
    'Area_of_administrative_districts'
]
df_cleaned = df.dropna(subset=columns_to_check)

In [5]:
df_cleaned

,Name_of_Regions,Unnamed: 1,Year,UrbanDistrictArea,UrbanDistrictPopulation,UrbanDistrictTemporaryPopulation,UrbanArea,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,...,Industrial_sulphur_dioxide_emissions_(tonnes),Industrial_fume_emissions_(tonnes),城市,Comprehensive_industrial_solid_waste_utilisation_rate(%),Urban_domestic_sewage_treatment_rate(%),Rate_of_non_hazardous_treatment_of_domestic_waste(%),CITY,Greening_coverage_in_builtup_areas,Unnamed: 45,Parkland_per_capita
0,北京,Beijing,2010,16410.00,1961.20,0.00,12187.00,1685.90,0.00,1186.00,...,56844.0,21266.0,北京市,65.82,80.98,96.95,北京市,55.10,北京市,11.28
1,天津,Tianjin,2010,7398.86,807.02,38.44,2236.12,587.40,27.89,686.71,...,217620.0,53831.0,天津市,98.37,83.00,100.00,天津市,32.04,天津市,8.56
3,石家庄,Shijiazhuang,2010,455.80,245.35,20.74,212.54,227.60,17.67,202.90,...,137934.0,32631.0,石家庄市,93.36,95.30,100.00,石家庄市,43.01,石家庄市,14.39
4,唐山,Tangshan,2010,3874.00,305.62,4.00,1230.20,193.08,4.00,234.00,...,238061.0,98670.0,唐山市,80.55,94.11,100.00,唐山市,46.00,唐山市,15.13
5,秦皇岛,Qinhuangdao,2010,363.20,82.97,7.13,363.20,82.97,7.13,89.48,...,44737.0,11365.0,秦皇岛市,59.57,92.10,100.00,秦皇岛市,50.24,秦皇岛市,19.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,固原,Guyuan,2010,4489.00,47.00,7.28,34.62,15.30,5.58,34.62,...,4210.0,1000.0,固原市,99.20,60.00,100.00,固原市,28.31,固原市,8.52
315,中卫,Zhongwei,2010,5358.10,39.59,0.86,52.00,18.30,0.12,32.04,...,46111.0,27833.0,中卫市,60.61,77.83,45.09,中卫市,26.03,中卫市,11.62
316,新疆,xinjiang,2010,240068.23,854.99,98.25,1267.62,549.12,81.76,838.21,...,128370.0,39003.0,新疆维吾尔自治区,47.50,149.46,70.58,NaN,36.40,NaN,8.61
317,乌鲁木齐,Urumuchi,2010,14216.30,279.20,36.16,342.67,243.04,36.16,342.67,...,94146.0,32993.0,乌鲁木齐市,68.20,57.34,87.40,乌鲁木齐市,34.77,乌鲁木齐市,7.39
318,克拉玛依,Kelamayi,2010,9548.00,26.13,8.73,57.16,26.13,8.73,57.16,...,34224.0,6010.0,克拉玛依市,63.55,92.12,94.87,克拉玛依市,50.68,克拉玛依市,9.04

In [6]:
# Specify the columns to check for NaN values
columns_to_check = [
    'UrbanPopulation',
    'UrbanTemporaryPopulation', 
    'Total_population_of_the_region', 
    'First_sector_of_GDP', 
    'GDP', 
    'Citycode', 
    'Area_of_administrative_districts',
    'Road_Surface_Area_Per_Capita_m2',
    'UrbanArea'
]

# Convert these columns to numeric types to handle non-numeric content
for column in columns_to_check:
    df_cleaned[column] = pd.to_numeric(df_cleaned[column], errors='coerce')

/tmp/ipykernel_4090/2476692969.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = pd.to_numeric(df_cleaned[column], errors='coerce')

In [7]:
df_cleaned['UrbanTemporaryPopulation'] = df_cleaned['UrbanTemporaryPopulation'].fillna(0)

/tmp/ipykernel_4090/1004577029.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['UrbanTemporaryPopulation'] = df_cleaned['UrbanTemporaryPopulation'].fillna(0)

In [8]:
df_cleaned['PUI'] = (df_cleaned['Population_urbanization'])

/tmp/ipykernel_4090/629985429.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['PUI'] = (df_cleaned['Population_urbanization'])

In [9]:
df_cleaned

,Name_of_Regions,Unnamed: 1,Year,UrbanDistrictArea,UrbanDistrictPopulation,UrbanDistrictTemporaryPopulation,UrbanArea,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,...,Industrial_fume_emissions_(tonnes),城市,Comprehensive_industrial_solid_waste_utilisation_rate(%),Urban_domestic_sewage_treatment_rate(%),Rate_of_non_hazardous_treatment_of_domestic_waste(%),CITY,Greening_coverage_in_builtup_areas,Unnamed: 45,Parkland_per_capita,PUI
0,北京,Beijing,2010,16410.00,1961.20,0.00,12187.00,1685.90,0.00,1186.00,...,21266.0,北京市,65.82,80.98,96.95,北京市,55.10,北京市,11.28,0.8433
1,天津,Tianjin,2010,7398.86,807.02,38.44,2236.12,587.40,27.89,686.71,...,53831.0,天津市,98.37,83.00,100.00,天津市,32.04,天津市,8.56,0.7572
3,石家庄,Shijiazhuang,2010,455.80,245.35,20.74,212.54,227.60,17.67,202.90,...,32631.0,石家庄市,93.36,95.30,100.00,石家庄市,43.01,石家庄市,14.39,0.3904
4,唐山,Tangshan,2010,3874.00,305.62,4.00,1230.20,193.08,4.00,234.00,...,98670.0,唐山市,80.55,94.11,100.00,唐山市,46.00,唐山市,15.13,0.3128
5,秦皇岛,Qinhuangdao,2010,363.20,82.97,7.13,363.20,82.97,7.13,89.48,...,11365.0,秦皇岛市,59.57,92.10,100.00,秦皇岛市,50.24,秦皇岛市,19.90,0.4053
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,固原,Guyuan,2010,4489.00,47.00,7.28,34.62,15.30,5.58,34.62,...,1000.0,固原市,99.20,60.00,100.00,固原市,28.31,固原市,8.52,0.1222
315,中卫,Zhongwei,2010,5358.10,39.59,0.86,52.00,18.30,0.12,32.04,...,27833.0,中卫市,60.61,77.83,45.09,中卫市,26.03,中卫市,11.62,0.2169
316,新疆,xinjiang,2010,240068.23,854.99,98.25,1267.62,549.12,81.76,838.21,...,39003.0,新疆维吾尔自治区,47.50,149.46,70.58,NaN,36.40,NaN,8.61,0.4006
317,乌鲁木齐,Urumuchi,2010,14216.30,279.20,36.16,342.67,243.04,36.16,342.67,...,32993.0,乌鲁木齐市,68.20,57.34,87.40,乌鲁木齐市,34.77,乌鲁木齐市,7.39,0.9744
318,克拉玛依,Kelamayi,2010,9548.00,26.13,8.73,57.16,26.13,8.73,57.16,...,6010.0,克拉玛依市,63.55,92.12,94.87,克拉玛依市,50.68,克拉玛依市,9.04,0.7686

In [10]:
df_cleaned['PUI'].describe()

count    290.000000
mean       0.414694
std        0.177859
min        0.113700
25%        0.285275
50%        0.383700
75%        0.492675
max        1.000000
Name: PUI, dtype: float64

In [11]:
df_cleaned['URI'] = (df_cleaned['Road_Surface_Area_Per_Capita_m2'] * ((df_cleaned['UrbanPopulation'] + df_cleaned['UrbanTemporaryPopulation'])* 10000) /1000000 ) / df_cleaned['Area_of_administrative_districts']

/tmp/ipykernel_4090/2660692400.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['URI'] = (df_cleaned['Road_Surface_Area_Per_Capita_m2'] * ((df_cleaned['UrbanPopulation'] + df_cleaned['UrbanTemporaryPopulation'])* 10000) /1000000 ) / df_cleaned['Area_of_administrative_districts']

In [12]:
df_cleaned['URI'].describe()

count    290.000000
mean       0.001927
std        0.004595
min        0.000005
25%        0.000253
50%        0.000730
75%        0.002014
max        0.048389
Name: URI, dtype: float64

In [13]:
df_cleaned['LUI'] = (df_cleaned['Surface_Area_of_Built_District']) / df_cleaned['Area_of_administrative_districts']

/tmp/ipykernel_4090/3353621859.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['LUI'] = (df_cleaned['Surface_Area_of_Built_District']) / df_cleaned['Area_of_administrative_districts']

In [14]:
df_cleaned['LUI'].describe()

count    290.000000
mean       0.014792
std        0.035899
min        0.000071
25%        0.002721
50%        0.006242
75%        0.014999
max        0.427180
Name: LUI, dtype: float64

In [15]:
df_cleaned['EUI'] = 1 - (df_cleaned['First_sector_of_GDP']) / 100

/tmp/ipykernel_4090/1051056126.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['EUI'] = 1 - (df_cleaned['First_sector_of_GDP']) / 100

In [16]:
df_cleaned['EUI'].describe()

count    290.000000
mean       0.859063
std        0.084728
min        0.555800
25%        0.795475
50%        0.867350
75%        0.930550
max        0.999200
Name: EUI, dtype: float64

In [17]:
df_cleaned['EAL'] = df_cleaned['GDP'] / df_cleaned['Area_of_administrative_districts']

/tmp/ipykernel_4090/3615482750.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['EAL'] = df_cleaned['GDP'] / df_cleaned['Area_of_administrative_districts']

In [18]:
df_cleaned['EAL'].describe()

count      290.000000
mean      1538.416561
std       3308.283152
min          4.221506
25%        306.328838
50%        662.736441
75%       1532.333641
max      42209.560473
Name: EAL, dtype: float64

In [19]:
df_cleaned

,Name_of_Regions,Unnamed: 1,Year,UrbanDistrictArea,UrbanDistrictPopulation,UrbanDistrictTemporaryPopulation,UrbanArea,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,...,Rate_of_non_hazardous_treatment_of_domestic_waste(%),CITY,Greening_coverage_in_builtup_areas,Unnamed: 45,Parkland_per_capita,PUI,URI,LUI,EUI,EAL
0,北京,Beijing,2010,16410.00,1961.20,0.00,12187.00,1685.90,0.00,1186.00,...,96.95,北京市,55.10,北京市,11.28,0.8433,0.005724,0.072295,0.9903,7408.107284
1,天津,Tianjin,2010,7398.86,807.02,38.44,2236.12,587.40,27.89,686.71,...,100.00,天津市,32.04,天津市,8.56,0.7572,0.007683,0.057591,0.9829,6308.160013
3,石家庄,Shijiazhuang,2010,455.80,245.35,20.74,212.54,227.60,17.67,202.90,...,100.00,石家庄市,43.01,石家庄市,14.39,0.3904,0.002950,0.014433,0.8973,2134.926519
4,唐山,Tangshan,2010,3874.00,305.62,4.00,1230.20,193.08,4.00,234.00,...,100.00,唐山市,46.00,唐山市,15.13,0.3128,0.002158,0.016947,0.9055,2761.239282
5,秦皇岛,Qinhuangdao,2010,363.20,82.97,7.13,363.20,82.97,7.13,89.48,...,100.00,秦皇岛市,50.24,秦皇岛市,19.90,0.4053,0.002248,0.011484,0.8728,1032.523229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,固原,Guyuan,2010,4489.00,47.00,7.28,34.62,15.30,5.58,34.62,...,100.00,固原市,28.31,固原市,8.52,0.1222,0.000378,0.003290,0.7255,83.549981
315,中卫,Zhongwei,2010,5358.10,39.59,0.86,52.00,18.30,0.12,32.04,...,45.09,中卫市,26.03,中卫市,11.62,0.2169,0.000256,0.002346,0.8186,104.679991
316,新疆,xinjiang,2010,240068.23,854.99,98.25,1267.62,549.12,81.76,838.21,...,70.58,NaN,36.40,NaN,8.61,0.4006,0.000051,0.000514,0.8020,33.346723
317,乌鲁木齐,Urumuchi,2010,14216.30,279.20,36.16,342.67,243.04,36.16,342.67,...,87.40,乌鲁木齐市,34.77,乌鲁木齐市,7.39,0.9744,0.001453,0.024844,0.9850,793.532951
318,克拉玛依,Kelamayi,2010,9548.00,26.13,8.73,57.16,26.13,8.73,57.16,...,94.87,克拉玛依市,50.68,克拉玛依市,9.04,0.7686,0.001116,0.007752,0.9934,651.330214

In [20]:
# Import land_use_intensity_by_city2006.csv data
df_land_use = pd.read_csv("data/land_use_intensity_by_city2010.csv", encoding='ISO-8859-1')
df_land_useProvince = pd.read_csv("data/land_use_intensity_by_province2010.csv", encoding='ISO-8859-1')
df_combined = pd.concat([df_land_use, df_land_useProvince], ignore_index=True)

In [21]:
df_combined

     Citycode  Provincecode        Province            City         LUL
0    110000.0      110000.0          ±±¾©ÊÐ          ±±¾©ÊÐ  265.965018
1    120000.0      120000.0          Ìì½òÊÐ          Ìì½òÊÐ  302.537533
2    130100.0      130000.0          ºÓ±±Ê¡        Ê¯¼Ò×¯ÊÐ  285.652043
3    130200.0      130000.0          ºÓ±±Ê¡          ÌÆÉ½ÊÐ  296.218637
4    130300.0      130000.0          ºÓ±±Ê¡        ÇØ»ÊµºÊÐ  264.130224
..        ...           ...             ...             ...         ...
369  820000.0      820000.0  °ÄÃÅÌØ±ðÐÐÕþÇø  °ÄÃÅÌØ±ðÐÐÕþÇø  200.459557
370  460000.0           NaN          hainan             NaN  227.854195
371  630000.0           NaN         qinghai             NaN  141.508523
372  650000.0           NaN        xinjiang             NaN   65.635689
373  540000.0           NaN          xizang             NaN  168.642336

[374 rows x 5 columns]

In [22]:
df_merged = df_cleaned.merge(df_combined[['Citycode', 'LUL']], on='Citycode', how='left')

In [23]:
df_merged

,Name_of_Regions,Unnamed: 1,Year,UrbanDistrictArea,UrbanDistrictPopulation,UrbanDistrictTemporaryPopulation,UrbanArea,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,...,CITY,Greening_coverage_in_builtup_areas,Unnamed: 45,Parkland_per_capita,PUI,URI,LUI,EUI,EAL,LUL
0,北京,Beijing,2010,16410.00,1961.20,0.00,12187.00,1685.90,0.00,1186.00,...,北京市,55.10,北京市,11.28,0.8433,0.005724,0.072295,0.9903,7408.107284,265.965018
1,天津,Tianjin,2010,7398.86,807.02,38.44,2236.12,587.40,27.89,686.71,...,天津市,32.04,天津市,8.56,0.7572,0.007683,0.057591,0.9829,6308.160013,302.537533
2,石家庄,Shijiazhuang,2010,455.80,245.35,20.74,212.54,227.60,17.67,202.90,...,石家庄市,43.01,石家庄市,14.39,0.3904,0.002950,0.014433,0.8973,2134.926519,285.652043
3,唐山,Tangshan,2010,3874.00,305.62,4.00,1230.20,193.08,4.00,234.00,...,唐山市,46.00,唐山市,15.13,0.3128,0.002158,0.016947,0.9055,2761.239282,296.218637
4,秦皇岛,Qinhuangdao,2010,363.20,82.97,7.13,363.20,82.97,7.13,89.48,...,秦皇岛市,50.24,秦皇岛市,19.90,0.4053,0.002248,0.011484,0.8728,1032.523229,264.130224
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,固原,Guyuan,2010,4489.00,47.00,7.28,34.62,15.30,5.58,34.62,...,固原市,28.31,固原市,8.52,0.1222,0.000378,0.003290,0.7255,83.549981,244.783708
286,中卫,Zhongwei,2010,5358.10,39.59,0.86,52.00,18.30,0.12,32.04,...,中卫市,26.03,中卫市,11.62,0.2169,0.000256,0.002346,0.8186,104.679991,207.569339
287,新疆,xinjiang,2010,240068.23,854.99,98.25,1267.62,549.12,81.76,838.21,...,NaN,36.40,NaN,8.61,0.4006,0.000051,0.000514,0.8020,33.346723,65.635689
288,乌鲁木齐,Urumuchi,2010,14216.30,279.20,36.16,342.67,243.04,36.16,342.67,...,乌鲁木齐市,34.77,乌鲁木齐市,7.39,0.9744,0.001453,0.024844,0.9850,793.532951,138.231543
289,克拉玛依,Kelamayi,2010,9548.00,26.13,8.73,57.16,26.13,8.73,57.16,...,克拉玛依市,50.68,克拉玛依市,9.04,0.7686,0.001116,0.007752,0.9934,651.330214,69.640647

In [24]:
columns_to_check1 = ['URI', 'LUI', 'EUI', 'EAL','LUL']

data_merged = df_merged.dropna(subset=columns_to_check1)

In [25]:
data_merged

,Name_of_Regions,Unnamed: 1,Year,UrbanDistrictArea,UrbanDistrictPopulation,UrbanDistrictTemporaryPopulation,UrbanArea,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,...,CITY,Greening_coverage_in_builtup_areas,Unnamed: 45,Parkland_per_capita,PUI,URI,LUI,EUI,EAL,LUL
0,北京,Beijing,2010,16410.00,1961.20,0.00,12187.00,1685.90,0.00,1186.00,...,北京市,55.10,北京市,11.28,0.8433,0.005724,0.072295,0.9903,7408.107284,265.965018
1,天津,Tianjin,2010,7398.86,807.02,38.44,2236.12,587.40,27.89,686.71,...,天津市,32.04,天津市,8.56,0.7572,0.007683,0.057591,0.9829,6308.160013,302.537533
2,石家庄,Shijiazhuang,2010,455.80,245.35,20.74,212.54,227.60,17.67,202.90,...,石家庄市,43.01,石家庄市,14.39,0.3904,0.002950,0.014433,0.8973,2134.926519,285.652043
3,唐山,Tangshan,2010,3874.00,305.62,4.00,1230.20,193.08,4.00,234.00,...,唐山市,46.00,唐山市,15.13,0.3128,0.002158,0.016947,0.9055,2761.239282,296.218637
4,秦皇岛,Qinhuangdao,2010,363.20,82.97,7.13,363.20,82.97,7.13,89.48,...,秦皇岛市,50.24,秦皇岛市,19.90,0.4053,0.002248,0.011484,0.8728,1032.523229,264.130224
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,固原,Guyuan,2010,4489.00,47.00,7.28,34.62,15.30,5.58,34.62,...,固原市,28.31,固原市,8.52,0.1222,0.000378,0.003290,0.7255,83.549981,244.783708
286,中卫,Zhongwei,2010,5358.10,39.59,0.86,52.00,18.30,0.12,32.04,...,中卫市,26.03,中卫市,11.62,0.2169,0.000256,0.002346,0.8186,104.679991,207.569339
287,新疆,xinjiang,2010,240068.23,854.99,98.25,1267.62,549.12,81.76,838.21,...,NaN,36.40,NaN,8.61,0.4006,0.000051,0.000514,0.8020,33.346723,65.635689
288,乌鲁木齐,Urumuchi,2010,14216.30,279.20,36.16,342.67,243.04,36.16,342.67,...,乌鲁木齐市,34.77,乌鲁木齐市,7.39,0.9744,0.001453,0.024844,0.9850,793.532951,138.231543
289,克拉玛依,Kelamayi,2010,9548.00,26.13,8.73,57.16,26.13,8.73,57.16,...,克拉玛依市,50.68,克拉玛依市,9.04,0.7686,0.001116,0.007752,0.9934,651.330214,69.640647

In [26]:
columns_to_keep = ['Name_of_Regions', 'Year', 'Citycode', 'PUI', 'URI', 'LUI', 'EUI', 'EAL', 'LUL']
ui_index_2010 = data_merged[columns_to_keep]

ui_index_2010.to_csv('data/UI_index_2010.csv', index=False)

In [27]:
columns_to_fill = [
    'Industrial_wastewater_discharge_(tonnes)', 
    'Industrial_fume_emissions_(tonnes)', 
    'Comprehensive_industrial_solid_waste_utilisation_rate(%)', 
    'Rate_of_non_hazardous_treatment_of_domestic_waste(%)', 
    'Greening_coverage_in_builtup_areas', 
    'Parkland_per_capita'
]

df_cleaned[columns_to_fill] = df_cleaned[columns_to_fill].fillna(0)

/tmp/ipykernel_4090/1106163433.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[columns_to_fill] = df_cleaned[columns_to_fill].fillna(0)

In [28]:
df_cleaned

,Name_of_Regions,Unnamed: 1,Year,UrbanDistrictArea,UrbanDistrictPopulation,UrbanDistrictTemporaryPopulation,UrbanArea,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,...,Rate_of_non_hazardous_treatment_of_domestic_waste(%),CITY,Greening_coverage_in_builtup_areas,Unnamed: 45,Parkland_per_capita,PUI,URI,LUI,EUI,EAL
0,北京,Beijing,2010,16410.00,1961.20,0.00,12187.00,1685.90,0.00,1186.00,...,96.95,北京市,55.10,北京市,11.28,0.8433,0.005724,0.072295,0.9903,7408.107284
1,天津,Tianjin,2010,7398.86,807.02,38.44,2236.12,587.40,27.89,686.71,...,100.00,天津市,32.04,天津市,8.56,0.7572,0.007683,0.057591,0.9829,6308.160013
3,石家庄,Shijiazhuang,2010,455.80,245.35,20.74,212.54,227.60,17.67,202.90,...,100.00,石家庄市,43.01,石家庄市,14.39,0.3904,0.002950,0.014433,0.8973,2134.926519
4,唐山,Tangshan,2010,3874.00,305.62,4.00,1230.20,193.08,4.00,234.00,...,100.00,唐山市,46.00,唐山市,15.13,0.3128,0.002158,0.016947,0.9055,2761.239282
5,秦皇岛,Qinhuangdao,2010,363.20,82.97,7.13,363.20,82.97,7.13,89.48,...,100.00,秦皇岛市,50.24,秦皇岛市,19.90,0.4053,0.002248,0.011484,0.8728,1032.523229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,固原,Guyuan,2010,4489.00,47.00,7.28,34.62,15.30,5.58,34.62,...,100.00,固原市,28.31,固原市,8.52,0.1222,0.000378,0.003290,0.7255,83.549981
315,中卫,Zhongwei,2010,5358.10,39.59,0.86,52.00,18.30,0.12,32.04,...,45.09,中卫市,26.03,中卫市,11.62,0.2169,0.000256,0.002346,0.8186,104.679991
316,新疆,xinjiang,2010,240068.23,854.99,98.25,1267.62,549.12,81.76,838.21,...,70.58,NaN,36.40,NaN,8.61,0.4006,0.000051,0.000514,0.8020,33.346723
317,乌鲁木齐,Urumuchi,2010,14216.30,279.20,36.16,342.67,243.04,36.16,342.67,...,87.40,乌鲁木齐市,34.77,乌鲁木齐市,7.39,0.9744,0.001453,0.024844,0.9850,793.532951
318,克拉玛依,Kelamayi,2010,9548.00,26.13,8.73,57.16,26.13,8.73,57.16,...,94.87,克拉玛依市,50.68,克拉玛依市,9.04,0.7686,0.001116,0.007752,0.9934,651.330214

In [29]:
df_cleaned['Res1'] = df_cleaned['Industrial_wastewater_discharge_(tonnes)'] / df_cleaned['GDP']

/tmp/ipykernel_4090/2666823736.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Res1'] = df_cleaned['Industrial_wastewater_discharge_(tonnes)'] / df_cleaned['GDP']

In [30]:
df_cleaned['Res1'].describe()

count    290.000000
mean       0.000826
std        0.001186
min        0.000000
25%        0.000356
50%        0.000610
75%        0.001018
max        0.017121
Name: Res1, dtype: float64

In [31]:
df_cleaned['Res2'] = df_cleaned['Industrial_fume_emissions_(tonnes)'] / df_cleaned['GDP']

/tmp/ipykernel_4090/2575824147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Res2'] = df_cleaned['Industrial_fume_emissions_(tonnes)'] / df_cleaned['GDP']

In [32]:
df_cleaned['Res2'].describe()

count    290.000000
mean       0.002547
std        0.002987
min        0.000000
25%        0.000781
50%        0.001499
75%        0.003297
max        0.026616
Name: Res2, dtype: float64

In [33]:
df_cleaned['Ada1'] = df_cleaned['Comprehensive_industrial_solid_waste_utilisation_rate(%)'] 
df_cleaned['Ada1'].describe()

/tmp/ipykernel_4090/526319254.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Ada1'] = df_cleaned['Comprehensive_industrial_solid_waste_utilisation_rate(%)']

count    290.000000
mean      81.877966
std       22.771954
min        0.000000
25%       74.095000
50%       90.650000
75%       97.387500
max      143.240000
Name: Ada1, dtype: float64

In [34]:
rows_ada1_above_100 = df_cleaned[df_cleaned['Ada1'] > 100]
rows_ada1_above_100

,Name_of_Regions,Unnamed: 1,Year,UrbanDistrictArea,UrbanDistrictPopulation,UrbanDistrictTemporaryPopulation,UrbanArea,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,...,Unnamed: 45,Parkland_per_capita,PUI,URI,LUI,EUI,EAL,Res1,Res2,Ada1
186,荆州,Jingzhou,2010,1576.00,131.23,2.91,66.40,68.61,2.58,66.40,...,荆州市,9.51,0.2466,0.000536,0.004715,0.7080,503.819938,0.00086,0.006669,143.24
207,深圳,Shenzhen,2010,1991.64,1035.79,0.00,1991.64,1035.79,0.00,830.01,...,深圳市,16.40,1.0000,0.046005,0.427180,0.9992,42209.560473,0.00011,0.000011,134.74

In [35]:
df_cleaned['Ada2'] = df_cleaned['Rate_of_non_hazardous_treatment_of_domestic_waste(%)'] 
df_cleaned['Ada2'].describe()

/tmp/ipykernel_4090/2482281589.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Ada2'] = df_cleaned['Rate_of_non_hazardous_treatment_of_domestic_waste(%)']

count    290.000000
mean      78.119931
std       28.284028
min        0.000000
25%       67.000000
50%       90.015000
75%      100.000000
max      100.000000
Name: Ada2, dtype: float64

In [36]:
rows_ada2_above_100 = df_cleaned[df_cleaned['Ada2'] > 100]
rows_ada2_above_100

Empty DataFrame
Columns: [Name_of_Regions, Unnamed: 1, Year, UrbanDistrictArea, UrbanDistrictPopulation, UrbanDistrictTemporaryPopulation, UrbanArea, UrbanPopulation, UrbanTemporaryPopulation, Surface_Area_of_Built_District, Area_of_Urban_Construction_Land_Subtotal, Residential, Area_for Public_Utilities, Area_for_Industrial_Overation, Area_for_Storage, Area_for_Traffic_System, Area_for_Roads_and_Plazas, Area_for_Municipal_Utilities, Greenland_Area, Area_for_Specialpurpose, Area_of_Land_Requisition_this_Year, Arable_Land, Road_Surface_Area_Per_Capita_m2, Unnamed: 23, Total_population_of_the_region, Unnamed: 25, Population_urbanization, Unnamed: 27, GDP, Unnamed: 29, First_sector_of_GDP, Unnamed: 31, Unnamed: 32, Citycode, Area_of_administrative_districts, Unnamed: 35, Industrial_wastewater_discharge_(tonnes), Industrial_sulphur_dioxide_emissions_(tonnes), Industrial_fume_emissions_(tonnes),     城市, Comprehensive_industrial_solid_waste_utilisation_rate(%), Urban_domestic_sewage_treatment_rate(%), Rate_of_non_hazardous_treatment_of_domestic_waste(%), CITY, Greening_coverage_in_builtup_areas, Unnamed: 45, Parkland_per_capita, PUI, URI, LUI, EUI, EAL, Res1, Res2, Ada1, Ada2]
Index: []

[0 rows x 56 columns]

In [37]:
df_cleaned['Rec1'] = df_cleaned['Greening_coverage_in_builtup_areas'] 
df_cleaned['Rec2'] = df_cleaned['Parkland_per_capita']

/tmp/ipykernel_4090/1792138184.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Rec1'] = df_cleaned['Greening_coverage_in_builtup_areas']
/tmp/ipykernel_4090/1792138184.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Rec2'] = df_cleaned['Parkland_per_capita']

In [38]:
df_cleaned['Rec1'].describe()

count    290.000000
mean      38.220931
std        8.455952
min        0.000000
25%       35.122500
50%       39.260000
75%       42.267500
max       70.720000
Name: Rec1, dtype: float64

In [39]:
rows_rec1_above_100 = df_cleaned[df_cleaned['Rec1'] > 100]
rows_rec1_above_100

Empty DataFrame
Columns: [Name_of_Regions, Unnamed: 1, Year, UrbanDistrictArea, UrbanDistrictPopulation, UrbanDistrictTemporaryPopulation, UrbanArea, UrbanPopulation, UrbanTemporaryPopulation, Surface_Area_of_Built_District, Area_of_Urban_Construction_Land_Subtotal, Residential, Area_for Public_Utilities, Area_for_Industrial_Overation, Area_for_Storage, Area_for_Traffic_System, Area_for_Roads_and_Plazas, Area_for_Municipal_Utilities, Greenland_Area, Area_for_Specialpurpose, Area_of_Land_Requisition_this_Year, Arable_Land, Road_Surface_Area_Per_Capita_m2, Unnamed: 23, Total_population_of_the_region, Unnamed: 25, Population_urbanization, Unnamed: 27, GDP, Unnamed: 29, First_sector_of_GDP, Unnamed: 31, Unnamed: 32, Citycode, Area_of_administrative_districts, Unnamed: 35, Industrial_wastewater_discharge_(tonnes), Industrial_sulphur_dioxide_emissions_(tonnes), Industrial_fume_emissions_(tonnes),     城市, Comprehensive_industrial_solid_waste_utilisation_rate(%), Urban_domestic_sewage_treatment_rate(%), Rate_of_non_hazardous_treatment_of_domestic_waste(%), CITY, Greening_coverage_in_builtup_areas, Unnamed: 45, Parkland_per_capita, PUI, URI, LUI, EUI, EAL, Res1, Res2, Ada1, Ada2, Rec1, Rec2]
Index: []

[0 rows x 58 columns]

In [40]:
df_cleaned['Rec2'].describe()

count    290.000000
mean      11.432172
std        4.115226
min        0.000000
25%        8.995000
50%       10.950000
75%       13.660000
max       29.900000
Name: Rec2, dtype: float64

In [43]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 290 entries, 0 to 318
Data columns (total 58 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   Name_of_Regions                                           290 non-null    object
 1   Unnamed: 1                                                290 non-null    object
 2   Year                                                      290 non-null    int64
 3   UrbanDistrictArea                                         290 non-null    float64
 4   UrbanDistrictPopulation                                   290 non-null    float64
 5   UrbanDistrictTemporaryPopulation                          290 non-null    float64
 6   UrbanArea                                                 290 non-null    float64
 7   UrbanPopulation                                           290 non-null    float64
 8   UrbanTemporaryPopulation                                  290 non-null    float64
 9   Surface_Area_of_Built_District                            290 non-null    float64
 10  Area_of_Urban_Construction_Land_Subtotal                  286 non-null    float64
 11  Residential                                               286 non-null    float64
 12  Area_for Public_Utilities                                 286 non-null    object
 13  Area_for_Industrial_Overation                             286 non-null    float64
 14  Area_for_Storage                                          286 non-null    float64
 15  Area_for_Traffic_System                                   286 non-null    float64
 16  Area_for_Roads_and_Plazas                                 286 non-null    float64
 17  Area_for_Municipal_Utilities                              286 non-null    float64
 18  Greenland_Area                                            286 non-null    object
 19  Area_for_Specialpurpose                                   273 non-null    float64
 20  Area_of_Land_Requisition_this_Year                        193 non-null    float64
 21  Arable_Land                                               144 non-null    float64
 22  Road_Surface_Area_Per_Capita_m2                           290 non-null    float64
 23  Unnamed: 23                                               289 non-null    object
 24  Total_population_of_the_region                            290 non-null    float64
 25  Unnamed: 25                                               0 non-null      float64
 26  Population_urbanization                                   290 non-null    float64
 27  Unnamed: 27                                               289 non-null    object
 28  GDP                                                       290 non-null    float64
 29  Unnamed: 29                                               289 non-null    object
 30  First_sector_of_GDP                                       290 non-null    float64
 31  Unnamed: 31                                               0 non-null      float64
 32  Unnamed: 32                                               289 non-null    object
 33  Citycode                                                  290 non-null    float64
 34  Area_of_administrative_districts                          290 non-null    float64
 35  Unnamed: 35                                               289 non-null    object
 36  Industrial_wastewater_discharge_(tonnes)                  290 non-null    float64
 37  Industrial_sulphur_dioxide_emissions_(tonnes)             285 non-null    float64
 38  Industrial_fume_emissions_(tonnes)                        290 non-null    float64
 39      城市                                                    289 non-null    object
 40  Comprehensive_industrial_solid_waste_utilisation_rate(%)  290 non-null    float64
 41  Urban_domestic_sewage_treatment_rate(%)                   279 non-null    float64
 42  Rate_of_non_hazardous_treatment_of_domestic_waste(%)      290 non-null    float64
 43  CITY                                                      285 non-null    object
 44  Greening_coverage_in_builtup_areas                        290 non-null    float64
 45  Unnamed: 45                                               285 non-null    object
 46  Parkland_per_capita                                       290 non-null    float64
 47  PUI                                                       290 non-null    float64
 48  URI                                                       290 non-null    float64
 49  LUI                                                       290 non-null    float64
 50  EUI                                                       290 non-null    float64
 51  EAL                                                       290 non-null    float64
 52  Res1                                                      290 non-null    float64
 53  Res2                                                      290 non-null    float64
 54  Ada1                                                      290 non-null    float64
 55  Ada2                                                      290 non-null    float64
 56  Rec1                                                      290 non-null    float64
 57  Rec2                                                      290 non-null    float64
dtypes: float64(45), int64(1), object(12)
memory usage: 133.7+ KB

In [44]:
columns_to_keep = ['Name_of_Regions','Citycode','Year','Res1','Res2','Ada1','Ada2','Rec1','Rec2']
uer_index_2010 = df_cleaned[columns_to_keep]
uer_index_2010.to_csv('data/UER_index_2010.csv', index=False)

# 熵权法
# 标准化

In [41]:
# Initialize a column for the normalized values
data_merged['X1_star'] = pd.Series(dtype='float')
column_to_normalize = 'PUI'
# Iterate over each year to perform the normalization
for year in range(2010, 2011):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X1_max = year_data[column_to_normalize].max()
    X1_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X1_star'] = (year_data[column_to_normalize] - X1_min) / (X1_max - X1_min)

# Initialize a column for the normalized values
data_merged['X2_star'] = pd.Series(dtype='float')
column_to_normalize = 'URI'
# Iterate over each year to perform the normalization
for year in range(2010, 2011):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X2_max = year_data[column_to_normalize].max()
    X2_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X2_star'] = (year_data[column_to_normalize] - X2_min) / (X2_max - X2_min)

data_merged['X3_star'] = pd.Series(dtype='float')
column_to_normalize = 'LUI'
# Iterate over each year to perform the normalization
for year in range(2010, 2011):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X3_max = year_data[column_to_normalize].max()
    X3_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X3_star'] = (year_data[column_to_normalize] - X3_min) / (X3_max - X3_min)

data_merged['X4_star'] = pd.Series(dtype='float')
column_to_normalize = 'EUI'
# Iterate over each year to perform the normalization
for year in range(2010, 2011):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X4_max = year_data[column_to_normalize].max()
    X4_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X4_star'] = (year_data[column_to_normalize] - X4_min) / (X4_max - X4_min)

data_merged['X5_star'] = pd.Series(dtype='float')
column_to_normalize = 'EAL'
# Iterate over each year to perform the normalization
for year in range(2010, 2011):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X5_max = year_data[column_to_normalize].max()
    X5_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X5_star'] = (year_data[column_to_normalize] - X5_min) / (X5_max - X5_min)


data_merged['X6_star'] = pd.Series(dtype='float')
column_to_normalize = 'LUL'
# Iterate over each year to perform the normalization
for year in range(2010, 2011):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X6_max = year_data[column_to_normalize].max()
    X6_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X6_star'] = (year_data[column_to_normalize] - X6_min) / (X6_max - X6_min)

In [42]:
data_merged

,Name_of_Regions,Unnamed: 1,Year,UrbanDistrictArea,UrbanDistrictPopulation,UrbanDistrictTemporaryPopulation,UrbanArea,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,...,LUI,EUI,EAL,LUL,X1_star,X2_star,X3_star,X4_star,X5_star,X6_star
0,北京,Beijing,2010,16410.00,1961.20,0.00,12187.00,1685.90,0.00,1186.00,...,0.072295,0.9903,7408.107284,265.965018,0.823198,0.118204,0.169101,0.979928,0.175425,0.810060
1,天津,Tianjin,2010,7398.86,807.02,38.44,2236.12,587.40,27.89,686.71,...,0.057591,0.9829,6308.160013,302.537533,0.726052,0.158697,0.134673,0.963239,0.149364,0.935477
2,石家庄,Shijiazhuang,2010,455.80,245.35,20.74,212.54,227.60,17.67,202.90,...,0.014433,0.8973,2134.926519,285.652043,0.312197,0.060874,0.033627,0.770185,0.050484,0.877572
3,唐山,Tangshan,2010,3874.00,305.62,4.00,1230.20,193.08,4.00,234.00,...,0.016947,0.9055,2761.239282,296.218637,0.224642,0.044500,0.039512,0.788678,0.065324,0.913808
4,秦皇岛,Qinhuangdao,2010,363.20,82.97,7.13,363.20,82.97,7.13,89.48,...,0.011484,0.8728,1032.523229,264.130224,0.329008,0.046357,0.026721,0.714930,0.024364,0.803768
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,固原,Guyuan,2010,4489.00,47.00,7.28,34.62,15.30,5.58,34.62,...,0.003290,0.7255,83.549981,244.783708,0.009590,0.007713,0.007537,0.382724,0.001880,0.737424
286,中卫,Zhongwei,2010,5358.10,39.59,0.86,52.00,18.30,0.12,32.04,...,0.002346,0.8186,104.679991,207.569339,0.116439,0.005199,0.005327,0.592693,0.002380,0.609806
287,新疆,xinjiang,2010,240068.23,854.99,98.25,1267.62,549.12,81.76,838.21,...,0.000514,0.8020,33.346723,65.635689,0.323705,0.000952,0.001038,0.555255,0.000690,0.123079
288,乌鲁木齐,Urumuchi,2010,14216.30,279.20,36.16,342.67,243.04,36.16,342.67,...,0.024844,0.9850,793.532951,138.231543,0.971116,0.029936,0.058002,0.967975,0.018702,0.372029
289,克拉玛依,Kelamayi,2010,9548.00,26.13,8.73,57.16,26.13,8.73,57.16,...,0.007752,0.9934,651.330214,69.640647,0.738915,0.022956,0.017984,0.986919,0.015332,0.136813

In [43]:
columns_to_keep = ['Name_of_Regions','Citycode','Year','X1_star','X2_star','X3_star','X4_star','X5_star','X6_star']
data_process_UI = data_merged[columns_to_keep]

In [44]:
data_process_UI

,Name_of_Regions,Citycode,Year,X1_star,X2_star,X3_star,X4_star,X5_star,X6_star
0,北京,110000.0,2010,0.823198,0.118204,0.169101,0.979928,0.175425,0.810060
1,天津,120000.0,2010,0.726052,0.158697,0.134673,0.963239,0.149364,0.935477
2,石家庄,130100.0,2010,0.312197,0.060874,0.033627,0.770185,0.050484,0.877572
3,唐山,130200.0,2010,0.224642,0.044500,0.039512,0.788678,0.065324,0.913808
4,秦皇岛,130300.0,2010,0.329008,0.046357,0.026721,0.714930,0.024364,0.803768
...,...,...,...,...,...,...,...,...,...
285,固原,640400.0,2010,0.009590,0.007713,0.007537,0.382724,0.001880,0.737424
286,中卫,640500.0,2010,0.116439,0.005199,0.005327,0.592693,0.002380,0.609806
287,新疆,650000.0,2010,0.323705,0.000952,0.001038,0.555255,0.000690,0.123079
288,乌鲁木齐,650100.0,2010,0.971116,0.029936,0.058002,0.967975,0.018702,0.372029
289,克拉玛依,650200.0,2010,0.738915,0.022956,0.017984,0.986919,0.015332,0.136813

In [45]:
#1.7熵权法

def calculate_entropy(indicator_data):
    # Replace zero values to avoid log(0) and negative infinity in entropy calculation
    indicator_data = indicator_data.replace(0, np.finfo(float).eps)  # Use a small number instead of zero
    p_ij = indicator_data / indicator_data.sum()  # Calculate the proportion p_ij
    K = 1 / np.log(290)  # Calculate the constant K
    e_j = -K * (p_ij * np.log(p_ij)).sum()  # Calculate the entropy e_j
    return e_j

# Initialize an empty list to store DataFrames for each year
dataframes_list = []

# Calculate entropies and weights for each year
for year in range(2010, 2011):
    year_data = data_process_UI[data_process_UI['Year'] == year].copy()
    entropies = year_data[['X1_star', 'X2_star', 'X3_star', 'X4_star','X5_star','X6_star']].apply(calculate_entropy, axis=0)
    weights = (1 - entropies) / (1 - entropies).sum()  # Calculate weights, ensuring they sum up to 1 within the year
    for i, indicator in enumerate(['X1_star', 'X2_star', 'X3_star', 'X4_star','X5_star','X6_star']):
        year_data[indicator + '_weighted'] = year_data[indicator] * weights.values[i]  # Apply weights to the indicators
    dataframes_list.append(year_data)  # Append the yearly data to the list

# Concatenate all DataFrames in the list to create the comprehensive_scores DataFrame
UI = pd.concat(dataframes_list, ignore_index=True)

# Now you should have the comprehensive_scores DataFrame with correctly calculated weights per year

In [46]:
UI

,Name_of_Regions,Citycode,Year,X1_star,X2_star,X3_star,X4_star,X5_star,X6_star,X1_star_weighted,X2_star_weighted,X3_star_weighted,X4_star_weighted,X5_star_weighted,X6_star_weighted
0,北京,110000.0,2010,0.823198,0.118204,0.169101,0.979928,0.175425,0.810060,0.045384,0.038459,0.052908,0.013495,0.049970,0.006489
1,天津,120000.0,2010,0.726052,0.158697,0.134673,0.963239,0.149364,0.935477,0.040028,0.051633,0.042136,0.013265,0.042546,0.007493
2,石家庄,130100.0,2010,0.312197,0.060874,0.033627,0.770185,0.050484,0.877572,0.017212,0.019806,0.010521,0.010606,0.014381,0.007030
3,唐山,130200.0,2010,0.224642,0.044500,0.039512,0.788678,0.065324,0.913808,0.012385,0.014478,0.012363,0.010861,0.018608,0.007320
4,秦皇岛,130300.0,2010,0.329008,0.046357,0.026721,0.714930,0.024364,0.803768,0.018139,0.015082,0.008361,0.009845,0.006940,0.006438
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,固原,640400.0,2010,0.009590,0.007713,0.007537,0.382724,0.001880,0.737424,0.000529,0.002510,0.002358,0.005270,0.000535,0.005907
286,中卫,640500.0,2010,0.116439,0.005199,0.005327,0.592693,0.002380,0.609806,0.006419,0.001691,0.001667,0.008162,0.000678,0.004885
287,新疆,650000.0,2010,0.323705,0.000952,0.001038,0.555255,0.000690,0.123079,0.017846,0.000310,0.000325,0.007646,0.000197,0.000986
288,乌鲁木齐,650100.0,2010,0.971116,0.029936,0.058002,0.967975,0.018702,0.372029,0.053538,0.009740,0.018148,0.013330,0.005327,0.002980
289,克拉玛依,650200.0,2010,0.738915,0.022956,0.017984,0.986919,0.015332,0.136813,0.040737,0.007469,0.005627,0.013591,0.004367,0.001096

In [47]:
# Calculate the combined weighted values for Resistance, Adaptability, and Recovery
UI['PU'] = UI['X1_star_weighted'] + UI['X2_star_weighted']
UI['LU'] = UI['X3_star_weighted'] + UI['X6_star_weighted']
#comprehensive_scores['ADA'] = comprehensive_scores['X2_star_weighted'] 
UI['EU'] = UI['X4_star_weighted'] + UI['X5_star_weighted']

# Assuming data_merged is the DataFrame with the standardized 'RES', 'ADA', and 'REC' columns.

# Define a small positive value to add to REC to avoid zero values
small_positive_value = 1e-6

# Replace zero values in REC with the small positive value
UI['PU_adj'] = UI['PU'].replace(0, small_positive_value)
UI['LU_adj'] = UI['LU'].replace(0, small_positive_value)
UI['EU_adj'] = UI['EU'].replace(0, small_positive_value)

# Now, the UER values should not be zero due to REC being zero, since we have adjusted REC values slightly above zero.

# Calculate the Urban Ecological Resilience (UER) for each borough and year
UI['UI'] = UI['PU_adj'] + UI['LU_adj'] + UI['EU_adj']

# Check the result
UI[['Year', 'Name_of_Regions', 'PU', 'LU', 'EU', 'UI']].head()

   Year Name_of_Regions        PU        LU        EU        UI
0  2010              北京  0.083842  0.059397  0.063465  0.206704
1  2010              天津  0.091661  0.049630  0.055811  0.197102
2  2010             石家庄  0.037017  0.017551  0.024987  0.079555
3  2010              唐山  0.026863  0.019682  0.029468  0.076014
4  2010             秦皇岛  0.033221  0.014799  0.016785  0.064805

In [48]:
UI

,Name_of_Regions,Citycode,Year,X1_star,X2_star,X3_star,X4_star,X5_star,X6_star,X1_star_weighted,...,X4_star_weighted,X5_star_weighted,X6_star_weighted,PU,LU,EU,PU_adj,LU_adj,EU_adj,UI
0,北京,110000.0,2010,0.823198,0.118204,0.169101,0.979928,0.175425,0.810060,0.045384,...,0.013495,0.049970,0.006489,0.083842,0.059397,0.063465,0.083842,0.059397,0.063465,0.206704
1,天津,120000.0,2010,0.726052,0.158697,0.134673,0.963239,0.149364,0.935477,0.040028,...,0.013265,0.042546,0.007493,0.091661,0.049630,0.055811,0.091661,0.049630,0.055811,0.197102
2,石家庄,130100.0,2010,0.312197,0.060874,0.033627,0.770185,0.050484,0.877572,0.017212,...,0.010606,0.014381,0.007030,0.037017,0.017551,0.024987,0.037017,0.017551,0.024987,0.079555
3,唐山,130200.0,2010,0.224642,0.044500,0.039512,0.788678,0.065324,0.913808,0.012385,...,0.010861,0.018608,0.007320,0.026863,0.019682,0.029468,0.026863,0.019682,0.029468,0.076014
4,秦皇岛,130300.0,2010,0.329008,0.046357,0.026721,0.714930,0.024364,0.803768,0.018139,...,0.009845,0.006940,0.006438,0.033221,0.014799,0.016785,0.033221,0.014799,0.016785,0.064805
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,固原,640400.0,2010,0.009590,0.007713,0.007537,0.382724,0.001880,0.737424,0.000529,...,0.005270,0.000535,0.005907,0.003038,0.008265,0.005806,0.003038,0.008265,0.005806,0.017109
286,中卫,640500.0,2010,0.116439,0.005199,0.005327,0.592693,0.002380,0.609806,0.006419,...,0.008162,0.000678,0.004885,0.008111,0.006551,0.008840,0.008111,0.006551,0.008840,0.023502
287,新疆,650000.0,2010,0.323705,0.000952,0.001038,0.555255,0.000690,0.123079,0.017846,...,0.007646,0.000197,0.000986,0.018156,0.001311,0.007843,0.018156,0.001311,0.007843,0.027310
288,乌鲁木齐,650100.0,2010,0.971116,0.029936,0.058002,0.967975,0.018702,0.372029,0.053538,...,0.013330,0.005327,0.002980,0.063278,0.021128,0.018657,0.063278,0.021128,0.018657,0.103063
289,克拉玛依,650200.0,2010,0.738915,0.022956,0.017984,0.986919,0.015332,0.136813,0.040737,...,0.013591,0.004367,0.001096,0.048206,0.006723,0.017958,0.048206,0.006723,0.017958,0.072887

In [49]:
columns_to_keep = ['Name_of_Regions','Citycode','Year','Res1','Res2','Ada1','Ada2','Rec1','Rec2']
data_merged = df_cleaned[columns_to_keep]

In [50]:
data_merged

,Name_of_Regions,Citycode,Year,Res1,Res2,Ada1,Ada2,Rec1,Rec2
0,北京,110000.0,2010,0.000067,0.000175,65.82,96.95,55.10,11.28
1,天津,120000.0,2010,0.000262,0.000716,98.37,100.00,32.04,8.56
3,石家庄,130100.0,2010,0.000642,0.001087,93.36,100.00,43.01,14.39
4,唐山,130200.0,2010,0.000477,0.002588,80.55,100.00,46.00,15.13
5,秦皇岛,130300.0,2010,0.000697,0.001413,59.57,100.00,50.24,19.90
...,...,...,...,...,...,...,...,...,...
314,固原,640400.0,2010,0.000161,0.001137,99.20,100.00,28.31,8.52
315,中卫,640500.0,2010,0.003707,0.019466,60.61,45.09,26.03,11.62
316,新疆,650000.0,2010,0.000136,0.000717,47.50,70.58,36.40,8.61
317,乌鲁木齐,650100.0,2010,0.000532,0.003014,68.20,87.40,34.77,7.39
318,克拉玛依,650200.0,2010,0.000329,0.001251,63.55,94.87,50.68,9.04

In [51]:
# Initialize a column for the normalized values
data_merged['X1_star'] = pd.Series(dtype='float')
column_to_normalize = 'Res1'
# Iterate over each year to perform the normalization
for year in range(2010, 2011):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X1_max = year_data[column_to_normalize].max()
    X1_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X1_star'] = (X1_max - year_data[column_to_normalize]) / (X1_max - X1_min)


# Initialize a column for the normalized values
data_merged['X2_star'] = pd.Series(dtype='float')
column_to_normalize = 'Res2'
# Iterate over each year to perform the normalization
for year in range(2010, 2011):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X2_max = year_data[column_to_normalize].max()
    X2_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X2_star'] = (X2_max - year_data[column_to_normalize]) / (X2_max - X2_min)

data_merged['X3_star'] = pd.Series(dtype='float')
column_to_normalize = 'Ada1'
# Iterate over each year to perform the normalization
for year in range(2010, 2011):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X3_max = year_data[column_to_normalize].max()
    X3_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X3_star'] = (year_data[column_to_normalize] - X3_min) / (X3_max - X3_min)

data_merged['X4_star'] = pd.Series(dtype='float')
column_to_normalize = 'Ada2'
# Iterate over each year to perform the normalization
for year in range(2010, 2011):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X4_max = year_data[column_to_normalize].max()
    X4_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X4_star'] = (year_data[column_to_normalize] - X4_min) / (X4_max - X4_min)

data_merged['X5_star'] = pd.Series(dtype='float')
column_to_normalize = 'Rec1'
# Iterate over each year to perform the normalization
for year in range(2010, 2011):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X5_max = year_data[column_to_normalize].max()
    X5_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X5_star'] = (year_data[column_to_normalize] - X5_min) / (X5_max - X5_min)

data_merged['X6_star'] = pd.Series(dtype='float')
column_to_normalize = 'Rec2'
# Iterate over each year to perform the normalization
for year in range(2010, 2011):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X6_max = year_data[column_to_normalize].max()
    X6_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X6_star'] = (year_data[column_to_normalize] - X6_min) / (X6_max - X6_min)

/tmp/ipykernel_31992/2293287907.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_merged['X1_star'] = pd.Series(dtype='float')
/tmp/ipykernel_31992/2293287907.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_merged['X2_star'] = pd.Series(dtype='float')
/tmp/ipykernel_31992/2293287907.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_merged['X3_star'] = pd.Series(dtype='float')
/tmp/ipykernel_31992/2293287907.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_merged['X4_star'] = pd.Series(dtype='float')
/tmp/ipykernel_31992/2293287907.py:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_merged['X5_star'] = pd.Series(dtype='float')
/tmp/ipykernel_31992/2293287907.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_merged['X6_star'] = pd.Series(dtype='float')

In [52]:
data_merged

,Name_of_Regions,Citycode,Year,Res1,Res2,Ada1,Ada2,Rec1,Rec2,X1_star,X2_star,X3_star,X4_star,X5_star,X6_star
0,北京,110000.0,2010,0.000067,0.000175,65.82,96.95,55.10,11.28,0.996060,0.993426,0.459509,0.9695,0.779129,0.377258
1,天津,120000.0,2010,0.000262,0.000716,98.37,100.00,32.04,8.56,0.984718,0.973112,0.686750,1.0000,0.453054,0.286288
3,石家庄,130100.0,2010,0.000642,0.001087,93.36,100.00,43.01,14.39,0.962529,0.959151,0.651773,1.0000,0.608173,0.481271
4,唐山,130200.0,2010,0.000477,0.002588,80.55,100.00,46.00,15.13,0.972164,0.902769,0.562343,1.0000,0.650452,0.506020
5,秦皇岛,130300.0,2010,0.000697,0.001413,59.57,100.00,50.24,19.90,0.959286,0.946927,0.415875,1.0000,0.710407,0.665552
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,固原,640400.0,2010,0.000161,0.001137,99.20,100.00,28.31,8.52,0.990567,0.957270,0.692544,1.0000,0.400311,0.284950
315,中卫,640500.0,2010,0.003707,0.019466,60.61,45.09,26.03,11.62,0.783491,0.268636,0.423136,0.4509,0.368071,0.388629
316,新疆,650000.0,2010,0.000136,0.000717,47.50,70.58,36.40,8.61,0.992049,0.973050,0.331611,0.7058,0.514706,0.287960
317,乌鲁木齐,650100.0,2010,0.000532,0.003014,68.20,87.40,34.77,7.39,0.968931,0.886746,0.476124,0.8740,0.491657,0.247157
318,克拉玛依,650200.0,2010,0.000329,0.001251,63.55,94.87,50.68,9.04,0.980785,0.952986,0.443661,0.9487,0.716629,0.302341

In [53]:
columns_to_keep = ['Name_of_Regions','Citycode','Year','X1_star','X2_star','X3_star','X4_star','X5_star','X6_star']
data_process = data_merged[columns_to_keep]

In [54]:
#1.7熵权法

def calculate_entropy(indicator_data):
    # Replace zero values to avoid log(0) and negative infinity in entropy calculation
    indicator_data = indicator_data.replace(0, np.finfo(float).eps)  # Use a small number instead of zero
    p_ij = indicator_data / indicator_data.sum()  # Calculate the proportion p_ij
    K = 1 / np.log(290)  # Calculate the constant K
    e_j = -K * (p_ij * np.log(p_ij)).sum()  # Calculate the entropy e_j
    return e_j

# Initialize an empty list to store DataFrames for each year
dataframes_list = []

# Calculate entropies and weights for each year
for year in range(2010, 2011):
    year_data = data_process[data_process['Year'] == year].copy()
    entropies = year_data[['X1_star', 'X2_star', 'X3_star', 'X4_star','X5_star','X6_star']].apply(calculate_entropy, axis=0)
    weights = (1 - entropies) / (1 - entropies).sum()  # Calculate weights, ensuring they sum up to 1 within the year
    for i, indicator in enumerate(['X1_star', 'X2_star', 'X3_star', 'X4_star','X5_star','X6_star']):
        year_data[indicator + '_weighted'] = year_data[indicator] * weights.values[i]  # Apply weights to the indicators
    dataframes_list.append(year_data)  # Append the yearly data to the list

# Concatenate all DataFrames in the list to create the comprehensive_scores DataFrame
UER = pd.concat(dataframes_list, ignore_index=True)

# Now you should have the comprehensive_scores DataFrame with correctly calculated weights per year

In [55]:
UER

,Name_of_Regions,Citycode,Year,X1_star,X2_star,X3_star,X4_star,X5_star,X6_star,X1_star_weighted,X2_star_weighted,X3_star_weighted,X4_star_weighted,X5_star_weighted,X6_star_weighted
0,北京,110000.0,2010,0.996060,0.993426,0.459509,0.9695,0.779129,0.377258,0.017033,0.038971,0.089941,0.365253,0.091064,0.095942
1,天津,120000.0,2010,0.984718,0.973112,0.686750,1.0000,0.453054,0.286288,0.016839,0.038174,0.134420,0.376743,0.052953,0.072807
2,石家庄,130100.0,2010,0.962529,0.959151,0.651773,1.0000,0.608173,0.481271,0.016460,0.037626,0.127574,0.376743,0.071083,0.122394
3,唐山,130200.0,2010,0.972164,0.902769,0.562343,1.0000,0.650452,0.506020,0.016625,0.035415,0.110069,0.376743,0.076025,0.128688
4,秦皇岛,130300.0,2010,0.959286,0.946927,0.415875,1.0000,0.710407,0.665552,0.016404,0.037147,0.081401,0.376743,0.083032,0.169259
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,固原,640400.0,2010,0.990567,0.957270,0.692544,1.0000,0.400311,0.284950,0.016939,0.037553,0.135554,0.376743,0.046788,0.072467
286,中卫,640500.0,2010,0.783491,0.268636,0.423136,0.4509,0.368071,0.388629,0.013398,0.010538,0.082822,0.169874,0.043020,0.098834
287,新疆,650000.0,2010,0.992049,0.973050,0.331611,0.7058,0.514706,0.287960,0.016965,0.038172,0.064907,0.265905,0.060159,0.073232
288,乌鲁木齐,650100.0,2010,0.968931,0.886746,0.476124,0.8740,0.491657,0.247157,0.016569,0.034786,0.093193,0.329274,0.057465,0.062856
289,克拉玛依,650200.0,2010,0.980785,0.952986,0.443661,0.9487,0.716629,0.302341,0.016772,0.037385,0.086839,0.357416,0.083759,0.076890

In [56]:
# Calculate the combined weighted values for Resistance, Adaptability, and Recovery
UER['RES'] = UER['X1_star_weighted'] + UER['X2_star_weighted']
UER['ADA'] = UER['X3_star_weighted'] + UER['X4_star_weighted']
#comprehensive_scores['ADA'] = comprehensive_scores['X2_star_weighted'] 
UER['REC'] = UER['X5_star_weighted'] + UER['X6_star_weighted']

# Assuming data_merged is the DataFrame with the standardized 'RES', 'ADA', and 'REC' columns.

# Define a small positive value to add to REC to avoid zero values
small_positive_value = 1e-6

# Replace zero values in REC with the small positive value
UER['REC_adj'] = UER['REC'].replace(0, small_positive_value)
UER['ADA_adj'] = UER['ADA'].replace(0, small_positive_value)
UER['RES_adj'] = UER['RES'].replace(0, small_positive_value)

# Now, the UER values should not be zero due to REC being zero, since we have adjusted REC values slightly above zero.

# Calculate the Urban Ecological Resilience (UER) for each borough and year
UER['UER'] = (UER['RES_adj'] * UER['ADA_adj'] * UER['REC_adj']) ** (1/3)

# Check the result
UER[['Year', 'Name_of_Regions', 'RES', 'ADA', 'REC', 'UER']].head()

   Year Name_of_Regions       RES       ADA       REC       UER
0  2010              北京  0.056004  0.455194  0.187006  0.168303
1  2010              天津  0.055013  0.511163  0.125760  0.152355
2  2010             石家庄  0.054086  0.504317  0.193477  0.174103
3  2010              唐山  0.052039  0.486813  0.204713  0.173093
4  2010             秦皇岛  0.053551  0.458144  0.252291  0.183608

In [57]:
UER

,Name_of_Regions,Citycode,Year,X1_star,X2_star,X3_star,X4_star,X5_star,X6_star,X1_star_weighted,...,X4_star_weighted,X5_star_weighted,X6_star_weighted,RES,ADA,REC,REC_adj,ADA_adj,RES_adj,UER
0,北京,110000.0,2010,0.996060,0.993426,0.459509,0.9695,0.779129,0.377258,0.017033,...,0.365253,0.091064,0.095942,0.056004,0.455194,0.187006,0.187006,0.455194,0.056004,0.168303
1,天津,120000.0,2010,0.984718,0.973112,0.686750,1.0000,0.453054,0.286288,0.016839,...,0.376743,0.052953,0.072807,0.055013,0.511163,0.125760,0.125760,0.511163,0.055013,0.152355
2,石家庄,130100.0,2010,0.962529,0.959151,0.651773,1.0000,0.608173,0.481271,0.016460,...,0.376743,0.071083,0.122394,0.054086,0.504317,0.193477,0.193477,0.504317,0.054086,0.174103
3,唐山,130200.0,2010,0.972164,0.902769,0.562343,1.0000,0.650452,0.506020,0.016625,...,0.376743,0.076025,0.128688,0.052039,0.486813,0.204713,0.204713,0.486813,0.052039,0.173093
4,秦皇岛,130300.0,2010,0.959286,0.946927,0.415875,1.0000,0.710407,0.665552,0.016404,...,0.376743,0.083032,0.169259,0.053551,0.458144,0.252291,0.252291,0.458144,0.053551,0.183608
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,固原,640400.0,2010,0.990567,0.957270,0.692544,1.0000,0.400311,0.284950,0.016939,...,0.376743,0.046788,0.072467,0.054492,0.512297,0.119255,0.119255,0.512297,0.054492,0.149317
286,中卫,640500.0,2010,0.783491,0.268636,0.423136,0.4509,0.368071,0.388629,0.013398,...,0.169874,0.043020,0.098834,0.023937,0.252695,0.141854,0.141854,0.252695,0.023937,0.095024
287,新疆,650000.0,2010,0.992049,0.973050,0.331611,0.7058,0.514706,0.287960,0.016965,...,0.265905,0.060159,0.073232,0.055136,0.330813,0.133391,0.133391,0.330813,0.055136,0.134498
288,乌鲁木齐,650100.0,2010,0.968931,0.886746,0.476124,0.8740,0.491657,0.247157,0.016569,...,0.329274,0.057465,0.062856,0.051355,0.422467,0.120320,0.120320,0.422467,0.051355,0.137691
289,克拉玛依,650200.0,2010,0.980785,0.952986,0.443661,0.9487,0.716629,0.302341,0.016772,...,0.357416,0.083759,0.076890,0.054157,0.444256,0.160649,0.160649,0.444256,0.054157,0.156935

In [58]:
df_merged1 = pd.merge(UI, UER, on=['Citycode', 'Year'])

In [59]:
df_merged1

,Name_of_Regions_x,Citycode,Year,X1_star_x,X2_star_x,X3_star_x,X4_star_x,X5_star_x,X6_star_x,X1_star_weighted_x,...,X4_star_weighted_y,X5_star_weighted_y,X6_star_weighted_y,RES,ADA,REC,REC_adj,ADA_adj,RES_adj,UER
0,北京,110000.0,2010,0.823198,0.118204,0.169101,0.979928,0.175425,0.810060,0.045384,...,0.365253,0.091064,0.095942,0.056004,0.455194,0.187006,0.187006,0.455194,0.056004,0.168303
1,天津,120000.0,2010,0.726052,0.158697,0.134673,0.963239,0.149364,0.935477,0.040028,...,0.376743,0.052953,0.072807,0.055013,0.511163,0.125760,0.125760,0.511163,0.055013,0.152355
2,石家庄,130100.0,2010,0.312197,0.060874,0.033627,0.770185,0.050484,0.877572,0.017212,...,0.376743,0.071083,0.122394,0.054086,0.504317,0.193477,0.193477,0.504317,0.054086,0.174103
3,唐山,130200.0,2010,0.224642,0.044500,0.039512,0.788678,0.065324,0.913808,0.012385,...,0.376743,0.076025,0.128688,0.052039,0.486813,0.204713,0.204713,0.486813,0.052039,0.173093
4,秦皇岛,130300.0,2010,0.329008,0.046357,0.026721,0.714930,0.024364,0.803768,0.018139,...,0.376743,0.083032,0.169259,0.053551,0.458144,0.252291,0.252291,0.458144,0.053551,0.183608
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,固原,640400.0,2010,0.009590,0.007713,0.007537,0.382724,0.001880,0.737424,0.000529,...,0.376743,0.046788,0.072467,0.054492,0.512297,0.119255,0.119255,0.512297,0.054492,0.149317
286,中卫,640500.0,2010,0.116439,0.005199,0.005327,0.592693,0.002380,0.609806,0.006419,...,0.169874,0.043020,0.098834,0.023937,0.252695,0.141854,0.141854,0.252695,0.023937,0.095024
287,新疆,650000.0,2010,0.323705,0.000952,0.001038,0.555255,0.000690,0.123079,0.017846,...,0.265905,0.060159,0.073232,0.055136,0.330813,0.133391,0.133391,0.330813,0.055136,0.134498
288,乌鲁木齐,650100.0,2010,0.971116,0.029936,0.058002,0.967975,0.018702,0.372029,0.053538,...,0.329274,0.057465,0.062856,0.051355,0.422467,0.120320,0.120320,0.422467,0.051355,0.137691
289,克拉玛依,650200.0,2010,0.738915,0.022956,0.017984,0.986919,0.015332,0.136813,0.040737,...,0.357416,0.083759,0.076890,0.054157,0.444256,0.160649,0.160649,0.444256,0.054157,0.156935

In [60]:
df_result = df_merged1[['Name_of_Regions_x', 'Citycode', 'Year', 'UER', 'UI']]

In [61]:
df_result

    Name_of_Regions_x  Citycode  Year       UER        UI
0                  北京  110000.0  2010  0.168303  0.206704
1                  天津  120000.0  2010  0.152355  0.197102
2                 石家庄  130100.0  2010  0.174103  0.079555
3                  唐山  130200.0  2010  0.173093  0.076014
4                 秦皇岛  130300.0  2010  0.183608  0.064805
..                ...       ...   ...       ...       ...
285                固原  640400.0  2010  0.149317  0.017109
286                中卫  640500.0  2010  0.095024  0.023502
287                新疆  650000.0  2010  0.134498  0.027310
288              乌鲁木齐  650100.0  2010  0.137691  0.103063
289              克拉玛依  650200.0  2010  0.156935  0.072887

[290 rows x 5 columns]

In [62]:
# 定义计算公式
def calculate_C(UI, UER):
    return np.sqrt((UI * UER) / ((UI + UER) / 2)**2)

def calculate_T(UI, UER, mu1=0.5, mu2=0.5):
    return mu1 * UI + mu2 * UER

def calculate_D(C, T):
    return np.sqrt(C * T)

# 计算C耦合度
df_result['C'] = df_result.apply(lambda row: calculate_C(row['UI'], row['UER']), axis=1)

# 计算T协调度
df_result['T'] = df_result.apply(lambda row: calculate_T(row['UI'], row['UER']), axis=1)

# 计算D耦合协调度
df_result['D'] = df_result.apply(lambda row: calculate_D(row['C'], row['T']), axis=1)

/tmp/ipykernel_31992/4091750289.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['C'] = df_result.apply(lambda row: calculate_C(row['UI'], row['UER']), axis=1)
/tmp/ipykernel_31992/4091750289.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['T'] = df_result.apply(lambda row: calculate_T(row['UI'], row['UER']), axis=1)
/tmp/ipykernel_31992/4091750289.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['D'] = df_result.apply(lambda row: calculate_D(row['C'], row['T']), axis=1)

In [63]:
# 定义归一化公式
def normalize(column):
    return (column - column.min()) / (column.max() - column.min())

# 归一化处理
df_result['UI_normalized'] = normalize(df_result['UI'])
df_result['UER_normalized'] = normalize(df_result['UER'])

# 定义计算公式
def calculate_C(UI, UER):
    return np.sqrt((UI * UER) / ((UI + UER) / 2)**2)

def calculate_T(UI, UER, mu1=0.5, mu2=0.5):
    return mu1 * UI + mu2 * UER

def calculate_D(C, T):
    return np.sqrt(C * T)

# 计算C耦合度
df_result['C2'] = df_result.apply(lambda row: calculate_C(row['UI_normalized'], row['UER_normalized']), axis=1)

# 计算T协调度
df_result['T2'] = df_result.apply(lambda row: calculate_T(row['UI_normalized'], row['UER_normalized']), axis=1)

# 计算D耦合协调度
df_result['D2'] = df_result.apply(lambda row: calculate_D(row['C2'], row['T2']), axis=1)

/tmp/ipykernel_31992/3512385329.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['UI_normalized'] = normalize(df_result['UI'])
/tmp/ipykernel_31992/3512385329.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['UER_normalized'] = normalize(df_result['UER'])
/tmp/ipykernel_31992/3512385329.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['C2'] = df_result.apply(lambda row: calculate_C(row['UI_normalized'], row['UER_normalized']), axis=1)
/tmp/ipykernel_31992/3512385329.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['T2'] = df_result.apply(lambda row: calculate_T(row['UI_normalized'], row['UER_normalized']), axis=1)
/tmp/ipykernel_31992/3512385329.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['D2'] = df_result.apply(lambda row: calculate_D(row['C2'], row['T2']), axis=1)

In [64]:
df_result

,Name_of_Regions_x,Citycode,Year,UER,UI,C,T,D,UI_normalized,UER_normalized,C2,T2,D2
0,北京,110000.0,2010,0.168303,0.206704,0.994743,0.187503,0.431877,0.200826,0.839766,0.789294,0.520296,0.640833
1,天津,120000.0,2010,0.152355,0.197102,0.991768,0.174729,0.416281,0.190941,0.760175,0.801130,0.475558,0.617239
2,石家庄,130100.0,2010,0.174103,0.079555,0.927936,0.126829,0.343059,0.069926,0.868715,0.525158,0.469321,0.496455
3,唐山,130200.0,2010,0.173093,0.076014,0.920939,0.124553,0.338683,0.066281,0.863673,0.514562,0.464977,0.489142
4,秦皇岛,130300.0,2010,0.183608,0.064805,0.878226,0.124207,0.330275,0.054742,0.916151,0.461319,0.485446,0.473229
...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,固原,640400.0,2010,0.149317,0.017109,0.607403,0.083213,0.224820,0.005639,0.745015,0.172687,0.375327,0.254586
286,中卫,640500.0,2010,0.095024,0.023502,0.797418,0.059263,0.217388,0.012220,0.474050,0.313042,0.243135,0.275883
287,新疆,650000.0,2010,0.134498,0.027310,0.749113,0.080904,0.246183,0.016140,0.671055,0.302887,0.343597,0.322601
288,乌鲁木齐,650100.0,2010,0.137691,0.103063,0.989602,0.120377,0.345146,0.094128,0.686991,0.651100,0.390560,0.504275
289,克拉玛依,650200.0,2010,0.156935,0.072887,0.930728,0.114911,0.327034,0.063062,0.783035,0.525271,0.423048,0.471397

In [65]:
# 导出comprehensive_scores数据框为Excel文件
output_excel_path = 'data/df_2010_result.xlsx'
df_result.to_excel(output_excel_path, index=False)

In [66]:
file_path = 'data/df_2006_result.xlsx'
df_result_2006 = pd.read_excel(file_path)

In [67]:
df_result_2006

,Name_of_Regions_x,Citycode,Year_x,UER,UI,C,T,D,UI_normalized,UER_normalized,C2,T2,D2
0,Beijing,110000,2006,0.137433,0.210078,0.977907,0.173756,0.412210,0.202760,0.702098,0.833949,0.452429,0.614250
1,Tianjin,120000,2006,0.103581,0.168235,0.971300,0.135908,0.363328,0.160479,0.529117,0.845124,0.344798,0.539812
2,Shijiazhuang,130100,2006,0.135975,0.075086,0.957483,0.105530,0.317873,0.066357,0.694645,0.564248,0.380501,0.463354
3,Tangshan,130200,2006,0.137393,0.076543,0.958697,0.106968,0.320234,0.067829,0.701890,0.566945,0.384860,0.467113
4,Qinhuangdao,130300,2006,0.140799,0.069600,0.941002,0.105200,0.314632,0.060814,0.719298,0.536204,0.390056,0.457329
...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,Guyuan,640400,2006,0.129806,0.020694,0.688750,0.075250,0.227659,0.011397,0.663123,0.257766,0.337260,0.294846
286,Zhongwei,640500,2006,0.126115,0.030682,0.793445,0.078398,0.249409,0.021489,0.644263,0.353476,0.332876,0.343022
287,Xinjiang,650000,2006,0.087788,0.075510,0.997170,0.081649,0.285338,0.066786,0.448413,0.671796,0.257600,0.415998
288,Urumuchi,650100,2006,0.100333,0.097620,0.999906,0.098976,0.314590,0.089127,0.512516,0.710475,0.300821,0.462305
289,Kelamayi,650200,2006,0.121824,0.102816,0.996414,0.112320,0.334540,0.094377,0.622335,0.676287,0.358356,0.492292

In [68]:
# 合并数据
df_merged2 = pd.merge(df_result_2006, df_result, left_on='Citycode', right_on='Citycode', suffixes=('_2006', '_2010'))

In [69]:
df_merged2

,Name_of_Regions_x_2006,Citycode,Year_x,UER_2006,UI_2006,C_2006,T_2006,D_2006,UI_normalized_2006,UER_normalized_2006,...,UER_2010,UI_2010,C_2010,T_2010,D_2010,UI_normalized_2010,UER_normalized_2010,C2_2010,T2_2010,D2_2010
0,Beijing,110000,2006,0.137433,0.210078,0.977907,0.173756,0.412210,0.202760,0.702098,...,0.168303,0.206704,0.994743,0.187503,0.431877,0.200826,0.839766,0.789294,0.520296,0.640833
1,Tianjin,120000,2006,0.103581,0.168235,0.971300,0.135908,0.363328,0.160479,0.529117,...,0.152355,0.197102,0.991768,0.174729,0.416281,0.190941,0.760175,0.801130,0.475558,0.617239
2,Shijiazhuang,130100,2006,0.135975,0.075086,0.957483,0.105530,0.317873,0.066357,0.694645,...,0.174103,0.079555,0.927936,0.126829,0.343059,0.069926,0.868715,0.525158,0.469321,0.496455
3,Tangshan,130200,2006,0.137393,0.076543,0.958697,0.106968,0.320234,0.067829,0.701890,...,0.173093,0.076014,0.920939,0.124553,0.338683,0.066281,0.863673,0.514562,0.464977,0.489142
4,Qinhuangdao,130300,2006,0.140799,0.069600,0.941002,0.105200,0.314632,0.060814,0.719298,...,0.183608,0.064805,0.878226,0.124207,0.330275,0.054742,0.916151,0.461319,0.485446,0.473229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,Guyuan,640400,2006,0.129806,0.020694,0.688750,0.075250,0.227659,0.011397,0.663123,...,0.149317,0.017109,0.607403,0.083213,0.224820,0.005639,0.745015,0.172687,0.375327,0.254586
286,Zhongwei,640500,2006,0.126115,0.030682,0.793445,0.078398,0.249409,0.021489,0.644263,...,0.095024,0.023502,0.797418,0.059263,0.217388,0.012220,0.474050,0.313042,0.243135,0.275883
287,Xinjiang,650000,2006,0.087788,0.075510,0.997170,0.081649,0.285338,0.066786,0.448413,...,0.134498,0.027310,0.749113,0.080904,0.246183,0.016140,0.671055,0.302887,0.343597,0.322601
288,Urumuchi,650100,2006,0.100333,0.097620,0.999906,0.098976,0.314590,0.089127,0.512516,...,0.137691,0.103063,0.989602,0.120377,0.345146,0.094128,0.686991,0.651100,0.390560,0.504275
289,Kelamayi,650200,2006,0.121824,0.102816,0.996414,0.112320,0.334540,0.094377,0.622335,...,0.156935,0.072887,0.930728,0.114911,0.327034,0.063062,0.783035,0.525271,0.423048,0.471397

# 计算Tapio脱钩模型

In [70]:
# 计算增长率
df_merged2['Delta_UER'] = (df_merged2['UER_2010'] - df_merged2['UER_2006']) / df_merged2['UER_2006']
df_merged2['Delta_UI'] = (df_merged2['UI_2010'] - df_merged2['UI_2006']) / df_merged2['UI_2006']

# 计算脱钩指数DI
df_merged2['DI'] = df_merged2['Delta_UER'] / df_merged2['Delta_UI']

In [71]:
df_merged2

,Name_of_Regions_x_2006,Citycode,Year_x,UER_2006,UI_2006,C_2006,T_2006,D_2006,UI_normalized_2006,UER_normalized_2006,...,T_2010,D_2010,UI_normalized_2010,UER_normalized_2010,C2_2010,T2_2010,D2_2010,Delta_UER,Delta_UI,DI
0,Beijing,110000,2006,0.137433,0.210078,0.977907,0.173756,0.412210,0.202760,0.702098,...,0.187503,0.431877,0.200826,0.839766,0.789294,0.520296,0.640833,0.224613,-0.016062,-13.983872
1,Tianjin,120000,2006,0.103581,0.168235,0.971300,0.135908,0.363328,0.160479,0.529117,...,0.174729,0.416281,0.190941,0.760175,0.801130,0.475558,0.617239,0.470873,0.171589,2.744191
2,Shijiazhuang,130100,2006,0.135975,0.075086,0.957483,0.105530,0.317873,0.066357,0.694645,...,0.126829,0.343059,0.069926,0.868715,0.525158,0.469321,0.496455,0.280409,0.059519,4.711286
3,Tangshan,130200,2006,0.137393,0.076543,0.958697,0.106968,0.320234,0.067829,0.701890,...,0.124553,0.338683,0.066281,0.863673,0.514562,0.464977,0.489142,0.259842,-0.006908,-37.613687
4,Qinhuangdao,130300,2006,0.140799,0.069600,0.941002,0.105200,0.314632,0.060814,0.719298,...,0.124207,0.330275,0.054742,0.916151,0.461319,0.485446,0.473229,0.304040,-0.068890,-4.413412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,Guyuan,640400,2006,0.129806,0.020694,0.688750,0.075250,0.227659,0.011397,0.663123,...,0.083213,0.224820,0.005639,0.745015,0.172687,0.375327,0.254586,0.150312,-0.173223,-0.867736
286,Zhongwei,640500,2006,0.126115,0.030682,0.793445,0.078398,0.249409,0.021489,0.644263,...,0.059263,0.217388,0.012220,0.474050,0.313042,0.243135,0.275883,-0.246529,-0.234007,1.053514
287,Xinjiang,650000,2006,0.087788,0.075510,0.997170,0.081649,0.285338,0.066786,0.448413,...,0.080904,0.246183,0.016140,0.671055,0.302887,0.343597,0.322601,0.532082,-0.638332,-0.833551
288,Urumuchi,650100,2006,0.100333,0.097620,0.999906,0.098976,0.314590,0.089127,0.512516,...,0.120377,0.345146,0.094128,0.686991,0.651100,0.390560,0.504275,0.372347,0.055761,6.677574
289,Kelamayi,650200,2006,0.121824,0.102816,0.996414,0.112320,0.334540,0.094377,0.622335,...,0.114911,0.327034,0.063062,0.783035,0.525271,0.423048,0.471397,0.288216,-0.291095,-0.990109

In [72]:
def classify_decoupling(row):
    Delta_ER = row['Delta_UER']
    Delta_UI = row['Delta_UI']
    DI = row['DI']
    
    if Delta_ER < 0 and Delta_UI < 0 and 1.2 <= DI < float('inf'):
        return 'Recession decoupling / Decoupling'
    elif Delta_ER < 0 and Delta_UI > 0 and float('-inf') < DI <= 0:
        return 'Strong decoupling / Decoupling'
    elif Delta_ER > 0 and Delta_UI > 0 and 0 <= DI <= 0.8:
        return 'Weak decoupling / Decoupling'
    elif Delta_ER > 0 and Delta_UI > 0 and 0.8 < DI <= 1.2:
        return 'Expansion connection / Connection'
    elif Delta_ER < 0 and Delta_UI < 0 and 0.8 < DI <= 1.2:
        return 'Recession connection / Connection'
    elif Delta_ER > 0 and Delta_UI > 0 and 1.2 <= DI < float('inf'):
        return 'Negative decoupling of expansion / Negative decoupling'
    elif Delta_ER > 0 and Delta_UI < 0 and float('-inf') < DI <= 0:
        return 'Strong negative decoupling / Negative decoupling'
    elif Delta_ER < 0 and Delta_UI < 0 and 0 <= DI <= 0.8:
        return 'Weak negative decoupling / Negative decoupling'
    else:
        return 'Unknown'

# Apply the function to the DataFrame
df_merged2['DI_Category'] = df_merged2.apply(classify_decoupling, axis=1)

In [73]:
df_merged2

,Name_of_Regions_x_2006,Citycode,Year_x,UER_2006,UI_2006,C_2006,T_2006,D_2006,UI_normalized_2006,UER_normalized_2006,...,D_2010,UI_normalized_2010,UER_normalized_2010,C2_2010,T2_2010,D2_2010,Delta_UER,Delta_UI,DI,DI_Category
0,Beijing,110000,2006,0.137433,0.210078,0.977907,0.173756,0.412210,0.202760,0.702098,...,0.431877,0.200826,0.839766,0.789294,0.520296,0.640833,0.224613,-0.016062,-13.983872,Strong negative decoupling / Negative decoupling
1,Tianjin,120000,2006,0.103581,0.168235,0.971300,0.135908,0.363328,0.160479,0.529117,...,0.416281,0.190941,0.760175,0.801130,0.475558,0.617239,0.470873,0.171589,2.744191,Negative decoupling of expansion / Negative de...
2,Shijiazhuang,130100,2006,0.135975,0.075086,0.957483,0.105530,0.317873,0.066357,0.694645,...,0.343059,0.069926,0.868715,0.525158,0.469321,0.496455,0.280409,0.059519,4.711286,Negative decoupling of expansion / Negative de...
3,Tangshan,130200,2006,0.137393,0.076543,0.958697,0.106968,0.320234,0.067829,0.701890,...,0.338683,0.066281,0.863673,0.514562,0.464977,0.489142,0.259842,-0.006908,-37.613687,Strong negative decoupling / Negative decoupling
4,Qinhuangdao,130300,2006,0.140799,0.069600,0.941002,0.105200,0.314632,0.060814,0.719298,...,0.330275,0.054742,0.916151,0.461319,0.485446,0.473229,0.304040,-0.068890,-4.413412,Strong negative decoupling / Negative decoupling
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,Guyuan,640400,2006,0.129806,0.020694,0.688750,0.075250,0.227659,0.011397,0.663123,...,0.224820,0.005639,0.745015,0.172687,0.375327,0.254586,0.150312,-0.173223,-0.867736,Strong negative decoupling / Negative decoupling
286,Zhongwei,640500,2006,0.126115,0.030682,0.793445,0.078398,0.249409,0.021489,0.644263,...,0.217388,0.012220,0.474050,0.313042,0.243135,0.275883,-0.246529,-0.234007,1.053514,Recession connection / Connection
287,Xinjiang,650000,2006,0.087788,0.075510,0.997170,0.081649,0.285338,0.066786,0.448413,...,0.246183,0.016140,0.671055,0.302887,0.343597,0.322601,0.532082,-0.638332,-0.833551,Strong negative decoupling / Negative decoupling
288,Urumuchi,650100,2006,0.100333,0.097620,0.999906,0.098976,0.314590,0.089127,0.512516,...,0.345146,0.094128,0.686991,0.651100,0.390560,0.504275,0.372347,0.055761,6.677574,Negative decoupling of expansion / Negative de...
289,Kelamayi,650200,2006,0.121824,0.102816,0.996414,0.112320,0.334540,0.094377,0.622335,...,0.327034,0.063062,0.783035,0.525271,0.423048,0.471397,0.288216,-0.291095,-0.990109,Strong negative decoupling / Negative decoupling

In [45]:
# 读取shapefile
shapefile_path = 'data/Chinamap_2019/Merged_Municipalities.shp'
gdf = gpd.read_file(shapefile_path)

In [46]:
gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 317 entries, 0 to 316
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Prvnc_c   317 non-null    float64
 1   City_cd   317 non-null    object
 2   Area      317 non-null    object
 3   Name      286 non-null    object
 4   geometry  317 non-null    geometry
dtypes: float64(1), geometry(1), object(3)
memory usage: 12.5+ KB

In [75]:
df_merged2['Citycode'] = df_merged2['Citycode'].astype(float)
gdf['City_cd'] = gdf['City_cd'].astype(float)

In [76]:

# 根据Citycode和市代码进行连接，保留不匹配的行
data_merged3 = gdf.merge(df_merged2, left_on='City_cd', right_on='Citycode', how='outer')

In [82]:
data_merged3

,Prvnc_c,City_cd,Area,Name,geometry,Name_of_Regions_x_2006,Citycode,Year_x,UER_2006,UI_2006,...,D_2010,UI_normalized_2010,UER_normalized_2010,C2_2010,T2_2010,D2_2010,Delta_UER,Delta_UI,DI,DI_Category
0,460000.0,460000.0,0,Hainan,"MULTIPOLYGON (((509245.473 1880004.210, 509230...",Hainan,460000.0,2006.0,0.126850,0.062596,...,0.279759,0.029700,0.754980,0.381667,0.392340,0.386967,0.192857,-0.353294,-0.545881,Strong negative decoupling / Negative decoupling
1,540000.0,540000.0,0,Tibet,"POLYGON ((-1051759.214 2954966.840, -1051995.7...",Tibet,540000.0,2006.0,0.057672,0.022349,...,0.207468,0.004016,0.595070,0.163205,0.299543,0.221104,1.068123,-0.304972,-3.502358,Strong negative decoupling / Negative decoupling
2,630000.0,630000.0,0,Qinghai,"POLYGON ((-228508.104 3789259.226, -228464.693...",Qinghai,630000.0,2006.0,0.122428,0.054317,...,0.238689,0.012656,0.676889,0.268455,0.344772,0.304230,0.108137,-0.559522,-0.193266,Strong negative decoupling / Negative decoupling
3,650000.0,650000.0,0,xinjiang,"POLYGON ((-1766120.224 3995392.661, -1766246.1...",Xinjiang,650000.0,2006.0,0.087788,0.075510,...,0.246183,0.016140,0.671055,0.302887,0.343597,0.322601,0.532082,-0.638332,-0.833551,Strong negative decoupling / Negative decoupling
4,110000.0,110000.0,16405,Beijing,"POLYGON ((964331.264 4474013.823, 964404.983 4...",Beijing,110000.0,2006.0,0.137433,0.210078,...,0.431877,0.200826,0.839766,0.789294,0.520296,0.640833,0.224613,-0.016062,-13.983872,Strong negative decoupling / Negative decoupling
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,640000.0,640400.0,10524,Guyuan,"MULTIPOLYGON (((93771.810 3789604.316, 93641.5...",Guyuan,640400.0,2006.0,0.129806,0.020694,...,0.224820,0.005639,0.745015,0.172687,0.375327,0.254586,0.150312,-0.173223,-0.867736,Strong negative decoupling / Negative decoupling
313,640000.0,640500.0,13659,Zhongwei,"POLYGON ((75753.800 4044387.044, 76030.401 404...",Zhongwei,640500.0,2006.0,0.126115,0.030682,...,0.217388,0.012220,0.474050,0.313042,0.243135,0.275883,-0.246529,-0.234007,1.053514,Recession connection / Connection
314,710000.0,710000.0,36200,NaN,"MULTIPOLYGON (((1725282.722 2422889.823, 17253...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,810000.0,810000.0,1115,NaN,"MULTIPOLYGON (((926766.217 2342789.464, 926841...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,820000.0,820000.0,34,NaN,"MULTIPOLYGON (((891332.431 2339835.922, 891974...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [81]:
# 查找 Name_of_Regions_x_2010 有值但是 Name 列无值的行
rows_with_value_in_Regions_but_not_in_Name = data_merged3[(data_merged3['Name_of_Regions_x_2010'].notna()) & (data_merged3['Name'].isna())]

# 输出符合条件的行
print(rows_with_value_in_Regions_but_not_in_Name)

Empty GeoDataFrame
Columns: [Prvnc_c, City_cd, Area, Name, geometry, Name_of_Regions_x_2006, Citycode, Year_x, UER_2006, UI_2006, C_2006, T_2006, D_2006, UI_normalized_2006, UER_normalized_2006, C2_2006, T2_2006, D2_2006, Name_of_Regions_x_2010, Year, UER_2010, UI_2010, C_2010, T_2010, D_2010, UI_normalized_2010, UER_normalized_2010, C2_2010, T2_2010, D2_2010, Delta_UER, Delta_UI, DI, DI_Category]
Index: []

[0 rows x 34 columns]

In [79]:
# 删除 geometry 列为空值的行
data_merged3 = data_merged3.dropna(subset=['geometry'])

In [80]:
# 查找 geometry 列为空值的行
rows_with_nan_in_geometry = data_merged3[data_merged3['geometry'].isna()]

# 输出包含 geometry 列为空值的行
print(rows_with_nan_in_geometry)

Empty GeoDataFrame
Columns: [Prvnc_c, City_cd, Area, Name, geometry, Name_of_Regions_x_2006, Citycode, Year_x, UER_2006, UI_2006, C_2006, T_2006, D_2006, UI_normalized_2006, UER_normalized_2006, C2_2006, T2_2006, D2_2006, Name_of_Regions_x_2010, Year, UER_2010, UI_2010, C_2010, T_2010, D_2010, UI_normalized_2010, UER_normalized_2010, C2_2010, T2_2010, D2_2010, Delta_UER, Delta_UI, DI, DI_Category]
Index: []

[0 rows x 34 columns]

In [83]:
# 修改列名称“省代码”为“province”
data_merged3 = data_merged3.rename(columns={'省代码': 'Provincecode'})
# 修改列名称“省代码”为“province”
data_merged3 = data_merged3.rename(columns={'省': 'Province'})
# 修改列名称“省代码”为“province”
data_merged3 = data_merged3.rename(columns={'市代码': 'Citycode1'})
data_merged3 = data_merged3.rename(columns={'市': 'City'})
data_merged3 = data_merged3.rename(columns={'类型': 'Type'})

In [84]:
# 将data_merged导出为新的shapefile
output_shapefile_path = 'data/Chinamap_2019/CouplingValue_20062010.shp'
data_merged3.to_file(output_shapefile_path, driver='ESRI Shapefile')

/tmp/ipykernel_31992/3462740497.py:3: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  data_merged3.to_file(output_shapefile_path, driver='ESRI Shapefile')