In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt

In [2]:
file_path = 'data/2014_UI_UER.xlsx'
df = pd.read_excel(file_path)

In [3]:
df

,Name_of_Regions,Unnamed: 1,Year,Unnamed: 3,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,Road_Surface_Area_Per_Capita_m2,Unnamed: 8,Unnamed: 9,...,Industrial_wastewater_discharge_(tonnes),Industrial_fume_emissions_(tonnes),城市,Comprehensive_industrial_solid_waste_utilisation_rate(%),Unnamed: 24,Rate_of_non_hazardous_treatment_of_domestic_waste(%),CITY,Greening_coverage_in_builtup_areas,Unnamed: 28,Parkland_per_capita
0,北京,Beijing,NaN,北京,1859.00,NaN,1385.58,7.44,北京市,北京市,...,9174.0,22710.0,北京市,87.670,86.10,99.59,北京市,60.41,北京市,15.94
1,天津,Tianjin,NaN,天津,642.91,143.58,797.10,16.71,天津市,天津市,...,19011.0,112129.0,天津市,98.910,100.00,96.23,天津市,41.82,天津市,9.73
2,河北,Hebei,NaN,河北,1521.44,107.26,1833.17,18.49,河北省,NaN,...,106550.0,1440208.0,河北省,NaN,NaN,NaN,NaN,NaN,NaN,14.45
3,石家庄,Shijiazhuang,NaN,石家庄,262.46,19.31,264.01,18.57,石家庄市,石家庄市,...,24024.0,104277.0,石家庄市,95.100,95.85,71.98,石家庄市,48.98,石家庄市,15.33
4,唐山,Tangshan,NaN,唐山,193.49,4.00,249.00,15.67,唐山市,唐山市,...,13973.0,536092.0,唐山市,70.000,95.00,100.00,唐山市,41.17,唐山市,15.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,固原,Guyuan,NaN,固原,20.68,8.68,44.10,26.65,固原市,固原市,...,249.0,2765.0,固原市,93.700,79.00,92.82,固原市,27.45,固原市,7.99
315,中卫,Zhongwei,NaN,中卫,18.86,0.86,38.68,27.49,中卫市,NaN,...,2806.0,60109.0,中卫市,92.740,96.70,96.90,中卫市,36.82,中卫市,20.08
316,新疆,xinjiang,NaN,新疆,598.58,125.51,1118.40,16.46,新疆维吾尔自治区,NaN,...,6698.0,81581.0,新疆维吾尔自治区,55.632,NaN,81.90,NaN,36.80,NaN,10.74
317,乌鲁木齐,Urumuchi,NaN,乌鲁木齐,260.50,47.31,412.26,10.08,乌鲁木齐市,乌鲁木齐市,...,4849.0,77076.0,乌鲁木齐市,93.660,81.98,92.42,乌鲁木齐市,38.52,乌鲁木齐市,10.66
318,克拉玛依,Kelamayi,NaN,克拉玛依,28.08,8.39,69.38,28.72,克拉玛依市,NaN,...,1849.0,4505.0,克拉玛依市,98.610,95.10,98.98,克拉玛依市,43.28,克拉玛依市,11.48

In [4]:
# 去除指定列中包含NaN值的行
columns_to_check = [ 
    'Population_urbanization', 
    'First_sector_of_GDP', 
    'GDP', 
    'Citycode', 
    'Area_of_administrative_districts'
]
df_cleaned = df.dropna(subset=columns_to_check)

In [5]:
df_cleaned

,Name_of_Regions,Unnamed: 1,Year,Unnamed: 3,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,Road_Surface_Area_Per_Capita_m2,Unnamed: 8,Unnamed: 9,...,Industrial_wastewater_discharge_(tonnes),Industrial_fume_emissions_(tonnes),城市,Comprehensive_industrial_solid_waste_utilisation_rate(%),Unnamed: 24,Rate_of_non_hazardous_treatment_of_domestic_waste(%),CITY,Greening_coverage_in_builtup_areas,Unnamed: 28,Parkland_per_capita
0,北京,Beijing,NaN,北京,1859.00,NaN,1385.58,7.44,北京市,北京市,...,9174.0,22710.0,北京市,87.670,86.10,99.59,北京市,60.41,北京市,15.94
1,天津,Tianjin,NaN,天津,642.91,143.58,797.10,16.71,天津市,天津市,...,19011.0,112129.0,天津市,98.910,100.00,96.23,天津市,41.82,天津市,9.73
3,石家庄,Shijiazhuang,NaN,石家庄,262.46,19.31,264.01,18.57,石家庄市,石家庄市,...,24024.0,104277.0,石家庄市,95.100,95.85,71.98,石家庄市,48.98,石家庄市,15.33
4,唐山,Tangshan,NaN,唐山,193.49,4.00,249.00,15.67,唐山市,唐山市,...,13973.0,536092.0,唐山市,70.000,95.00,100.00,唐山市,41.17,唐山市,15.08
5,秦皇岛,Qinhuangdao,NaN,秦皇岛,89.56,9.30,102.85,19.77,秦皇岛市,秦皇岛市,...,6273.0,59221.0,秦皇岛市,65.000,98.38,157.94,秦皇岛市,92.87,秦皇岛市,20.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,固原,Guyuan,NaN,固原,20.68,8.68,44.10,26.65,固原市,固原市,...,249.0,2765.0,固原市,93.700,79.00,92.82,固原市,27.45,固原市,7.99
315,中卫,Zhongwei,NaN,中卫,18.86,0.86,38.68,27.49,中卫市,NaN,...,2806.0,60109.0,中卫市,92.740,96.70,96.90,中卫市,36.82,中卫市,20.08
316,新疆,xinjiang,NaN,新疆,598.58,125.51,1118.40,16.46,新疆维吾尔自治区,NaN,...,6698.0,81581.0,新疆维吾尔自治区,55.632,NaN,81.90,NaN,36.80,NaN,10.74
317,乌鲁木齐,Urumuchi,NaN,乌鲁木齐,260.50,47.31,412.26,10.08,乌鲁木齐市,乌鲁木齐市,...,4849.0,77076.0,乌鲁木齐市,93.660,81.98,92.42,乌鲁木齐市,38.52,乌鲁木齐市,10.66
318,克拉玛依,Kelamayi,NaN,克拉玛依,28.08,8.39,69.38,28.72,克拉玛依市,NaN,...,1849.0,4505.0,克拉玛依市,98.610,95.10,98.98,克拉玛依市,43.28,克拉玛依市,11.48

In [6]:
# 指定需要检查NaN值的列
columns_to_check = [
    'UrbanPopulation',
    'UrbanTemporaryPopulation', 
    'Population_urbanization', 
    'First_sector_of_GDP', 
    'GDP', 
    'Citycode', 
    'Area_of_administrative_districts',
    'Road_Surface_Area_Per_Capita_m2',
    'Surface_Area_of_Built_District'
]

# 将这些列转换为数值类型，处理非数值内容
for column in columns_to_check:
    df_cleaned[column] = pd.to_numeric(df_cleaned[column], errors='coerce')

/tmp/ipykernel_4763/1195776530.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = pd.to_numeric(df_cleaned[column], errors='coerce')

In [7]:
df_cleaned['UrbanTemporaryPopulation'] = df_cleaned['UrbanTemporaryPopulation'].fillna(0)

/tmp/ipykernel_4763/1004577029.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['UrbanTemporaryPopulation'] = df_cleaned['UrbanTemporaryPopulation'].fillna(0)

In [8]:
df_cleaned['PUI'] = (df_cleaned['Population_urbanization'])

/tmp/ipykernel_4763/629985429.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['PUI'] = (df_cleaned['Population_urbanization'])

In [9]:
df_cleaned

,Name_of_Regions,Unnamed: 1,Year,Unnamed: 3,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,Road_Surface_Area_Per_Capita_m2,Unnamed: 8,Unnamed: 9,...,Industrial_fume_emissions_(tonnes),城市,Comprehensive_industrial_solid_waste_utilisation_rate(%),Unnamed: 24,Rate_of_non_hazardous_treatment_of_domestic_waste(%),CITY,Greening_coverage_in_builtup_areas,Unnamed: 28,Parkland_per_capita,PUI
0,北京,Beijing,NaN,北京,1859.00,0.00,1385.58,7.44,北京市,北京市,...,22710.0,北京市,87.670,86.10,99.59,北京市,60.41,北京市,15.94,0.8640
1,天津,Tianjin,NaN,天津,642.91,143.58,797.10,16.71,天津市,天津市,...,112129.0,天津市,98.910,100.00,96.23,天津市,41.82,天津市,9.73,0.8227
3,石家庄,Shijiazhuang,NaN,石家庄,262.46,19.31,264.01,18.57,石家庄市,石家庄市,...,104277.0,石家庄市,95.100,95.85,71.98,石家庄市,48.98,石家庄市,15.33,0.4759
4,唐山,Tangshan,NaN,唐山,193.49,4.00,249.00,15.67,唐山市,唐山市,...,536092.0,唐山市,70.000,95.00,100.00,唐山市,41.17,唐山市,15.08,0.5621
5,秦皇岛,Qinhuangdao,NaN,秦皇岛,89.56,9.30,102.85,19.77,秦皇岛市,秦皇岛市,...,59221.0,秦皇岛市,65.000,98.38,157.94,秦皇岛市,92.87,秦皇岛市,20.41,0.4359
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,固原,Guyuan,NaN,固原,20.68,8.68,44.10,26.65,固原市,固原市,...,2765.0,固原市,93.700,79.00,92.82,固原市,27.45,固原市,7.99,0.3009
315,中卫,Zhongwei,NaN,中卫,18.86,0.86,38.68,27.49,中卫市,NaN,...,60109.0,中卫市,92.740,96.70,96.90,中卫市,36.82,中卫市,20.08,0.3719
316,新疆,xinjiang,NaN,新疆,598.58,125.51,1118.40,16.46,新疆维吾尔自治区,NaN,...,81581.0,新疆维吾尔自治区,55.632,NaN,81.90,NaN,36.80,NaN,10.74,0.4218
317,乌鲁木齐,Urumuchi,NaN,乌鲁木齐,260.50,47.31,412.26,10.08,乌鲁木齐市,乌鲁木齐市,...,77076.0,乌鲁木齐市,93.660,81.98,92.42,乌鲁木齐市,38.52,乌鲁木齐市,10.66,0.9712
318,克拉玛依,Kelamayi,NaN,克拉玛依,28.08,8.39,69.38,28.72,克拉玛依市,NaN,...,4505.0,克拉玛依市,98.610,95.10,98.98,克拉玛依市,43.28,克拉玛依市,11.48,0.6482

In [10]:
df_cleaned['PUI'].describe()

count    291.000000
mean       0.530229
std        0.154627
min        0.073000
25%        0.427550
50%        0.503600
75%        0.632500
max        1.000000
Name: PUI, dtype: float64

In [11]:
# 查找 PUI 列中为空值的行
rows_with_nan_in_pui = df_cleaned[df_cleaned['PUI'].isna()]

# 输出包含 PUI 列为空值的行
print(rows_with_nan_in_pui)

Empty DataFrame
Columns: [Name_of_Regions, Unnamed: 1, Year, Unnamed: 3, UrbanPopulation, UrbanTemporaryPopulation, Surface_Area_of_Built_District, Road_Surface_Area_Per_Capita_m2, Unnamed: 8, Unnamed: 9, Population_urbanization, Unnamed: 11, GDP, Unnamed: 13, First_sector_of_GDP, Unnamed: 15, Unnamed: 16, Citycode, Area_of_administrative_districts, Unnamed: 19, Industrial_wastewater_discharge_(tonnes), Industrial_fume_emissions_(tonnes), 城市, Comprehensive_industrial_solid_waste_utilisation_rate(%), Unnamed: 24, Rate_of_non_hazardous_treatment_of_domestic_waste(%), CITY, Greening_coverage_in_builtup_areas, Unnamed: 28, Parkland_per_capita, PUI]
Index: []

[0 rows x 31 columns]

In [12]:
df_cleaned['URI'] = (df_cleaned['Road_Surface_Area_Per_Capita_m2'] * ((df_cleaned['UrbanPopulation'] + df_cleaned['UrbanTemporaryPopulation'])* 10000) /1000000 ) / df_cleaned['Area_of_administrative_districts']

/tmp/ipykernel_4763/2660692400.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['URI'] = (df_cleaned['Road_Surface_Area_Per_Capita_m2'] * ((df_cleaned['UrbanPopulation'] + df_cleaned['UrbanTemporaryPopulation'])* 10000) /1000000 ) / df_cleaned['Area_of_administrative_districts']

In [13]:
df_cleaned['URI'].describe()

count    291.000000
mean       0.002509
std        0.005777
min        0.000004
25%        0.000381
50%        0.000963
75%        0.002608
max        0.059858
Name: URI, dtype: float64

In [14]:
df_cleaned['LUI'] = (df_cleaned['Surface_Area_of_Built_District']) / df_cleaned['Area_of_administrative_districts']

/tmp/ipykernel_4763/3353621859.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['LUI'] = (df_cleaned['Surface_Area_of_Built_District']) / df_cleaned['Area_of_administrative_districts']

In [15]:
df_cleaned['LUI'].describe()

count    291.000000
mean       0.017735
std        0.040089
min        0.000105
25%        0.003220
50%        0.007410
75%        0.018730
max        0.458075
Name: LUI, dtype: float64

In [16]:
df_cleaned['EUI'] = 1 - (df_cleaned['First_sector_of_GDP']) / 100

/tmp/ipykernel_4763/1051056126.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['EUI'] = 1 - (df_cleaned['First_sector_of_GDP']) / 100

In [17]:
df_cleaned['EUI'].describe()

count    291.000000
mean       0.877521
std        0.078881
min        0.519400
25%        0.832150
50%        0.884100
75%        0.937900
max        0.999700
Name: EUI, dtype: float64

In [18]:
df_cleaned['EAL'] = df_cleaned['GDP'] / df_cleaned['Area_of_administrative_districts']

/tmp/ipykernel_4763/3615482750.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['EAL'] = df_cleaned['GDP'] / df_cleaned['Area_of_administrative_districts']

In [19]:
df_cleaned['EAL'].describe()

count      291.000000
mean      2836.182246
std       6097.331513
min          2.890399
25%        585.870975
50%       1300.808807
75%       2810.113903
max      82356.256819
Name: EAL, dtype: float64

In [20]:
df_cleaned

,Name_of_Regions,Unnamed: 1,Year,Unnamed: 3,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,Road_Surface_Area_Per_Capita_m2,Unnamed: 8,Unnamed: 9,...,Rate_of_non_hazardous_treatment_of_domestic_waste(%),CITY,Greening_coverage_in_builtup_areas,Unnamed: 28,Parkland_per_capita,PUI,URI,LUI,EUI,EAL
0,北京,Beijing,NaN,北京,1859.00,0.00,1385.58,7.44,北京市,北京市,...,99.59,北京市,60.41,北京市,15.94,0.8640,0.008431,0.084461,0.9925,13002.639439
1,天津,Tianjin,NaN,天津,642.91,143.58,797.10,16.71,天津市,天津市,...,96.23,天津市,41.82,天津市,9.73,0.8227,0.011022,0.066848,0.9872,13189.307279
3,石家庄,Shijiazhuang,NaN,石家庄,262.46,19.31,264.01,18.57,石家庄市,石家庄市,...,71.98,石家庄市,48.98,石家庄市,15.33,0.4759,0.003722,0.018780,0.9057,3677.810001
4,唐山,Tangshan,NaN,唐山,193.49,4.00,249.00,15.67,唐山市,唐山市,...,100.00,唐山市,41.17,唐山市,15.08,0.5621,0.002241,0.018033,0.9103,4508.475014
5,秦皇岛,Qinhuangdao,NaN,秦皇岛,89.56,9.30,102.85,19.77,秦皇岛市,秦皇岛市,...,157.94,秦皇岛市,92.87,秦皇岛市,20.41,0.4359,0.002508,0.013199,0.8545,1540.069174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,固原,Guyuan,NaN,固原,20.68,8.68,44.10,26.65,固原市,固原市,...,92.82,固原市,27.45,固原市,7.99,0.3009,0.000743,0.004190,0.7820,191.019479
315,中卫,Zhongwei,NaN,中卫,18.86,0.86,38.68,27.49,中卫市,NaN,...,96.90,中卫市,36.82,中卫市,20.08,0.3719,0.000397,0.002832,0.8460,217.856651
316,新疆,xinjiang,NaN,新疆,598.58,125.51,1118.40,16.46,新疆维吾尔自治区,NaN,...,81.90,NaN,36.80,NaN,10.74,0.4218,0.000073,0.000686,0.9902,20.294191
317,乌鲁木齐,Urumuchi,NaN,乌鲁木齐,260.50,47.31,412.26,10.08,乌鲁木齐市,乌鲁木齐市,...,92.42,乌鲁木齐市,38.52,乌鲁木齐市,10.66,0.9712,0.002249,0.029889,0.9889,1784.578989
318,克拉玛依,Kelamayi,NaN,克拉玛依,28.08,8.39,69.38,28.72,克拉玛依市,NaN,...,98.98,克拉玛依市,43.28,克拉玛依市,11.48,0.6482,0.001420,0.009409,0.9939,1149.542311

In [21]:
# 导入 land_use_intensity_by_city2006.csv 数据
df_land_use = pd.read_csv("data/land_use_intensity_by_city2014.csv", encoding='ISO-8859-1')
df_land_useProvince = pd.read_csv("data/land_use_intensity_by_province2014.csv", encoding='ISO-8859-1')
df_combined = pd.concat([df_land_use, df_land_useProvince], ignore_index=True)

In [22]:
df_combined

     Citycode  Provincecode        Province            City         LUL
0    110000.0      110000.0          ±±¾©ÊÐ          ±±¾©ÊÐ  267.559962
1    120000.0      120000.0          Ìì½òÊÐ          Ìì½òÊÐ  306.430451
2    130100.0      130000.0          ºÓ±±Ê¡        Ê¯¼Ò×¯ÊÐ  288.052816
3    130200.0      130000.0          ºÓ±±Ê¡          ÌÆÉ½ÊÐ  298.554656
4    130300.0      130000.0          ºÓ±±Ê¡        ÇØ»ÊµºÊÐ  265.773350
..        ...           ...             ...             ...         ...
369  820000.0      820000.0  °ÄÃÅÌØ±ðÐÐÕþÇø  °ÄÃÅÌØ±ðÐÐÕþÇø  201.983475
370  460000.0           NaN          hainan             NaN  231.306077
371  630000.0           NaN         qinghai             NaN  140.893852
372  650000.0           NaN        xinjiang             NaN   66.578463
373  540000.0           NaN          xizang             NaN  168.106935

[374 rows x 5 columns]

In [23]:
df_merged = df_cleaned.merge(df_combined[['Citycode', 'LUL']], on='Citycode', how='left')

In [24]:
df_merged

,Name_of_Regions,Unnamed: 1,Year,Unnamed: 3,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,Road_Surface_Area_Per_Capita_m2,Unnamed: 8,Unnamed: 9,...,CITY,Greening_coverage_in_builtup_areas,Unnamed: 28,Parkland_per_capita,PUI,URI,LUI,EUI,EAL,LUL
0,北京,Beijing,NaN,北京,1859.00,0.00,1385.58,7.44,北京市,北京市,...,北京市,60.41,北京市,15.94,0.8640,0.008431,0.084461,0.9925,13002.639439,267.559962
1,天津,Tianjin,NaN,天津,642.91,143.58,797.10,16.71,天津市,天津市,...,天津市,41.82,天津市,9.73,0.8227,0.011022,0.066848,0.9872,13189.307279,306.430451
2,石家庄,Shijiazhuang,NaN,石家庄,262.46,19.31,264.01,18.57,石家庄市,石家庄市,...,石家庄市,48.98,石家庄市,15.33,0.4759,0.003722,0.018780,0.9057,3677.810001,288.052816
3,唐山,Tangshan,NaN,唐山,193.49,4.00,249.00,15.67,唐山市,唐山市,...,唐山市,41.17,唐山市,15.08,0.5621,0.002241,0.018033,0.9103,4508.475014,298.554656
4,秦皇岛,Qinhuangdao,NaN,秦皇岛,89.56,9.30,102.85,19.77,秦皇岛市,秦皇岛市,...,秦皇岛市,92.87,秦皇岛市,20.41,0.4359,0.002508,0.013199,0.8545,1540.069174,265.773350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,固原,Guyuan,NaN,固原,20.68,8.68,44.10,26.65,固原市,固原市,...,固原市,27.45,固原市,7.99,0.3009,0.000743,0.004190,0.7820,191.019479,237.388911
287,中卫,Zhongwei,NaN,中卫,18.86,0.86,38.68,27.49,中卫市,NaN,...,中卫市,36.82,中卫市,20.08,0.3719,0.000397,0.002832,0.8460,217.856651,208.074665
288,新疆,xinjiang,NaN,新疆,598.58,125.51,1118.40,16.46,新疆维吾尔自治区,NaN,...,NaN,36.80,NaN,10.74,0.4218,0.000073,0.000686,0.9902,20.294191,66.578463
289,乌鲁木齐,Urumuchi,NaN,乌鲁木齐,260.50,47.31,412.26,10.08,乌鲁木齐市,乌鲁木齐市,...,乌鲁木齐市,38.52,乌鲁木齐市,10.66,0.9712,0.002249,0.029889,0.9889,1784.578989,135.964895
290,克拉玛依,Kelamayi,NaN,克拉玛依,28.08,8.39,69.38,28.72,克拉玛依市,NaN,...,克拉玛依市,43.28,克拉玛依市,11.48,0.6482,0.001420,0.009409,0.9939,1149.542311,68.179318

In [25]:
df_merged['LUL'].describe()

count    291.000000
mean     252.642906
std       45.251916
min       31.398128
25%      227.437408
50%      249.139263
75%      287.789421
max      324.307626
Name: LUL, dtype: float64

In [26]:
# 指定需要检查 NaN 值的列
columns_to_check = ['URI', 'LUI', 'EUI', 'EAL', 'LUL']

# 查找这些列中包含 NaN 值的行
rows_with_nan = df_merged[df_merged[columns_to_check].isna().any(axis=1)]

# 输出包含 NaN 值的行
print(rows_with_nan)

Empty DataFrame
Columns: [Name_of_Regions, Unnamed: 1, Year, Unnamed: 3, UrbanPopulation, UrbanTemporaryPopulation, Surface_Area_of_Built_District, Road_Surface_Area_Per_Capita_m2, Unnamed: 8, Unnamed: 9, Population_urbanization, Unnamed: 11, GDP, Unnamed: 13, First_sector_of_GDP, Unnamed: 15, Unnamed: 16, Citycode, Area_of_administrative_districts, Unnamed: 19, Industrial_wastewater_discharge_(tonnes), Industrial_fume_emissions_(tonnes), 城市, Comprehensive_industrial_solid_waste_utilisation_rate(%), Unnamed: 24, Rate_of_non_hazardous_treatment_of_domestic_waste(%), CITY, Greening_coverage_in_builtup_areas, Unnamed: 28, Parkland_per_capita, PUI, URI, LUI, EUI, EAL, LUL]
Index: []

[0 rows x 36 columns]

In [27]:
# 指定需要检查NaN值的列
columns_to_check1 = ['URI', 'LUI', 'EUI', 'EAL','LUL']

# 去除这些列中包含NaN值的行
data_merged = df_merged.dropna(subset=columns_to_check1)

In [47]:
data_merged

,Name_of_Regions,Unnamed: 1,Year,Unnamed: 3,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,Road_Surface_Area_Per_Capita_m2,Unnamed: 8,Unnamed: 9,...,CITY,Greening_coverage_in_builtup_areas,Unnamed: 28,Parkland_per_capita,PUI,URI,LUI,EUI,EAL,LUL
0,北京,Beijing,2014,北京,1859.00,0.00,1385.58,7.44,北京市,北京市,...,北京市,60.41,北京市,15.94,0.8640,0.008431,0.084461,0.9925,13002.639439,267.559962
1,天津,Tianjin,2014,天津,642.91,143.58,797.10,16.71,天津市,天津市,...,天津市,41.82,天津市,9.73,0.8227,0.011022,0.066848,0.9872,13189.307279,306.430451
2,石家庄,Shijiazhuang,2014,石家庄,262.46,19.31,264.01,18.57,石家庄市,石家庄市,...,石家庄市,48.98,石家庄市,15.33,0.4759,0.003722,0.018780,0.9057,3677.810001,288.052816
3,唐山,Tangshan,2014,唐山,193.49,4.00,249.00,15.67,唐山市,唐山市,...,唐山市,41.17,唐山市,15.08,0.5621,0.002241,0.018033,0.9103,4508.475014,298.554656
4,秦皇岛,Qinhuangdao,2014,秦皇岛,89.56,9.30,102.85,19.77,秦皇岛市,秦皇岛市,...,秦皇岛市,92.87,秦皇岛市,20.41,0.4359,0.002508,0.013199,0.8545,1540.069174,265.773350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,固原,Guyuan,2014,固原,20.68,8.68,44.10,26.65,固原市,固原市,...,固原市,27.45,固原市,7.99,0.3009,0.000743,0.004190,0.7820,191.019479,237.388911
287,中卫,Zhongwei,2014,中卫,18.86,0.86,38.68,27.49,中卫市,NaN,...,中卫市,36.82,中卫市,20.08,0.3719,0.000397,0.002832,0.8460,217.856651,208.074665
288,新疆,xinjiang,2014,新疆,598.58,125.51,1118.40,16.46,新疆维吾尔自治区,NaN,...,NaN,36.80,NaN,10.74,0.4218,0.000073,0.000686,0.9902,20.294191,66.578463
289,乌鲁木齐,Urumuchi,2014,乌鲁木齐,260.50,47.31,412.26,10.08,乌鲁木齐市,乌鲁木齐市,...,乌鲁木齐市,38.52,乌鲁木齐市,10.66,0.9712,0.002249,0.029889,0.9889,1784.578989,135.964895
290,克拉玛依,Kelamayi,2014,克拉玛依,28.08,8.39,69.38,28.72,克拉玛依市,NaN,...,克拉玛依市,43.28,克拉玛依市,11.48,0.6482,0.001420,0.009409,0.9939,1149.542311,68.179318

In [48]:
# 保留所需的列
columns_to_keep = ['Name_of_Regions', 'Year', 'Citycode', 'PUI', 'URI', 'LUI', 'EUI', 'EAL', 'LUL']
ui_index_2014 = data_merged[columns_to_keep]

# 导出为 CSV 文件
ui_index_2014.to_csv('data/UI_index_2014.csv', index=False)

In [30]:
# 将指定列的NaN值转换为0
columns_to_fill = [
    'Industrial_wastewater_discharge_(tonnes)', 
    'Industrial_fume_emissions_(tonnes)', 
    'Comprehensive_industrial_solid_waste_utilisation_rate(%)', 
    'Rate_of_non_hazardous_treatment_of_domestic_waste(%)', 
    'Greening_coverage_in_builtup_areas', 
    'Parkland_per_capita'
]

df_cleaned[columns_to_fill] = df_cleaned[columns_to_fill].fillna(0)

/tmp/ipykernel_4763/1106163433.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[columns_to_fill] = df_cleaned[columns_to_fill].fillna(0)

In [31]:
df_cleaned

,Name_of_Regions,Unnamed: 1,Year,Unnamed: 3,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,Road_Surface_Area_Per_Capita_m2,Unnamed: 8,Unnamed: 9,...,Rate_of_non_hazardous_treatment_of_domestic_waste(%),CITY,Greening_coverage_in_builtup_areas,Unnamed: 28,Parkland_per_capita,PUI,URI,LUI,EUI,EAL
0,北京,Beijing,NaN,北京,1859.00,0.00,1385.58,7.44,北京市,北京市,...,99.59,北京市,60.41,北京市,15.94,0.8640,0.008431,0.084461,0.9925,13002.639439
1,天津,Tianjin,NaN,天津,642.91,143.58,797.10,16.71,天津市,天津市,...,96.23,天津市,41.82,天津市,9.73,0.8227,0.011022,0.066848,0.9872,13189.307279
3,石家庄,Shijiazhuang,NaN,石家庄,262.46,19.31,264.01,18.57,石家庄市,石家庄市,...,71.98,石家庄市,48.98,石家庄市,15.33,0.4759,0.003722,0.018780,0.9057,3677.810001
4,唐山,Tangshan,NaN,唐山,193.49,4.00,249.00,15.67,唐山市,唐山市,...,100.00,唐山市,41.17,唐山市,15.08,0.5621,0.002241,0.018033,0.9103,4508.475014
5,秦皇岛,Qinhuangdao,NaN,秦皇岛,89.56,9.30,102.85,19.77,秦皇岛市,秦皇岛市,...,157.94,秦皇岛市,92.87,秦皇岛市,20.41,0.4359,0.002508,0.013199,0.8545,1540.069174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,固原,Guyuan,NaN,固原,20.68,8.68,44.10,26.65,固原市,固原市,...,92.82,固原市,27.45,固原市,7.99,0.3009,0.000743,0.004190,0.7820,191.019479
315,中卫,Zhongwei,NaN,中卫,18.86,0.86,38.68,27.49,中卫市,NaN,...,96.90,中卫市,36.82,中卫市,20.08,0.3719,0.000397,0.002832,0.8460,217.856651
316,新疆,xinjiang,NaN,新疆,598.58,125.51,1118.40,16.46,新疆维吾尔自治区,NaN,...,81.90,NaN,36.80,NaN,10.74,0.4218,0.000073,0.000686,0.9902,20.294191
317,乌鲁木齐,Urumuchi,NaN,乌鲁木齐,260.50,47.31,412.26,10.08,乌鲁木齐市,乌鲁木齐市,...,92.42,乌鲁木齐市,38.52,乌鲁木齐市,10.66,0.9712,0.002249,0.029889,0.9889,1784.578989
318,克拉玛依,Kelamayi,NaN,克拉玛依,28.08,8.39,69.38,28.72,克拉玛依市,NaN,...,98.98,克拉玛依市,43.28,克拉玛依市,11.48,0.6482,0.001420,0.009409,0.9939,1149.542311

In [32]:
df_cleaned['Res1'] = df_cleaned['Industrial_wastewater_discharge_(tonnes)'] / df_cleaned['GDP']

/tmp/ipykernel_4763/2666823736.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Res1'] = df_cleaned['Industrial_wastewater_discharge_(tonnes)'] / df_cleaned['GDP']

In [33]:
df_cleaned['Res1'].describe()

count    291.000000
mean       0.000360
std        0.000272
min        0.000011
25%        0.000200
50%        0.000282
75%        0.000467
max        0.002619
Name: Res1, dtype: float64

In [34]:
df_cleaned['Res2'] = df_cleaned['Industrial_fume_emissions_(tonnes)'] / df_cleaned['GDP']

/tmp/ipykernel_4763/2575824147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Res2'] = df_cleaned['Industrial_fume_emissions_(tonnes)'] / df_cleaned['GDP']

In [35]:
df_cleaned['Res2'].describe()

count    291.000000
mean       0.002988
std        0.003444
min        0.000000
25%        0.000878
50%        0.001885
75%        0.003584
max        0.028356
Name: Res2, dtype: float64

In [36]:
df_cleaned['Ada1'] = df_cleaned['Comprehensive_industrial_solid_waste_utilisation_rate(%)'] 
df_cleaned['Ada1'].describe()

/tmp/ipykernel_4763/526319254.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Ada1'] = df_cleaned['Comprehensive_industrial_solid_waste_utilisation_rate(%)']

count    291.000000
mean      82.000247
std       22.117229
min        2.090000
25%       73.240000
50%       91.440000
75%       97.555000
max      100.000000
Name: Ada1, dtype: float64

In [37]:
# 查找 Ada1 列值大于 100 的行
rows_ada1_above_100 = df_cleaned[df_cleaned['Ada1'] > 100]
rows_ada1_above_100

Empty DataFrame
Columns: [Name_of_Regions, Unnamed: 1, Year, Unnamed: 3, UrbanPopulation, UrbanTemporaryPopulation, Surface_Area_of_Built_District, Road_Surface_Area_Per_Capita_m2, Unnamed: 8, Unnamed: 9, Population_urbanization, Unnamed: 11, GDP, Unnamed: 13, First_sector_of_GDP, Unnamed: 15, Unnamed: 16, Citycode, Area_of_administrative_districts, Unnamed: 19, Industrial_wastewater_discharge_(tonnes), Industrial_fume_emissions_(tonnes), 城市, Comprehensive_industrial_solid_waste_utilisation_rate(%), Unnamed: 24, Rate_of_non_hazardous_treatment_of_domestic_waste(%), CITY, Greening_coverage_in_builtup_areas, Unnamed: 28, Parkland_per_capita, PUI, URI, LUI, EUI, EAL, Res1, Res2, Ada1]
Index: []

[0 rows x 38 columns]

In [38]:
df_cleaned['Ada2'] = df_cleaned['Rate_of_non_hazardous_treatment_of_domestic_waste(%)'] 
df_cleaned['Ada2'].describe()

/tmp/ipykernel_4763/2482281589.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Ada2'] = df_cleaned['Rate_of_non_hazardous_treatment_of_domestic_waste(%)']

count    291.000000
mean      90.456186
std       18.351330
min        0.000000
25%       89.940000
50%       97.520000
75%      100.000000
max      157.940000
Name: Ada2, dtype: float64

In [39]:
rows_ada2_above_100 = df_cleaned[df_cleaned['Ada2'] > 100]
rows_ada2_above_100

,Name_of_Regions,Unnamed: 1,Year,Unnamed: 3,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,Road_Surface_Area_Per_Capita_m2,Unnamed: 8,Unnamed: 9,...,Parkland_per_capita,PUI,URI,LUI,EUI,EAL,Res1,Res2,Ada1,Ada2
5,秦皇岛,Qinhuangdao,NaN,秦皇岛,89.56,9.3,102.85,19.77,秦皇岛市,秦皇岛市,...,20.41,0.4359,0.002508,0.013199,0.8545,1540.069174,0.000523,0.004935,65.0,157.94

In [40]:
df_cleaned['Rec1'] = df_cleaned['Greening_coverage_in_builtup_areas'] 
df_cleaned['Rec2'] = df_cleaned['Parkland_per_capita']

/tmp/ipykernel_4763/1792138184.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Rec1'] = df_cleaned['Greening_coverage_in_builtup_areas']
/tmp/ipykernel_4763/1792138184.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Rec2'] = df_cleaned['Parkland_per_capita']

In [41]:
df_cleaned['Rec1'].describe()

count    291.000000
mean      39.551856
std        8.792786
min        1.020000
25%       36.810000
50%       40.410000
75%       43.010000
max       95.250000
Name: Rec1, dtype: float64

In [42]:
rows_rec1_above_100 = df_cleaned[df_cleaned['Rec1'] > 100]
rows_rec1_above_100

Empty DataFrame
Columns: [Name_of_Regions, Unnamed: 1, Year, Unnamed: 3, UrbanPopulation, UrbanTemporaryPopulation, Surface_Area_of_Built_District, Road_Surface_Area_Per_Capita_m2, Unnamed: 8, Unnamed: 9, Population_urbanization, Unnamed: 11, GDP, Unnamed: 13, First_sector_of_GDP, Unnamed: 15, Unnamed: 16, Citycode, Area_of_administrative_districts, Unnamed: 19, Industrial_wastewater_discharge_(tonnes), Industrial_fume_emissions_(tonnes), 城市, Comprehensive_industrial_solid_waste_utilisation_rate(%), Unnamed: 24, Rate_of_non_hazardous_treatment_of_domestic_waste(%), CITY, Greening_coverage_in_builtup_areas, Unnamed: 28, Parkland_per_capita, PUI, URI, LUI, EUI, EAL, Res1, Res2, Ada1, Ada2, Rec1, Rec2]
Index: []

[0 rows x 41 columns]

In [43]:
top_10_Rec1 = df_cleaned.nlargest(10, 'Rec1')
top_10_Rec1

,Name_of_Regions,Unnamed: 1,Year,Unnamed: 3,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,Road_Surface_Area_Per_Capita_m2,Unnamed: 8,Unnamed: 9,...,URI,LUI,EUI,EAL,Res1,Res2,Ada1,Ada2,Rec1,Rec2
35,乌兰察布,Wulanchabu,NaN,乌兰察布,27.50,6.60,60.00,25.94,乌兰察布市,乌兰察布市,...,0.000162,0.001102,0.8490,160.481559,0.000195,0.005805,71.52,91.17,95.25,34.81
5,秦皇岛,Qinhuangdao,NaN,秦皇岛,89.56,9.30,102.85,19.77,秦皇岛市,秦皇岛市,...,0.002508,0.013199,0.8545,1540.069174,0.000523,0.004935,65.00,157.94,92.87,20.41
0,北京,Beijing,NaN,北京,1859.00,0.00,1385.58,7.44,北京市,北京市,...,0.008431,0.084461,0.9925,13002.639439,0.000043,0.000106,87.67,99.59,60.41,15.94
156,滨州,Binzhou,NaN,滨州,67.32,7.31,113.90,20.71,滨州市,滨州市,...,0.001713,0.012625,0.9074,2523.504766,0.000686,0.004142,92.01,100.00,60.29,18.51
203,娄底,Loudi,NaN,娄底,42.50,5.50,47.15,9.27,娄底市,娄底市,...,0.000549,0.005815,0.8553,1493.411569,0.000456,0.002849,97.00,100.00,59.15,9.53
43,锦州,Jinzhou,NaN,锦州,88.20,8.10,77.10,11.58,锦州市,锦州市,...,0.001115,0.007712,0.8522,1364.408322,0.000246,0.003498,93.13,87.44,57.34,12.75
208,珠海,Zhuhai,NaN,珠海,79.00,100.15,123.64,28.47,珠海市,珠海市,...,0.032301,0.078303,0.9765,11825.287524,0.000264,0.000695,94.89,100.00,57.02,18.75
199,益阳,Yiyang,NaN,益阳,57.10,5.60,71.00,13.46,益阳市,益阳市,...,0.000685,0.005763,0.8151,1017.082299,0.000383,0.002529,84.98,91.00,55.80,16.22
223,潮州,Chaozhou,NaN,潮州,77.26,6.68,72.85,8.73,潮州市,潮州市,...,0.002354,0.023402,0.9285,2731.194346,0.000329,0.000531,99.80,80.70,53.71,10.55
130,景德镇,Jingdezhen,NaN,景德镇,48.68,1.16,78.68,16.21,景德镇市,景德镇市,...,0.001536,0.014955,0.9252,1403.181334,0.000928,0.002110,98.72,100.00,51.44,14.81

In [44]:
df_cleaned['Rec2'].describe()

count    291.000000
mean      13.417869
std        5.602025
min        2.270000
25%       10.535000
50%       12.530000
75%       14.985000
max       75.050000
Name: Rec2, dtype: float64

In [45]:
data_merged['Year'] = 2014

In [49]:
df_cleaned['Year'] = 2014

/tmp/ipykernel_4763/583664753.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Year'] = 2014

In [50]:
df_cleaned

,Name_of_Regions,Unnamed: 1,Year,Unnamed: 3,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,Road_Surface_Area_Per_Capita_m2,Unnamed: 8,Unnamed: 9,...,URI,LUI,EUI,EAL,Res1,Res2,Ada1,Ada2,Rec1,Rec2
0,北京,Beijing,2014,北京,1859.00,0.00,1385.58,7.44,北京市,北京市,...,0.008431,0.084461,0.9925,13002.639439,0.000043,0.000106,87.670,99.59,60.41,15.94
1,天津,Tianjin,2014,天津,642.91,143.58,797.10,16.71,天津市,天津市,...,0.011022,0.066848,0.9872,13189.307279,0.000121,0.000713,98.910,96.23,41.82,9.73
3,石家庄,Shijiazhuang,2014,石家庄,262.46,19.31,264.01,18.57,石家庄市,石家庄市,...,0.003722,0.018780,0.9057,3677.810001,0.000465,0.002017,95.100,71.98,48.98,15.33
4,唐山,Tangshan,2014,唐山,193.49,4.00,249.00,15.67,唐山市,唐山市,...,0.002241,0.018033,0.9103,4508.475014,0.000224,0.008612,70.000,100.00,41.17,15.08
5,秦皇岛,Qinhuangdao,2014,秦皇岛,89.56,9.30,102.85,19.77,秦皇岛市,秦皇岛市,...,0.002508,0.013199,0.8545,1540.069174,0.000523,0.004935,65.000,157.94,92.87,20.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,固原,Guyuan,2014,固原,20.68,8.68,44.10,26.65,固原市,固原市,...,0.000743,0.004190,0.7820,191.019479,0.000124,0.001375,93.700,92.82,27.45,7.99
315,中卫,Zhongwei,2014,中卫,18.86,0.86,38.68,27.49,中卫市,NaN,...,0.000397,0.002832,0.8460,217.856651,0.000943,0.020200,92.740,96.90,36.82,20.08
316,新疆,xinjiang,2014,新疆,598.58,125.51,1118.40,16.46,新疆维吾尔自治区,NaN,...,0.000073,0.000686,0.9902,20.294191,0.000202,0.002465,55.632,81.90,36.80,10.74
317,乌鲁木齐,Urumuchi,2014,乌鲁木齐,260.50,47.31,412.26,10.08,乌鲁木齐市,乌鲁木齐市,...,0.002249,0.029889,0.9889,1784.578989,0.000197,0.003131,93.660,92.42,38.52,10.66
318,克拉玛依,Kelamayi,2014,克拉玛依,28.08,8.39,69.38,28.72,克拉玛依市,NaN,...,0.001420,0.009409,0.9939,1149.542311,0.000218,0.000531,98.610,98.98,43.28,11.48

In [52]:
columns_to_keep = ['Name_of_Regions','Citycode','Year','Res1','Res2','Ada1','Ada2','Rec1','Rec2']
uer_index_2014 = df_cleaned[columns_to_keep]
# 导出为 CSV 文件
uer_index_2014.to_csv('data/UER_index_2014.csv', index=False)

# 熵权法
# 标准化

In [47]:
# Initialize a column for the normalized values
data_merged['X1_star'] = pd.Series(dtype='float')
column_to_normalize = 'PUI'
# Iterate over each year to perform the normalization
for year in range(2014, 2015):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X1_max = year_data[column_to_normalize].max()
    X1_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X1_star'] = (year_data[column_to_normalize] - X1_min) / (X1_max - X1_min)

# Initialize a column for the normalized values
data_merged['X2_star'] = pd.Series(dtype='float')
column_to_normalize = 'URI'
# Iterate over each year to perform the normalization
for year in range(2014, 2015):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X2_max = year_data[column_to_normalize].max()
    X2_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X2_star'] = (year_data[column_to_normalize] - X2_min) / (X2_max - X2_min)

data_merged['X3_star'] = pd.Series(dtype='float')
column_to_normalize = 'LUI'
# Iterate over each year to perform the normalization
for year in range(2014, 2015):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X3_max = year_data[column_to_normalize].max()
    X3_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X3_star'] = (year_data[column_to_normalize] - X3_min) / (X3_max - X3_min)

data_merged['X4_star'] = pd.Series(dtype='float')
column_to_normalize = 'EUI'
# Iterate over each year to perform the normalization
for year in range(2014, 2015):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X4_max = year_data[column_to_normalize].max()
    X4_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X4_star'] = (year_data[column_to_normalize] - X4_min) / (X4_max - X4_min)

data_merged['X5_star'] = pd.Series(dtype='float')
column_to_normalize = 'EAL'
# Iterate over each year to perform the normalization
for year in range(2014, 2015):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X5_max = year_data[column_to_normalize].max()
    X5_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X5_star'] = (year_data[column_to_normalize] - X5_min) / (X5_max - X5_min)


data_merged['X6_star'] = pd.Series(dtype='float')
column_to_normalize = 'LUL'
# Iterate over each year to perform the normalization
for year in range(2014, 2015):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X6_max = year_data[column_to_normalize].max()
    X6_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X6_star'] = (year_data[column_to_normalize] - X6_min) / (X6_max - X6_min)

In [48]:
data_merged

,Name_of_Regions,Unnamed: 1,Year,Unnamed: 3,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,Road_Surface_Area_Per_Capita_m2,Unnamed: 8,Unnamed: 9,...,LUI,EUI,EAL,LUL,X1_star,X2_star,X3_star,X4_star,X5_star,X6_star
0,北京,Beijing,2014,北京,1859.00,0.00,1385.58,7.44,北京市,北京市,...,0.084461,0.9925,13002.639439,267.559962,0.853290,0.140788,0.184195,0.985009,0.157853,0.806262
1,天津,Tianjin,2014,天津,642.91,143.58,797.10,16.71,天津市,天津市,...,0.066848,0.9872,13189.307279,306.430451,0.808738,0.184072,0.145737,0.973975,0.160120,0.938967
2,石家庄,Shijiazhuang,2014,石家庄,262.46,19.31,264.01,18.57,石家庄市,石家庄市,...,0.018780,0.9057,3677.810001,288.052816,0.434628,0.062115,0.040778,0.804289,0.044624,0.876225
3,唐山,Tangshan,2014,唐山,193.49,4.00,249.00,15.67,唐山市,唐山市,...,0.018033,0.9103,4508.475014,298.554656,0.527616,0.037374,0.039146,0.813866,0.054710,0.912079
4,秦皇岛,Qinhuangdao,2014,秦皇岛,89.56,9.30,102.85,19.77,秦皇岛市,秦皇岛市,...,0.013199,0.8545,1540.069174,265.773350,0.391478,0.041836,0.028592,0.697689,0.018666,0.800163
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,固原,Guyuan,2014,固原,20.68,8.68,44.10,26.65,固原市,固原市,...,0.004190,0.7820,191.019479,237.388911,0.245847,0.012351,0.008920,0.546742,0.002284,0.703257
287,中卫,Zhongwei,2014,中卫,18.86,0.86,38.68,27.49,中卫市,NaN,...,0.002832,0.8460,217.856651,208.074665,0.322438,0.006560,0.005954,0.679992,0.002610,0.603178
288,新疆,xinjiang,2014,新疆,598.58,125.51,1118.40,16.46,新疆维吾尔自治区,NaN,...,0.000686,0.9902,20.294191,66.578463,0.376268,0.001150,0.001268,0.980221,0.000211,0.120107
289,乌鲁木齐,Urumuchi,2014,乌鲁木齐,260.50,47.31,412.26,10.08,乌鲁木齐市,乌鲁木齐市,...,0.029889,0.9889,1784.578989,135.964895,0.968932,0.037512,0.065035,0.977514,0.021635,0.356993
290,克拉玛依,Kelamayi,2014,克拉玛依,28.08,8.39,69.38,28.72,克拉玛依市,NaN,...,0.009409,0.9939,1149.542311,68.179318,0.620496,0.023661,0.020315,0.987924,0.013924,0.125572

In [49]:
columns_to_keep = ['Name_of_Regions','Citycode','Year','X1_star','X2_star','X3_star','X4_star','X5_star','X6_star']
data_process_UI = data_merged[columns_to_keep]

In [50]:
data_process_UI

,Name_of_Regions,Citycode,Year,X1_star,X2_star,X3_star,X4_star,X5_star,X6_star
0,北京,110000.0,2014,0.853290,0.140788,0.184195,0.985009,0.157853,0.806262
1,天津,120000.0,2014,0.808738,0.184072,0.145737,0.973975,0.160120,0.938967
2,石家庄,130100.0,2014,0.434628,0.062115,0.040778,0.804289,0.044624,0.876225
3,唐山,130200.0,2014,0.527616,0.037374,0.039146,0.813866,0.054710,0.912079
4,秦皇岛,130300.0,2014,0.391478,0.041836,0.028592,0.697689,0.018666,0.800163
...,...,...,...,...,...,...,...,...,...
286,固原,640400.0,2014,0.245847,0.012351,0.008920,0.546742,0.002284,0.703257
287,中卫,640500.0,2014,0.322438,0.006560,0.005954,0.679992,0.002610,0.603178
288,新疆,650000.0,2014,0.376268,0.001150,0.001268,0.980221,0.000211,0.120107
289,乌鲁木齐,650100.0,2014,0.968932,0.037512,0.065035,0.977514,0.021635,0.356993
290,克拉玛依,650200.0,2014,0.620496,0.023661,0.020315,0.987924,0.013924,0.125572

In [51]:
#1.7熵权法

def calculate_entropy(indicator_data):
    # Replace zero values to avoid log(0) and negative infinity in entropy calculation
    indicator_data = indicator_data.replace(0, np.finfo(float).eps)  # Use a small number instead of zero
    p_ij = indicator_data / indicator_data.sum()  # Calculate the proportion p_ij
    K = 1 / np.log(291)  # Calculate the constant K
    e_j = -K * (p_ij * np.log(p_ij)).sum()  # Calculate the entropy e_j
    return e_j

# Initialize an empty list to store DataFrames for each year
dataframes_list = []

# Calculate entropies and weights for each year
for year in range(2014, 2015):
    year_data = data_process_UI[data_process_UI['Year'] == year].copy()
    entropies = year_data[['X1_star', 'X2_star', 'X3_star', 'X4_star','X5_star','X6_star']].apply(calculate_entropy, axis=0)
    weights = (1 - entropies) / (1 - entropies).sum()  # Calculate weights, ensuring they sum up to 1 within the year
    for i, indicator in enumerate(['X1_star', 'X2_star', 'X3_star', 'X4_star','X5_star','X6_star']):
        year_data[indicator + '_weighted'] = year_data[indicator] * weights.values[i]  # Apply weights to the indicators
    dataframes_list.append(year_data)  # Append the yearly data to the list

# Concatenate all DataFrames in the list to create the comprehensive_scores DataFrame
UI = pd.concat(dataframes_list, ignore_index=True)

# Now you should have the comprehensive_scores DataFrame with correctly calculated weights per year

In [52]:
UI

,Name_of_Regions,Citycode,Year,X1_star,X2_star,X3_star,X4_star,X5_star,X6_star,X1_star_weighted,X2_star_weighted,X3_star_weighted,X4_star_weighted,X5_star_weighted,X6_star_weighted
0,北京,110000.0,2014,0.853290,0.140788,0.184195,0.985009,0.157853,0.806262,0.017193,0.047977,0.059281,0.009651,0.047146,0.007072
1,天津,120000.0,2014,0.808738,0.184072,0.145737,0.973975,0.160120,0.938967,0.016295,0.062727,0.046904,0.009543,0.047823,0.008235
2,石家庄,130100.0,2014,0.434628,0.062115,0.040778,0.804289,0.044624,0.876225,0.008757,0.021167,0.013124,0.007881,0.013328,0.007685
3,唐山,130200.0,2014,0.527616,0.037374,0.039146,0.813866,0.054710,0.912079,0.010631,0.012736,0.012599,0.007974,0.016340,0.008000
4,秦皇岛,130300.0,2014,0.391478,0.041836,0.028592,0.697689,0.018666,0.800163,0.007888,0.014257,0.009202,0.006836,0.005575,0.007018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,固原,640400.0,2014,0.245847,0.012351,0.008920,0.546742,0.002284,0.703257,0.004953,0.004209,0.002871,0.005357,0.000682,0.006168
287,中卫,640500.0,2014,0.322438,0.006560,0.005954,0.679992,0.002610,0.603178,0.006497,0.002235,0.001916,0.006663,0.000780,0.005290
288,新疆,650000.0,2014,0.376268,0.001150,0.001268,0.980221,0.000211,0.120107,0.007581,0.000392,0.000408,0.009604,0.000063,0.001053
289,乌鲁木齐,650100.0,2014,0.968932,0.037512,0.065035,0.977514,0.021635,0.356993,0.019523,0.012783,0.020931,0.009578,0.006462,0.003131
290,克拉玛依,650200.0,2014,0.620496,0.023661,0.020315,0.987924,0.013924,0.125572,0.012502,0.008063,0.006538,0.009680,0.004159,0.001101

In [53]:
# Calculate the combined weighted values for Resistance, Adaptability, and Recovery
UI['PU'] = UI['X1_star_weighted'] + UI['X2_star_weighted']
UI['LU'] = UI['X3_star_weighted'] + UI['X6_star_weighted']
#comprehensive_scores['ADA'] = comprehensive_scores['X2_star_weighted'] 
UI['EU'] = UI['X4_star_weighted'] + UI['X5_star_weighted']

# Assuming data_merged is the DataFrame with the standardized 'RES', 'ADA', and 'REC' columns.

# Define a small positive value to add to REC to avoid zero values
small_positive_value = 1e-6

# Replace zero values in REC with the small positive value
UI['PU_adj'] = UI['PU'].replace(0, small_positive_value)
UI['LU_adj'] = UI['LU'].replace(0, small_positive_value)
UI['EU_adj'] = UI['EU'].replace(0, small_positive_value)

# Now, the UER values should not be zero due to REC being zero, since we have adjusted REC values slightly above zero.

# Calculate the Urban Ecological Resilience (UER) for each borough and year
UI['UI'] = UI['PU_adj'] + UI['LU_adj'] + UI['EU_adj']

# Check the result
UI[['Year', 'Name_of_Regions', 'PU', 'LU', 'EU', 'UI']].head()

   Year Name_of_Regions        PU        LU        EU        UI
0  2014              北京  0.065169  0.066353  0.056797  0.188319
1  2014              天津  0.079022  0.055140  0.057366  0.191527
2  2014             石家庄  0.029924  0.020809  0.021208  0.071942
3  2014              唐山  0.023367  0.020599  0.024315  0.068280
4  2014             秦皇岛  0.022144  0.016220  0.012411  0.050775

In [62]:
UI

,Name_of_Regions,Citycode,Year,X1_star,X2_star,X3_star,X4_star,X5_star,X6_star,X1_star_weighted,...,X4_star_weighted,X5_star_weighted,X6_star_weighted,PU,LU,EU,PU_adj,LU_adj,EU_adj,UI
0,北京,110000.0,2014,0.853290,0.140788,0.184195,0.985009,0.157853,0.806262,0.017193,...,0.009651,0.047146,0.007072,0.065169,0.066353,0.056797,0.065169,0.066353,0.056797,0.188319
1,天津,120000.0,2014,0.808738,0.184072,0.145737,0.973975,0.160120,0.938967,0.016295,...,0.009543,0.047823,0.008235,0.079022,0.055140,0.057366,0.079022,0.055140,0.057366,0.191527
2,石家庄,130100.0,2014,0.434628,0.062115,0.040778,0.804289,0.044624,0.876225,0.008757,...,0.007881,0.013328,0.007685,0.029924,0.020809,0.021208,0.029924,0.020809,0.021208,0.071942
3,唐山,130200.0,2014,0.527616,0.037374,0.039146,0.813866,0.054710,0.912079,0.010631,...,0.007974,0.016340,0.008000,0.023367,0.020599,0.024315,0.023367,0.020599,0.024315,0.068280
4,秦皇岛,130300.0,2014,0.391478,0.041836,0.028592,0.697689,0.018666,0.800163,0.007888,...,0.006836,0.005575,0.007018,0.022144,0.016220,0.012411,0.022144,0.016220,0.012411,0.050775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,固原,640400.0,2014,0.245847,0.012351,0.008920,0.546742,0.002284,0.703257,0.004953,...,0.005357,0.000682,0.006168,0.009162,0.009039,0.006039,0.009162,0.009039,0.006039,0.024241
287,中卫,640500.0,2014,0.322438,0.006560,0.005954,0.679992,0.002610,0.603178,0.006497,...,0.006663,0.000780,0.005290,0.008732,0.007207,0.007442,0.008732,0.007207,0.007442,0.023381
288,新疆,650000.0,2014,0.376268,0.001150,0.001268,0.980221,0.000211,0.120107,0.007581,...,0.009604,0.000063,0.001053,0.007973,0.001462,0.009668,0.007973,0.001462,0.009668,0.019102
289,乌鲁木齐,650100.0,2014,0.968932,0.037512,0.065035,0.977514,0.021635,0.356993,0.019523,...,0.009578,0.006462,0.003131,0.032306,0.024062,0.016040,0.032306,0.024062,0.016040,0.072407
290,克拉玛依,650200.0,2014,0.620496,0.023661,0.020315,0.987924,0.013924,0.125572,0.012502,...,0.009680,0.004159,0.001101,0.020565,0.007640,0.013838,0.020565,0.007640,0.013838,0.042043

In [55]:
columns_to_keep = ['Name_of_Regions','Citycode','Year','Res1','Res2','Ada1','Ada2','Rec1','Rec2']
data_merged = df_cleaned[columns_to_keep]

In [56]:
data_merged

,Name_of_Regions,Citycode,Year,Res1,Res2,Ada1,Ada2,Rec1,Rec2
0,北京,110000.0,NaN,0.000043,0.000106,87.670,99.59,60.41,15.94
1,天津,120000.0,NaN,0.000121,0.000713,98.910,96.23,41.82,9.73
3,石家庄,130100.0,NaN,0.000465,0.002017,95.100,71.98,48.98,15.33
4,唐山,130200.0,NaN,0.000224,0.008612,70.000,100.00,41.17,15.08
5,秦皇岛,130300.0,NaN,0.000523,0.004935,65.000,157.94,92.87,20.41
...,...,...,...,...,...,...,...,...,...
314,固原,640400.0,NaN,0.000124,0.001375,93.700,92.82,27.45,7.99
315,中卫,640500.0,NaN,0.000943,0.020200,92.740,96.90,36.82,20.08
316,新疆,650000.0,NaN,0.000202,0.002465,55.632,81.90,36.80,10.74
317,乌鲁木齐,650100.0,NaN,0.000197,0.003131,93.660,92.42,38.52,10.66
318,克拉玛依,650200.0,NaN,0.000218,0.000531,98.610,98.98,43.28,11.48

In [64]:
# Initialize a column for the normalized values
data_merged['X1_star'] = pd.Series(dtype='float')
column_to_normalize = 'Res1'
# Iterate over each year to perform the normalization
for year in range(2014, 2015):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X1_max = year_data[column_to_normalize].max()
    X1_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X1_star'] = (X1_max - year_data[column_to_normalize]) / (X1_max - X1_min)


# Initialize a column for the normalized values
data_merged['X2_star'] = pd.Series(dtype='float')
column_to_normalize = 'Res2'
# Iterate over each year to perform the normalization
for year in range(2014, 2015):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X2_max = year_data[column_to_normalize].max()
    X2_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X2_star'] = (X2_max - year_data[column_to_normalize]) / (X2_max - X2_min)

data_merged['X3_star'] = pd.Series(dtype='float')
column_to_normalize = 'Ada1'
# Iterate over each year to perform the normalization
for year in range(2014, 2015):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X3_max = year_data[column_to_normalize].max()
    X3_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X3_star'] = (year_data[column_to_normalize] - X3_min) / (X3_max - X3_min)

data_merged['X4_star'] = pd.Series(dtype='float')
column_to_normalize = 'Ada2'
# Iterate over each year to perform the normalization
for year in range(2014, 2015):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X4_max = year_data[column_to_normalize].max()
    X4_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X4_star'] = (year_data[column_to_normalize] - X4_min) / (X4_max - X4_min)

data_merged['X5_star'] = pd.Series(dtype='float')
column_to_normalize = 'Rec1'
# Iterate over each year to perform the normalization
for year in range(2014, 2015):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X5_max = year_data[column_to_normalize].max()
    X5_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X5_star'] = (year_data[column_to_normalize] - X5_min) / (X5_max - X5_min)

data_merged['X6_star'] = pd.Series(dtype='float')
column_to_normalize = 'Rec2'
# Iterate over each year to perform the normalization
for year in range(2014, 2015):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X6_max = year_data[column_to_normalize].max()
    X6_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X6_star'] = (year_data[column_to_normalize] - X6_min) / (X6_max - X6_min)

/tmp/ipykernel_30452/1432188144.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_merged['X1_star'] = pd.Series(dtype='float')
/tmp/ipykernel_30452/1432188144.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_merged['X2_star'] = pd.Series(dtype='float')
/tmp/ipykernel_30452/1432188144.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_merged['X3_star'] = pd.Series(dtype='float')
/tmp/ipykernel_30452/1432188144.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_merged['X4_star'] = pd.Series(dtype='float')
/tmp/ipykernel_30452/1432188144.py:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_merged['X5_star'] = pd.Series(dtype='float')
/tmp/ipykernel_30452/1432188144.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_merged['X6_star'] = pd.Series(dtype='float')

In [65]:
data_merged

,Name_of_Regions,Citycode,Year,Res1,Res2,Ada1,Ada2,Rec1,Rec2,X1_star,X2_star,X3_star,X4_star,X5_star,X6_star
0,北京,110000.0,2014,0.000043,0.000106,87.670,99.59,60.41,15.94,0.987892,0.996245,0.874068,0.630556,0.630266,0.187826
1,天津,120000.0,2014,0.000121,0.000713,98.910,96.23,41.82,9.73,0.958029,0.974856,0.988867,0.609282,0.432983,0.102501
3,石家庄,130100.0,2014,0.000465,0.002017,95.100,71.98,48.98,15.33,0.826196,0.928874,0.949954,0.455743,0.508967,0.179445
4,唐山,130200.0,2014,0.000224,0.008612,70.000,100.00,41.17,15.08,0.918310,0.696309,0.693596,0.633152,0.426085,0.176010
5,秦皇岛,130300.0,2014,0.000523,0.004935,65.000,157.94,92.87,20.41,0.803921,0.825964,0.642529,1.000000,0.974743,0.249244
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,固原,640400.0,2014,0.000124,0.001375,93.700,92.82,27.45,7.99,0.956886,0.951495,0.935655,0.587692,0.280484,0.078593
315,中卫,640500.0,2014,0.000943,0.020200,92.740,96.90,36.82,20.08,0.642769,0.287635,0.925850,0.613524,0.379921,0.244710
316,新疆,650000.0,2014,0.000202,0.002465,55.632,81.90,36.80,10.74,0.926764,0.913059,0.546849,0.518551,0.379709,0.116378
317,乌鲁木齐,650100.0,2014,0.000197,0.003131,93.660,92.42,38.52,10.66,0.928840,0.889573,0.935247,0.585159,0.397962,0.115279
318,克拉玛依,650200.0,2014,0.000218,0.000531,98.610,98.98,43.28,11.48,0.920737,0.981258,0.985803,0.626694,0.448477,0.126546

In [66]:
columns_to_keep = ['Name_of_Regions','Citycode','Year','X1_star','X2_star','X3_star','X4_star','X5_star','X6_star']
data_process = data_merged[columns_to_keep]

In [67]:
#1.7熵权法

def calculate_entropy(indicator_data):
    # Replace zero values to avoid log(0) and negative infinity in entropy calculation
    indicator_data = indicator_data.replace(0, np.finfo(float).eps)  # Use a small number instead of zero
    p_ij = indicator_data / indicator_data.sum()  # Calculate the proportion p_ij
    K = 1 / np.log(291)  # Calculate the constant K
    e_j = -K * (p_ij * np.log(p_ij)).sum()  # Calculate the entropy e_j
    return e_j

# Initialize an empty list to store DataFrames for each year
dataframes_list = []

# Calculate entropies and weights for each year
for year in range(2014, 2015):
    year_data = data_process[data_process['Year'] == year].copy()
    entropies = year_data[['X1_star', 'X2_star', 'X3_star', 'X4_star','X5_star','X6_star']].apply(calculate_entropy, axis=0)
    weights = (1 - entropies) / (1 - entropies).sum()  # Calculate weights, ensuring they sum up to 1 within the year
    for i, indicator in enumerate(['X1_star', 'X2_star', 'X3_star', 'X4_star','X5_star','X6_star']):
        year_data[indicator + '_weighted'] = year_data[indicator] * weights.values[i]  # Apply weights to the indicators
    dataframes_list.append(year_data)  # Append the yearly data to the list

# Concatenate all DataFrames in the list to create the comprehensive_scores DataFrame
UER = pd.concat(dataframes_list, ignore_index=True)

# Now you should have the comprehensive_scores DataFrame with correctly calculated weights per year

In [68]:
UER

,Name_of_Regions,Citycode,Year,X1_star,X2_star,X3_star,X4_star,X5_star,X6_star,X1_star_weighted,X2_star_weighted,X3_star_weighted,X4_star_weighted,X5_star_weighted,X6_star_weighted
0,北京,110000.0,2014,0.987892,0.996245,0.874068,0.630556,0.630266,0.187826,0.041244,0.052954,0.194246,0.085946,0.080648,0.078625
1,天津,120000.0,2014,0.958029,0.974856,0.988867,0.609282,0.432983,0.102501,0.039997,0.051817,0.219758,0.083047,0.055404,0.042907
2,石家庄,130100.0,2014,0.826196,0.928874,0.949954,0.455743,0.508967,0.179445,0.034493,0.049373,0.211110,0.062119,0.065127,0.075116
3,唐山,130200.0,2014,0.918310,0.696309,0.693596,0.633152,0.426085,0.176010,0.038339,0.037011,0.154139,0.086300,0.054521,0.073678
4,秦皇岛,130300.0,2014,0.803921,0.825964,0.642529,1.000000,0.974743,0.249244,0.033563,0.043903,0.142791,0.136302,0.124726,0.104335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,固原,640400.0,2014,0.956886,0.951495,0.935655,0.587692,0.280484,0.078593,0.039950,0.050575,0.207933,0.080104,0.035890,0.032899
287,中卫,640500.0,2014,0.642769,0.287635,0.925850,0.613524,0.379921,0.244710,0.026835,0.015289,0.205754,0.083625,0.048614,0.102437
288,新疆,650000.0,2014,0.926764,0.913059,0.546849,0.518551,0.379709,0.116378,0.038692,0.048532,0.121528,0.070680,0.048587,0.048716
289,乌鲁木齐,650100.0,2014,0.928840,0.889573,0.935247,0.585159,0.397962,0.115279,0.038779,0.047284,0.207842,0.079758,0.050923,0.048256
290,克拉玛依,650200.0,2014,0.920737,0.981258,0.985803,0.626694,0.448477,0.126546,0.038440,0.052157,0.219077,0.085420,0.057386,0.052973

In [69]:
# Calculate the combined weighted values for Resistance, Adaptability, and Recovery
UER['RES'] = UER['X1_star_weighted'] + UER['X2_star_weighted']
UER['ADA'] = UER['X3_star_weighted'] + UER['X4_star_weighted']
#comprehensive_scores['ADA'] = comprehensive_scores['X2_star_weighted'] 
UER['REC'] = UER['X5_star_weighted'] + UER['X6_star_weighted']

# Assuming data_merged is the DataFrame with the standardized 'RES', 'ADA', and 'REC' columns.

# Define a small positive value to add to REC to avoid zero values
small_positive_value = 1e-6

# Replace zero values in REC with the small positive value
UER['REC_adj'] = UER['REC'].replace(0, small_positive_value)
UER['ADA_adj'] = UER['ADA'].replace(0, small_positive_value)
UER['RES_adj'] = UER['RES'].replace(0, small_positive_value)

# Now, the UER values should not be zero due to REC being zero, since we have adjusted REC values slightly above zero.

# Calculate the Urban Ecological Resilience (UER) for each borough and year
UER['UER'] = (UER['RES_adj'] * UER['ADA_adj'] * UER['REC_adj']) ** (1/3)

# Check the result
UER[['Year', 'Name_of_Regions', 'RES', 'ADA', 'REC', 'UER']].head()

   Year Name_of_Regions       RES       ADA       REC       UER
0  2014              北京  0.094198  0.280192  0.159273  0.161391
1  2014              天津  0.091815  0.302805  0.098311  0.139817
2  2014             石家庄  0.083866  0.273229  0.140243  0.147570
3  2014              唐山  0.075351  0.240440  0.128200  0.132432
4  2014             秦皇岛  0.077466  0.279093  0.229061  0.170453

In [70]:
UER

,Name_of_Regions,Citycode,Year,X1_star,X2_star,X3_star,X4_star,X5_star,X6_star,X1_star_weighted,...,X4_star_weighted,X5_star_weighted,X6_star_weighted,RES,ADA,REC,REC_adj,ADA_adj,RES_adj,UER
0,北京,110000.0,2014,0.987892,0.996245,0.874068,0.630556,0.630266,0.187826,0.041244,...,0.085946,0.080648,0.078625,0.094198,0.280192,0.159273,0.159273,0.280192,0.094198,0.161391
1,天津,120000.0,2014,0.958029,0.974856,0.988867,0.609282,0.432983,0.102501,0.039997,...,0.083047,0.055404,0.042907,0.091815,0.302805,0.098311,0.098311,0.302805,0.091815,0.139817
2,石家庄,130100.0,2014,0.826196,0.928874,0.949954,0.455743,0.508967,0.179445,0.034493,...,0.062119,0.065127,0.075116,0.083866,0.273229,0.140243,0.140243,0.273229,0.083866,0.147570
3,唐山,130200.0,2014,0.918310,0.696309,0.693596,0.633152,0.426085,0.176010,0.038339,...,0.086300,0.054521,0.073678,0.075351,0.240440,0.128200,0.128200,0.240440,0.075351,0.132432
4,秦皇岛,130300.0,2014,0.803921,0.825964,0.642529,1.000000,0.974743,0.249244,0.033563,...,0.136302,0.124726,0.104335,0.077466,0.279093,0.229061,0.229061,0.279093,0.077466,0.170453
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,固原,640400.0,2014,0.956886,0.951495,0.935655,0.587692,0.280484,0.078593,0.039950,...,0.080104,0.035890,0.032899,0.090525,0.288036,0.068790,0.068790,0.288036,0.090525,0.121501
287,中卫,640500.0,2014,0.642769,0.287635,0.925850,0.613524,0.379921,0.244710,0.026835,...,0.083625,0.048614,0.102437,0.042124,0.289379,0.151051,0.151051,0.289379,0.042124,0.122567
288,新疆,650000.0,2014,0.926764,0.913059,0.546849,0.518551,0.379709,0.116378,0.038692,...,0.070680,0.048587,0.048716,0.087225,0.192207,0.097303,0.097303,0.192207,0.087225,0.117719
289,乌鲁木齐,650100.0,2014,0.928840,0.889573,0.935247,0.585159,0.397962,0.115279,0.038779,...,0.079758,0.050923,0.048256,0.086063,0.287601,0.099179,0.099179,0.287601,0.086063,0.134899
290,克拉玛依,650200.0,2014,0.920737,0.981258,0.985803,0.626694,0.448477,0.126546,0.038440,...,0.085420,0.057386,0.052973,0.090598,0.304497,0.110359,0.110359,0.304497,0.090598,0.144934

In [71]:
df_merged1 = pd.merge(UI, UER, on=['Citycode', 'Year'])

In [72]:
df_merged1

,Name_of_Regions_x,Citycode,Year,X1_star_x,X2_star_x,X3_star_x,X4_star_x,X5_star_x,X6_star_x,X1_star_weighted_x,...,X4_star_weighted_y,X5_star_weighted_y,X6_star_weighted_y,RES,ADA,REC,REC_adj,ADA_adj,RES_adj,UER
0,北京,110000.0,2014,0.853290,0.140788,0.184195,0.985009,0.157853,0.806262,0.017193,...,0.085946,0.080648,0.078625,0.094198,0.280192,0.159273,0.159273,0.280192,0.094198,0.161391
1,天津,120000.0,2014,0.808738,0.184072,0.145737,0.973975,0.160120,0.938967,0.016295,...,0.083047,0.055404,0.042907,0.091815,0.302805,0.098311,0.098311,0.302805,0.091815,0.139817
2,石家庄,130100.0,2014,0.434628,0.062115,0.040778,0.804289,0.044624,0.876225,0.008757,...,0.062119,0.065127,0.075116,0.083866,0.273229,0.140243,0.140243,0.273229,0.083866,0.147570
3,唐山,130200.0,2014,0.527616,0.037374,0.039146,0.813866,0.054710,0.912079,0.010631,...,0.086300,0.054521,0.073678,0.075351,0.240440,0.128200,0.128200,0.240440,0.075351,0.132432
4,秦皇岛,130300.0,2014,0.391478,0.041836,0.028592,0.697689,0.018666,0.800163,0.007888,...,0.136302,0.124726,0.104335,0.077466,0.279093,0.229061,0.229061,0.279093,0.077466,0.170453
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,固原,640400.0,2014,0.245847,0.012351,0.008920,0.546742,0.002284,0.703257,0.004953,...,0.080104,0.035890,0.032899,0.090525,0.288036,0.068790,0.068790,0.288036,0.090525,0.121501
287,中卫,640500.0,2014,0.322438,0.006560,0.005954,0.679992,0.002610,0.603178,0.006497,...,0.083625,0.048614,0.102437,0.042124,0.289379,0.151051,0.151051,0.289379,0.042124,0.122567
288,新疆,650000.0,2014,0.376268,0.001150,0.001268,0.980221,0.000211,0.120107,0.007581,...,0.070680,0.048587,0.048716,0.087225,0.192207,0.097303,0.097303,0.192207,0.087225,0.117719
289,乌鲁木齐,650100.0,2014,0.968932,0.037512,0.065035,0.977514,0.021635,0.356993,0.019523,...,0.079758,0.050923,0.048256,0.086063,0.287601,0.099179,0.099179,0.287601,0.086063,0.134899
290,克拉玛依,650200.0,2014,0.620496,0.023661,0.020315,0.987924,0.013924,0.125572,0.012502,...,0.085420,0.057386,0.052973,0.090598,0.304497,0.110359,0.110359,0.304497,0.090598,0.144934

In [73]:
df_result = df_merged1[['Name_of_Regions_x', 'Citycode', 'Year', 'UER', 'UI']]

In [74]:
df_result

    Name_of_Regions_x  Citycode  Year       UER        UI
0                  北京  110000.0  2014  0.161391  0.188319
1                  天津  120000.0  2014  0.139817  0.191527
2                 石家庄  130100.0  2014  0.147570  0.071942
3                  唐山  130200.0  2014  0.132432  0.068280
4                 秦皇岛  130300.0  2014  0.170453  0.050775
..                ...       ...   ...       ...       ...
286                固原  640400.0  2014  0.121501  0.024241
287                中卫  640500.0  2014  0.122567  0.023381
288                新疆  650000.0  2014  0.117719  0.019102
289              乌鲁木齐  650100.0  2014  0.134899  0.072407
290              克拉玛依  650200.0  2014  0.144934  0.042043

[291 rows x 5 columns]

In [75]:
# 定义计算公式
def calculate_C(UI, UER):
    return np.sqrt((UI * UER) / ((UI + UER) / 2)**2)

def calculate_T(UI, UER, mu1=0.5, mu2=0.5):
    return mu1 * UI + mu2 * UER

def calculate_D(C, T):
    return np.sqrt(C * T)

# 计算C耦合度
df_result['C'] = df_result.apply(lambda row: calculate_C(row['UI'], row['UER']), axis=1)

# 计算T协调度
df_result['T'] = df_result.apply(lambda row: calculate_T(row['UI'], row['UER']), axis=1)

# 计算D耦合协调度
df_result['D'] = df_result.apply(lambda row: calculate_D(row['C'], row['T']), axis=1)

/tmp/ipykernel_30452/4091750289.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['C'] = df_result.apply(lambda row: calculate_C(row['UI'], row['UER']), axis=1)
/tmp/ipykernel_30452/4091750289.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['T'] = df_result.apply(lambda row: calculate_T(row['UI'], row['UER']), axis=1)
/tmp/ipykernel_30452/4091750289.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['D'] = df_result.apply(lambda row: calculate_D(row['C'], row['T']), axis=1)

In [76]:
# 定义归一化公式
def normalize(column):
    return (column - column.min()) / (column.max() - column.min())

# 归一化处理
df_result['UI_normalized'] = normalize(df_result['UI'])
df_result['UER_normalized'] = normalize(df_result['UER'])

# 定义计算公式
def calculate_C(UI, UER):
    return np.sqrt((UI * UER) / ((UI + UER) / 2)**2)

def calculate_T(UI, UER, mu1=0.5, mu2=0.5):
    return mu1 * UI + mu2 * UER

def calculate_D(C, T):
    return np.sqrt(C * T)

# 计算C耦合度
df_result['C2'] = df_result.apply(lambda row: calculate_C(row['UI_normalized'], row['UER_normalized']), axis=1)

# 计算T协调度
df_result['T2'] = df_result.apply(lambda row: calculate_T(row['UI_normalized'], row['UER_normalized']), axis=1)

# 计算D耦合协调度
df_result['D2'] = df_result.apply(lambda row: calculate_D(row['C2'], row['T2']), axis=1)

/tmp/ipykernel_30452/3512385329.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['UI_normalized'] = normalize(df_result['UI'])
/tmp/ipykernel_30452/3512385329.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['UER_normalized'] = normalize(df_result['UER'])
/tmp/ipykernel_30452/3512385329.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['C2'] = df_result.apply(lambda row: calculate_C(row['UI_normalized'], row['UER_normalized']), axis=1)
/tmp/ipykernel_30452/3512385329.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['T2'] = df_result.apply(lambda row: calculate_T(row['UI_normalized'], row['UER_normalized']), axis=1)
/tmp/ipykernel_30452/3512385329.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['D2'] = df_result.apply(lambda row: calculate_D(row['C2'], row['T2']), axis=1)

In [77]:
df_result

,Name_of_Regions_x,Citycode,Year,UER,UI,C,T,D,UI_normalized,UER_normalized,C2,T2,D2
0,北京,110000.0,2014,0.161391,0.188319,0.997031,0.174855,0.417536,0.176834,0.747975,0.786510,0.462404,0.603064
1,天津,120000.0,2014,0.139817,0.191527,0.987747,0.165672,0.404527,0.180092,0.627424,0.832543,0.403758,0.579781
2,石家庄,130100.0,2014,0.147570,0.071942,0.938775,0.109756,0.320992,0.058646,0.670748,0.543834,0.364697,0.445348
3,唐山,130200.0,2014,0.132432,0.068280,0.947545,0.100356,0.308370,0.054927,0.586162,0.559776,0.320544,0.423595
4,秦皇岛,130300.0,2014,0.170453,0.050775,0.841043,0.110614,0.305010,0.037150,0.798608,0.412190,0.417879,0.415025
...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,固原,640400.0,2014,0.121501,0.024241,0.744748,0.072871,0.232960,0.010203,0.525083,0.273476,0.267643,0.270544
287,中卫,640500.0,2014,0.122567,0.023381,0.733585,0.072974,0.231371,0.009330,0.531041,0.260518,0.270185,0.265308
288,新疆,650000.0,2014,0.117719,0.019102,0.693176,0.068411,0.217763,0.004985,0.503949,0.196959,0.254467,0.223874
289,乌鲁木齐,650100.0,2014,0.134899,0.072407,0.953483,0.103653,0.314375,0.059119,0.599945,0.571505,0.329532,0.433969
290,克拉玛依,650200.0,2014,0.144934,0.042043,0.834976,0.093488,0.279393,0.028282,0.656017,0.398104,0.342149,0.369068

In [78]:
# 导出comprehensive_scores数据框为Excel文件
output_excel_path = 'data/df_2014_result.xlsx'
df_result.to_excel(output_excel_path, index=False)

In [2]:
#如果未运行以上步骤，导入本年数据
file_path = 'data/df_2014_result.xlsx'
df_result = pd.read_excel(file_path)

In [79]:
file_path = 'data/df_2010_result.xlsx'
df_result_2010 = pd.read_excel(file_path)

In [80]:
df_result_2010

,Name_of_Regions_x,Citycode,Year,UER,UI,C,T,D,UI_normalized,UER_normalized,C2,T2,D2
0,北京,110000,2010,0.168303,0.206704,0.994743,0.187503,0.431877,0.200826,0.839766,0.789294,0.520296,0.640833
1,天津,120000,2010,0.152355,0.197102,0.991768,0.174729,0.416281,0.190941,0.760175,0.801130,0.475558,0.617239
2,石家庄,130100,2010,0.174103,0.079555,0.927936,0.126829,0.343059,0.069926,0.868715,0.525158,0.469321,0.496455
3,唐山,130200,2010,0.173093,0.076014,0.920939,0.124553,0.338683,0.066281,0.863673,0.514562,0.464977,0.489142
4,秦皇岛,130300,2010,0.183608,0.064805,0.878226,0.124207,0.330275,0.054742,0.916151,0.461319,0.485446,0.473229
...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,固原,640400,2010,0.149317,0.017109,0.607403,0.083213,0.224820,0.005639,0.745015,0.172687,0.375327,0.254586
286,中卫,640500,2010,0.095024,0.023502,0.797418,0.059263,0.217388,0.012220,0.474050,0.313042,0.243135,0.275883
287,新疆,650000,2010,0.134498,0.027310,0.749113,0.080904,0.246183,0.016140,0.671055,0.302887,0.343597,0.322601
288,乌鲁木齐,650100,2010,0.137691,0.103063,0.989602,0.120377,0.345146,0.094128,0.686991,0.651100,0.390560,0.504275
289,克拉玛依,650200,2010,0.156935,0.072887,0.930728,0.114911,0.327034,0.063062,0.783035,0.525271,0.423048,0.471397

In [81]:
# 找出 df_result_2010 和 df_result 在 Citycode 列不匹配的行
mismatch_2010 = df_result_2010[~df_result_2010['Citycode'].isin(df_result['Citycode'])]
mismatch_result = df_result[~df_result['Citycode'].isin(df_result_2010['Citycode'])]

# 输出不匹配的行
print("Rows in df_result_2010 not in df_result:")
print(mismatch_2010)

print("\nRows in df_result not in df_result_2010:")
print(mismatch_result)

Rows in df_result_2010 not in df_result:
    Name_of_Regions_x  Citycode  Year       UER        UI         C         T  \
161                济源    419001  2010  0.000038  0.073656  0.045602  0.036847

            D  UI_normalized  UER_normalized   C2        T2   D2
161  0.040992       0.063854             0.0  0.0  0.031927  0.0

Rows in df_result not in df_result_2010:
    Name_of_Regions_x  Citycode  Year       UER        UI         C         T  \
247                铜仁  520600.0  2014  0.104455  0.015689  0.673890  0.060072
248                毕节  520500.0  2014  0.128655  0.015568  0.620627  0.072111

            D  UI_normalized  UER_normalized        C2        T2        D2
247  0.201201       0.001518        0.429838  0.118436  0.215678  0.159825
248  0.211552       0.001396        0.565055  0.099153  0.283225  0.167579

In [82]:
# 合并数据
df_merged2 = pd.merge(df_result_2010, df_result, left_on='Citycode', right_on='Citycode', suffixes=('_2010', '_2014'))

In [83]:
df_merged2

,Name_of_Regions_x_2010,Citycode,Year_2010,UER_2010,UI_2010,C_2010,T_2010,D_2010,UI_normalized_2010,UER_normalized_2010,...,UER_2014,UI_2014,C_2014,T_2014,D_2014,UI_normalized_2014,UER_normalized_2014,C2_2014,T2_2014,D2_2014
0,北京,110000,2010,0.168303,0.206704,0.994743,0.187503,0.431877,0.200826,0.839766,...,0.161391,0.188319,0.997031,0.174855,0.417536,0.176834,0.747975,0.786510,0.462404,0.603064
1,天津,120000,2010,0.152355,0.197102,0.991768,0.174729,0.416281,0.190941,0.760175,...,0.139817,0.191527,0.987747,0.165672,0.404527,0.180092,0.627424,0.832543,0.403758,0.579781
2,石家庄,130100,2010,0.174103,0.079555,0.927936,0.126829,0.343059,0.069926,0.868715,...,0.147570,0.071942,0.938775,0.109756,0.320992,0.058646,0.670748,0.543834,0.364697,0.445348
3,唐山,130200,2010,0.173093,0.076014,0.920939,0.124553,0.338683,0.066281,0.863673,...,0.132432,0.068280,0.947545,0.100356,0.308370,0.054927,0.586162,0.559776,0.320544,0.423595
4,秦皇岛,130300,2010,0.183608,0.064805,0.878226,0.124207,0.330275,0.054742,0.916151,...,0.170453,0.050775,0.841043,0.110614,0.305010,0.037150,0.798608,0.412190,0.417879,0.415025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,固原,640400,2010,0.149317,0.017109,0.607403,0.083213,0.224820,0.005639,0.745015,...,0.121501,0.024241,0.744748,0.072871,0.232960,0.010203,0.525083,0.273476,0.267643,0.270544
285,中卫,640500,2010,0.095024,0.023502,0.797418,0.059263,0.217388,0.012220,0.474050,...,0.122567,0.023381,0.733585,0.072974,0.231371,0.009330,0.531041,0.260518,0.270185,0.265308
286,新疆,650000,2010,0.134498,0.027310,0.749113,0.080904,0.246183,0.016140,0.671055,...,0.117719,0.019102,0.693176,0.068411,0.217763,0.004985,0.503949,0.196959,0.254467,0.223874
287,乌鲁木齐,650100,2010,0.137691,0.103063,0.989602,0.120377,0.345146,0.094128,0.686991,...,0.134899,0.072407,0.953483,0.103653,0.314375,0.059119,0.599945,0.571505,0.329532,0.433969
288,克拉玛依,650200,2010,0.156935,0.072887,0.930728,0.114911,0.327034,0.063062,0.783035,...,0.144934,0.042043,0.834976,0.093488,0.279393,0.028282,0.656017,0.398104,0.342149,0.369068

# 计算Tapio脱钩模型

In [84]:
# 计算增长率
df_merged2['Delta_UER'] = (df_merged2['UER_2014'] - df_merged2['UER_2010']) / df_merged2['UER_2010']
df_merged2['Delta_UI'] = (df_merged2['UI_2014'] - df_merged2['UI_2010']) / df_merged2['UI_2010']

# 计算脱钩指数DI
df_merged2['DI'] = df_merged2['Delta_UER'] / df_merged2['Delta_UI']

In [85]:
df_merged2

,Name_of_Regions_x_2010,Citycode,Year_2010,UER_2010,UI_2010,C_2010,T_2010,D_2010,UI_normalized_2010,UER_normalized_2010,...,T_2014,D_2014,UI_normalized_2014,UER_normalized_2014,C2_2014,T2_2014,D2_2014,Delta_UER,Delta_UI,DI
0,北京,110000,2010,0.168303,0.206704,0.994743,0.187503,0.431877,0.200826,0.839766,...,0.174855,0.417536,0.176834,0.747975,0.786510,0.462404,0.603064,-0.041066,-0.088940,0.461723
1,天津,120000,2010,0.152355,0.197102,0.991768,0.174729,0.416281,0.190941,0.760175,...,0.165672,0.404527,0.180092,0.627424,0.832543,0.403758,0.579781,-0.082297,-0.028283,2.909822
2,石家庄,130100,2010,0.174103,0.079555,0.927936,0.126829,0.343059,0.069926,0.868715,...,0.109756,0.320992,0.058646,0.670748,0.543834,0.364697,0.445348,-0.152398,-0.095698,1.592491
3,唐山,130200,2010,0.173093,0.076014,0.920939,0.124553,0.338683,0.066281,0.863673,...,0.100356,0.308370,0.054927,0.586162,0.559776,0.320544,0.423595,-0.234908,-0.101744,2.308817
4,秦皇岛,130300,2010,0.183608,0.064805,0.878226,0.124207,0.330275,0.054742,0.916151,...,0.110614,0.305010,0.037150,0.798608,0.412190,0.417879,0.415025,-0.071647,-0.216492,0.330947
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,固原,640400,2010,0.149317,0.017109,0.607403,0.083213,0.224820,0.005639,0.745015,...,0.072871,0.232960,0.010203,0.525083,0.273476,0.267643,0.270544,-0.186291,0.416829,-0.446924
285,中卫,640500,2010,0.095024,0.023502,0.797418,0.059263,0.217388,0.012220,0.474050,...,0.072974,0.231371,0.009330,0.531041,0.260518,0.270185,0.265308,0.289854,-0.005151,-56.270582
286,新疆,650000,2010,0.134498,0.027310,0.749113,0.080904,0.246183,0.016140,0.671055,...,0.068411,0.217763,0.004985,0.503949,0.196959,0.254467,0.223874,-0.124755,-0.300527,0.415121
287,乌鲁木齐,650100,2010,0.137691,0.103063,0.989602,0.120377,0.345146,0.094128,0.686991,...,0.103653,0.314375,0.059119,0.599945,0.571505,0.329532,0.433969,-0.020280,-0.297449,0.068180
288,克拉玛依,650200,2010,0.156935,0.072887,0.930728,0.114911,0.327034,0.063062,0.783035,...,0.093488,0.279393,0.028282,0.656017,0.398104,0.342149,0.369068,-0.076475,-0.423174,0.180718

In [86]:
def classify_decoupling(row):
    Delta_ER = row['Delta_UER']
    Delta_UI = row['Delta_UI']
    DI = row['DI']
    
    if Delta_ER < 0 and Delta_UI < 0 and 1.2 <= DI < float('inf'):
        return 'Recession decoupling / Decoupling'
    elif Delta_ER < 0 and Delta_UI > 0 and float('-inf') < DI <= 0:
        return 'Strong decoupling / Decoupling'
    elif Delta_ER > 0 and Delta_UI > 0 and 0 <= DI <= 0.8:
        return 'Weak decoupling / Decoupling'
    elif Delta_ER > 0 and Delta_UI > 0 and 0.8 < DI <= 1.2:
        return 'Expansion connection / Connection'
    elif Delta_ER < 0 and Delta_UI < 0 and 0.8 < DI <= 1.2:
        return 'Recession connection / Connection'
    elif Delta_ER > 0 and Delta_UI > 0 and 1.2 <= DI < float('inf'):
        return 'Negative decoupling of expansion / Negative decoupling'
    elif Delta_ER > 0 and Delta_UI < 0 and float('-inf') < DI <= 0:
        return 'Strong negative decoupling / Negative decoupling'
    elif Delta_ER < 0 and Delta_UI < 0 and 0 <= DI <= 0.8:
        return 'Weak negative decoupling / Negative decoupling'
    else:
        return 'Unknown'

# Apply the function to the DataFrame
df_merged2['DI_Category'] = df_merged2.apply(classify_decoupling, axis=1)

In [87]:
df_merged2

,Name_of_Regions_x_2010,Citycode,Year_2010,UER_2010,UI_2010,C_2010,T_2010,D_2010,UI_normalized_2010,UER_normalized_2010,...,D_2014,UI_normalized_2014,UER_normalized_2014,C2_2014,T2_2014,D2_2014,Delta_UER,Delta_UI,DI,DI_Category
0,北京,110000,2010,0.168303,0.206704,0.994743,0.187503,0.431877,0.200826,0.839766,...,0.417536,0.176834,0.747975,0.786510,0.462404,0.603064,-0.041066,-0.088940,0.461723,Weak negative decoupling / Negative decoupling
1,天津,120000,2010,0.152355,0.197102,0.991768,0.174729,0.416281,0.190941,0.760175,...,0.404527,0.180092,0.627424,0.832543,0.403758,0.579781,-0.082297,-0.028283,2.909822,Recession decoupling / Decoupling
2,石家庄,130100,2010,0.174103,0.079555,0.927936,0.126829,0.343059,0.069926,0.868715,...,0.320992,0.058646,0.670748,0.543834,0.364697,0.445348,-0.152398,-0.095698,1.592491,Recession decoupling / Decoupling
3,唐山,130200,2010,0.173093,0.076014,0.920939,0.124553,0.338683,0.066281,0.863673,...,0.308370,0.054927,0.586162,0.559776,0.320544,0.423595,-0.234908,-0.101744,2.308817,Recession decoupling / Decoupling
4,秦皇岛,130300,2010,0.183608,0.064805,0.878226,0.124207,0.330275,0.054742,0.916151,...,0.305010,0.037150,0.798608,0.412190,0.417879,0.415025,-0.071647,-0.216492,0.330947,Weak negative decoupling / Negative decoupling
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,固原,640400,2010,0.149317,0.017109,0.607403,0.083213,0.224820,0.005639,0.745015,...,0.232960,0.010203,0.525083,0.273476,0.267643,0.270544,-0.186291,0.416829,-0.446924,Strong decoupling / Decoupling
285,中卫,640500,2010,0.095024,0.023502,0.797418,0.059263,0.217388,0.012220,0.474050,...,0.231371,0.009330,0.531041,0.260518,0.270185,0.265308,0.289854,-0.005151,-56.270582,Strong negative decoupling / Negative decoupling
286,新疆,650000,2010,0.134498,0.027310,0.749113,0.080904,0.246183,0.016140,0.671055,...,0.217763,0.004985,0.503949,0.196959,0.254467,0.223874,-0.124755,-0.300527,0.415121,Weak negative decoupling / Negative decoupling
287,乌鲁木齐,650100,2010,0.137691,0.103063,0.989602,0.120377,0.345146,0.094128,0.686991,...,0.314375,0.059119,0.599945,0.571505,0.329532,0.433969,-0.020280,-0.297449,0.068180,Weak negative decoupling / Negative decoupling
288,克拉玛依,650200,2010,0.156935,0.072887,0.930728,0.114911,0.327034,0.063062,0.783035,...,0.279393,0.028282,0.656017,0.398104,0.342149,0.369068,-0.076475,-0.423174,0.180718,Weak negative decoupling / Negative decoupling

In [88]:
df_merged2['Citycode'] = df_merged2['Citycode'].astype('object')

In [89]:
df_merged2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 289 entries, 0 to 288
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name_of_Regions_x_2010  289 non-null    object
 1   Citycode                289 non-null    object
 2   Year_2010               289 non-null    int64
 3   UER_2010                289 non-null    float64
 4   UI_2010                 289 non-null    float64
 5   C_2010                  289 non-null    float64
 6   T_2010                  289 non-null    float64
 7   D_2010                  289 non-null    float64
 8   UI_normalized_2010      289 non-null    float64
 9   UER_normalized_2010     289 non-null    float64
 10  C2_2010                 289 non-null    float64
 11  T2_2010                 289 non-null    float64
 12  D2_2010                 289 non-null    float64
 13  Name_of_Regions_x_2014  289 non-null    object
 14  Year_2014               289 non-null    int64
 15  UER_2014                289 non-null    float64
 16  UI_2014                 289 non-null    float64
 17  C_2014                  289 non-null    float64
 18  T_2014                  289 non-null    float64
 19  D_2014                  289 non-null    float64
 20  UI_normalized_2014      289 non-null    float64
 21  UER_normalized_2014     289 non-null    float64
 22  C2_2014                 289 non-null    float64
 23  T2_2014                 289 non-null    float64
 24  D2_2014                 289 non-null    float64
 25  Delta_UER               289 non-null    float64
 26  Delta_UI                289 non-null    float64
 27  DI                      289 non-null    float64
 28  DI_Category             289 non-null    object
dtypes: float64(23), int64(2), object(4)
memory usage: 65.6+ KB

In [90]:
# 读取shapefile
shapefile_path = 'data/Chinamap_2019/Merged_Municipalities.shp'
gdf = gpd.read_file(shapefile_path)

In [91]:
gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 317 entries, 0 to 316
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Prvnc_c   317 non-null    float64
 1   City_cd   317 non-null    object
 2   Area      317 non-null    object
 3   Name      286 non-null    object
 4   geometry  317 non-null    geometry
dtypes: float64(1), geometry(1), object(3)
memory usage: 12.5+ KB

In [92]:
df_merged2['Citycode'] = df_merged2['Citycode'].astype(float)
gdf['City_cd'] = gdf['City_cd'].astype(float)

In [93]:
# 根据Citycode和市代码进行连接，保留不匹配的行
data_merged3 = gdf.merge(df_merged2, left_on='City_cd', right_on='Citycode', how='outer')

In [94]:
data_merged3.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 323 entries, 0 to 322
Data columns (total 34 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Prvnc_c                 317 non-null    float64
 1   City_cd                 317 non-null    float64
 2   Area                    317 non-null    object
 3   Name                    286 non-null    object
 4   geometry                317 non-null    geometry
 5   Name_of_Regions_x_2010  289 non-null    object
 6   Citycode                289 non-null    float64
 7   Year_2010               289 non-null    float64
 8   UER_2010                289 non-null    float64
 9   UI_2010                 289 non-null    float64
 10  C_2010                  289 non-null    float64
 11  T_2010                  289 non-null    float64
 12  D_2010                  289 non-null    float64
 13  UI_normalized_2010      289 non-null    float64
 14  UER_normalized_2010     289 non-null    float64
 15  C2_2010                 289 non-null    float64
 16  T2_2010                 289 non-null    float64
 17  D2_2010                 289 non-null    float64
 18  Name_of_Regions_x_2014  289 non-null    object
 19  Year_2014               289 non-null    float64
 20  UER_2014                289 non-null    float64
 21  UI_2014                 289 non-null    float64
 22  C_2014                  289 non-null    float64
 23  T_2014                  289 non-null    float64
 24  D_2014                  289 non-null    float64
 25  UI_normalized_2014      289 non-null    float64
 26  UER_normalized_2014     289 non-null    float64
 27  C2_2014                 289 non-null    float64
 28  T2_2014                 289 non-null    float64
 29  D2_2014                 289 non-null    float64
 30  Delta_UER               289 non-null    float64
 31  Delta_UI                289 non-null    float64
 32  DI                      289 non-null    float64
 33  DI_Category             289 non-null    object
dtypes: float64(28), geometry(1), object(5)
memory usage: 85.9+ KB

In [95]:
# 查找 Name_of_Regions_x_2010 有值但是 Name 列无值的行
rows_with_value_in_Regions_but_not_in_Name = data_merged3[(data_merged3['Name_of_Regions_x_2010'].notna()) & (data_merged3['Name'].isna())]

# 输出符合条件的行
print(rows_with_value_in_Regions_but_not_in_Name)

     Prvnc_c  City_cd Area Name geometry Name_of_Regions_x_2010  Citycode  \
317      NaN      NaN  NaN  NaN     None                     海口  460100.0
318      NaN      NaN  NaN  NaN     None                     三亚  460200.0
319      NaN      NaN  NaN  NaN     None                     拉萨  540100.0
320      NaN      NaN  NaN  NaN     None                     西宁  630100.0
321      NaN      NaN  NaN  NaN     None                   乌鲁木齐  650100.0
322      NaN      NaN  NaN  NaN     None                   克拉玛依  650200.0

     Year_2010  UER_2010   UI_2010  ...    D_2014  UI_normalized_2014  \
317     2010.0  0.167011  0.139612  ...  0.394054            0.149479
318     2010.0  0.191014  0.068079  ...  0.315056            0.047638
319     2010.0  0.022578  0.033119  ...  0.216202            0.010889
320     2010.0  0.139611  0.065114  ...  0.284436            0.034474
321     2010.0  0.137691  0.103063  ...  0.314375            0.059119
322     2010.0  0.156935  0.072887  ...  0.279393            0.028282

     UER_normalized_2014   C2_2014   T2_2014   D2_2014  Delta_UER  Delta_UI  \
317             0.681001  0.768360  0.415240  0.564848  -0.105417  0.155945
318             0.747170  0.474737  0.397404  0.434353  -0.155835 -0.102481
319             0.336163  0.348663  0.173526  0.245972   2.883833 -0.247677
320             0.605910  0.451376  0.320192  0.380167  -0.026108 -0.260686
321             0.599945  0.571505  0.329532  0.433969  -0.020280 -0.297449
322             0.656017  0.398104  0.342149  0.369068  -0.076475 -0.423174

            DI                                       DI_Category
317  -0.675990                    Strong decoupling / Decoupling
318   1.520628                 Recession decoupling / Decoupling
319 -11.643518  Strong negative decoupling / Negative decoupling
320   0.100150    Weak negative decoupling / Negative decoupling
321   0.068180    Weak negative decoupling / Negative decoupling
322   0.180718    Weak negative decoupling / Negative decoupling

[6 rows x 34 columns]

In [96]:
# 删除 geometry 列为空值的行
data_merged3 = data_merged3.dropna(subset=['geometry'])

In [97]:
# 查找 geometry 列为空值的行
rows_with_nan_in_geometry = data_merged3[data_merged3['geometry'].isna()]

# 输出包含 geometry 列为空值的行
print(rows_with_nan_in_geometry)

Empty GeoDataFrame
Columns: [Prvnc_c, City_cd, Area, Name, geometry, Name_of_Regions_x_2010, Citycode, Year_2010, UER_2010, UI_2010, C_2010, T_2010, D_2010, UI_normalized_2010, UER_normalized_2010, C2_2010, T2_2010, D2_2010, Name_of_Regions_x_2014, Year_2014, UER_2014, UI_2014, C_2014, T_2014, D_2014, UI_normalized_2014, UER_normalized_2014, C2_2014, T2_2014, D2_2014, Delta_UER, Delta_UI, DI, DI_Category]
Index: []

[0 rows x 34 columns]

In [98]:
# 修改列名称“省代码”为“province”
data_merged3 = data_merged3.rename(columns={'省代码': 'Provincecode'})
# 修改列名称“省代码”为“province”
data_merged3 = data_merged3.rename(columns={'省': 'Province'})
# 修改列名称“省代码”为“province”
data_merged3 = data_merged3.rename(columns={'市代码': 'Citycode1'})
data_merged3 = data_merged3.rename(columns={'市': 'City'})
data_merged3 = data_merged3.rename(columns={'类型': 'Type'})

In [99]:
# 将data_merged导出为新的shapefile
output_shapefile_path = 'data/Chinamap_2019/CouplingValue_20102014.shp'
data_merged3.to_file(output_shapefile_path, driver='ESRI Shapefile')

/tmp/ipykernel_30452/1465442449.py:3: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  data_merged3.to_file(output_shapefile_path, driver='ESRI Shapefile')