In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt

In [2]:
file_path = 'data/2018_UI_UER.xlsx'
df = pd.read_excel(file_path)

In [3]:
df

,Name_of_Regions,Unnamed: 1,Year,Unnamed: 3,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,Road_Surface_Area_Per_Capita_m2,Unnamed: 8,Population_urbanization,...,Unnamed: 22,Industrial_fume_emissions_(tonnes),城市,Comprehensive_industrial_solid_waste_utilisation_rate(%),Rate_of_non_hazardous_treatment_of_domestic_waste(%),CITY,Greening_coverage_in_builtup_areas,Unnamed: 29,Parkland_per_capita,NameofCities
0,北京,Beijing,2018,北京,1863.40,NaN,1469.05,7.57,北京市,0.8650,...,北京,15343.0,北京市,68.93,99.94,北京市,48.44,北京市,16.30,北京
1,天津,Tianjin,2018,天津,1296.81,NaN,1077.83,11.67,天津市,0.8315,...,天津,34837.0,天津市,98.90,98.37,天津市,38.03,天津市,9.38,天津
2,河北,Hebei,2018,河北,1741.28,161.43,2162.73,19.76,NaN,NaN,...,NaN,NaN,河北省,NaN,NaN,NaN,NaN,NaN,14.23,河北
3,石家庄,Shijiazhuang,2018,石家庄,281.16,3.15,309.12,21.77,石家庄市,0.6316,...,石家庄,27420.0,石家庄市,84.00,100.00,石家庄市,41.16,石家庄市,16.35,石家庄
4,唐山,Tangshan,2018,唐山,193.99,10.18,249.00,18.02,唐山市,0.6314,...,唐山,227824.0,唐山市,74.41,100.00,唐山市,41.51,唐山市,15.54,唐山
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,固原,Guyuan,2018,固原,17.65,10.33,44.10,28.65,固原市,0.3793,...,固原,1334.0,固原市,77.19,87.95,固原市,36.45,固原市,25.55,固原
315,中卫,Zhongwei,2018,中卫,17.24,0.94,32.00,31.68,NaN,0.4441,...,中卫,25261.0,中卫市,34.50,96.54,中卫市,40.10,中卫市,24.14,中卫
316,新疆,xinjiang,2018,新疆,590.33,167.23,1312.24,20.34,NaN,0.5091,...,NaN,462546.0,新疆维吾尔自治区,50.10,91.40,NaN,39.60,NaN,14.31,新疆
317,乌鲁木齐,Urumuchi,2018,乌鲁木齐,216.98,69.49,458.36,11.76,乌鲁木齐市,0.9015,...,乌鲁木齐,29183.0,乌鲁木齐市,84.94,99.97,乌鲁木齐市,41.90,乌鲁木齐市,12.70,乌鲁木齐
318,克拉玛依,Kelamayi,2018,克拉玛依,30.49,14.76,75.78,27.38,NaN,0.6855,...,克拉玛依,2365.0,克拉玛依市,95.93,100.00,克拉玛依市,43.29,克拉玛依市,11.07,克拉玛依

In [4]:
# 去除指定列中包含NaN值的行
columns_to_check = [ 
    'Population_urbanization', 
    'First_sector_of_GDP', 
    'GDP', 
    'Citycode', 
    'Area_of_administrative_districts'
]
df_cleaned = df.dropna(subset=columns_to_check)

In [5]:
df_cleaned

,Name_of_Regions,Unnamed: 1,Year,Unnamed: 3,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,Road_Surface_Area_Per_Capita_m2,Unnamed: 8,Population_urbanization,...,Unnamed: 22,Industrial_fume_emissions_(tonnes),城市,Comprehensive_industrial_solid_waste_utilisation_rate(%),Rate_of_non_hazardous_treatment_of_domestic_waste(%),CITY,Greening_coverage_in_builtup_areas,Unnamed: 29,Parkland_per_capita,NameofCities
0,北京,Beijing,2018,北京,1863.40,NaN,1469.05,7.57,北京市,0.8650,...,北京,15343.0,北京市,68.93,99.94,北京市,48.44,北京市,16.30,北京
1,天津,Tianjin,2018,天津,1296.81,NaN,1077.83,11.67,天津市,0.8315,...,天津,34837.0,天津市,98.90,98.37,天津市,38.03,天津市,9.38,天津
3,石家庄,Shijiazhuang,2018,石家庄,281.16,3.15,309.12,21.77,石家庄市,0.6316,...,石家庄,27420.0,石家庄市,84.00,100.00,石家庄市,41.16,石家庄市,16.35,石家庄
4,唐山,Tangshan,2018,唐山,193.99,10.18,249.00,18.02,唐山市,0.6314,...,唐山,227824.0,唐山市,74.41,100.00,唐山市,41.51,唐山市,15.54,唐山
5,秦皇岛,Qinhuangdao,2018,秦皇岛,100.90,32.96,138.43,17.74,秦皇岛市,0.5942,...,秦皇岛,19289.0,秦皇岛市,77.46,100.00,秦皇岛市,41.29,秦皇岛市,17.89,秦皇岛
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,固原,Guyuan,2018,固原,17.65,10.33,44.10,28.65,固原市,0.3793,...,固原,1334.0,固原市,77.19,87.95,固原市,36.45,固原市,25.55,固原
315,中卫,Zhongwei,2018,中卫,17.24,0.94,32.00,31.68,NaN,0.4441,...,中卫,25261.0,中卫市,34.50,96.54,中卫市,40.10,中卫市,24.14,中卫
316,新疆,xinjiang,2018,新疆,590.33,167.23,1312.24,20.34,NaN,0.5091,...,NaN,462546.0,新疆维吾尔自治区,50.10,91.40,NaN,39.60,NaN,14.31,新疆
317,乌鲁木齐,Urumuchi,2018,乌鲁木齐,216.98,69.49,458.36,11.76,乌鲁木齐市,0.9015,...,乌鲁木齐,29183.0,乌鲁木齐市,84.94,99.97,乌鲁木齐市,41.90,乌鲁木齐市,12.70,乌鲁木齐
318,克拉玛依,Kelamayi,2018,克拉玛依,30.49,14.76,75.78,27.38,NaN,0.6855,...,克拉玛依,2365.0,克拉玛依市,95.93,100.00,克拉玛依市,43.29,克拉玛依市,11.07,克拉玛依

In [6]:
# 指定需要检查NaN值的列
columns_to_check = [
    'UrbanPopulation',
    'UrbanTemporaryPopulation', 
    'Population_urbanization', 
    'First_sector_of_GDP', 
    'GDP', 
    'Citycode', 
    'Area_of_administrative_districts',
    'Road_Surface_Area_Per_Capita_m2',
    'Surface_Area_of_Built_District'
]

# 将这些列转换为数值类型，处理非数值内容
for column in columns_to_check:
    df_cleaned[column] = pd.to_numeric(df_cleaned[column], errors='coerce')

/tmp/ipykernel_5364/1195776530.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = pd.to_numeric(df_cleaned[column], errors='coerce')

In [7]:
df_cleaned['UrbanTemporaryPopulation'] = df_cleaned['UrbanTemporaryPopulation'].fillna(0)

/tmp/ipykernel_5364/1004577029.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['UrbanTemporaryPopulation'] = df_cleaned['UrbanTemporaryPopulation'].fillna(0)

In [8]:
df_cleaned['PUI'] = (df_cleaned['Population_urbanization'])

/tmp/ipykernel_5364/629985429.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['PUI'] = (df_cleaned['Population_urbanization'])

In [9]:
df_cleaned

,Name_of_Regions,Unnamed: 1,Year,Unnamed: 3,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,Road_Surface_Area_Per_Capita_m2,Unnamed: 8,Population_urbanization,...,Industrial_fume_emissions_(tonnes),城市,Comprehensive_industrial_solid_waste_utilisation_rate(%),Rate_of_non_hazardous_treatment_of_domestic_waste(%),CITY,Greening_coverage_in_builtup_areas,Unnamed: 29,Parkland_per_capita,NameofCities,PUI
0,北京,Beijing,2018,北京,1863.40,0.00,1469.05,7.57,北京市,0.8650,...,15343.0,北京市,68.93,99.94,北京市,48.44,北京市,16.30,北京,0.8650
1,天津,Tianjin,2018,天津,1296.81,0.00,1077.83,11.67,天津市,0.8315,...,34837.0,天津市,98.90,98.37,天津市,38.03,天津市,9.38,天津,0.8315
3,石家庄,Shijiazhuang,2018,石家庄,281.16,3.15,309.12,21.77,石家庄市,0.6316,...,27420.0,石家庄市,84.00,100.00,石家庄市,41.16,石家庄市,16.35,石家庄,0.6316
4,唐山,Tangshan,2018,唐山,193.99,10.18,249.00,18.02,唐山市,0.6314,...,227824.0,唐山市,74.41,100.00,唐山市,41.51,唐山市,15.54,唐山,0.6314
5,秦皇岛,Qinhuangdao,2018,秦皇岛,100.90,32.96,138.43,17.74,秦皇岛市,0.5942,...,19289.0,秦皇岛市,77.46,100.00,秦皇岛市,41.29,秦皇岛市,17.89,秦皇岛,0.5942
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,固原,Guyuan,2018,固原,17.65,10.33,44.10,28.65,固原市,0.3793,...,1334.0,固原市,77.19,87.95,固原市,36.45,固原市,25.55,固原,0.3793
315,中卫,Zhongwei,2018,中卫,17.24,0.94,32.00,31.68,NaN,0.4441,...,25261.0,中卫市,34.50,96.54,中卫市,40.10,中卫市,24.14,中卫,0.4441
316,新疆,xinjiang,2018,新疆,590.33,167.23,1312.24,20.34,NaN,0.5091,...,462546.0,新疆维吾尔自治区,50.10,91.40,NaN,39.60,NaN,14.31,新疆,0.5091
317,乌鲁木齐,Urumuchi,2018,乌鲁木齐,216.98,69.49,458.36,11.76,乌鲁木齐市,0.9015,...,29183.0,乌鲁木齐市,84.94,99.97,乌鲁木齐市,41.90,乌鲁木齐市,12.70,乌鲁木齐,0.9015
318,克拉玛依,Kelamayi,2018,克拉玛依,30.49,14.76,75.78,27.38,NaN,0.6855,...,2365.0,克拉玛依市,95.93,100.00,克拉玛依市,43.29,克拉玛依市,11.07,克拉玛依,0.6855

In [10]:
df_cleaned['PUI'].describe()

count    291.000000
mean       0.579090
std        0.136596
min        0.220700
25%        0.491000
50%        0.559900
75%        0.665950
max        0.997500
Name: PUI, dtype: float64

In [11]:
# 查找 PUI 列中为空值的行
rows_with_nan_in_pui = df_cleaned[df_cleaned['PUI'].isna()]

# 输出包含 PUI 列为空值的行
print(rows_with_nan_in_pui)

Empty DataFrame
Columns: [Name_of_Regions, Unnamed: 1, Year, Unnamed: 3, UrbanPopulation, UrbanTemporaryPopulation, Surface_Area_of_Built_District, Road_Surface_Area_Per_Capita_m2, Unnamed: 8, Population_urbanization, Unnamed: 10, GDP, Unnamed: 12, First_sector_of_GDP, Unnamed: 14, Unnamed: 15, Citycode, Area_of_administrative_districts, Unnamed: 18, Industrial_wastewater_discharge_(tonnes), Unnamed: 20, Unnamed: 21, Unnamed: 22, Industrial_fume_emissions_(tonnes), 城市, Comprehensive_industrial_solid_waste_utilisation_rate(%), Rate_of_non_hazardous_treatment_of_domestic_waste(%), CITY, Greening_coverage_in_builtup_areas, Unnamed: 29, Parkland_per_capita, NameofCities, PUI]
Index: []

[0 rows x 33 columns]

In [12]:
df_cleaned['URI'] = (df_cleaned['Road_Surface_Area_Per_Capita_m2'] * ((df_cleaned['UrbanPopulation'] + df_cleaned['UrbanTemporaryPopulation'])* 10000) /1000000 ) / df_cleaned['Area_of_administrative_districts']

/tmp/ipykernel_5364/2660692400.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['URI'] = (df_cleaned['Road_Surface_Area_Per_Capita_m2'] * ((df_cleaned['UrbanPopulation'] + df_cleaned['UrbanTemporaryPopulation'])* 10000) /1000000 ) / df_cleaned['Area_of_administrative_districts']

In [13]:
df_cleaned['URI'].describe()

count    291.000000
mean       0.003104
std        0.006523
min        0.000011
25%        0.000504
50%        0.001258
75%        0.003484
max        0.061010
Name: URI, dtype: float64

In [14]:
df_cleaned['LUI'] = (df_cleaned['Surface_Area_of_Built_District']) / df_cleaned['Area_of_administrative_districts']

/tmp/ipykernel_5364/3353621859.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['LUI'] = (df_cleaned['Surface_Area_of_Built_District']) / df_cleaned['Area_of_administrative_districts']

In [15]:
df_cleaned['LUI'].describe()

count    291.000000
mean       0.020734
std        0.044566
min        0.000136
25%        0.003947
50%        0.008538
75%        0.022136
max        0.477591
Name: LUI, dtype: float64

In [16]:
df_cleaned['EUI'] = 1 - (df_cleaned['First_sector_of_GDP']) / 100

/tmp/ipykernel_5364/1051056126.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['EUI'] = 1 - (df_cleaned['First_sector_of_GDP']) / 100

In [17]:
df_cleaned['EUI'].describe()

count    291.000000
mean       0.890847
std        0.072524
min        0.558100
25%        0.849250
50%        0.900400
75%        0.945100
max        0.999100
Name: EUI, dtype: float64

In [18]:
df_cleaned['EAL'] = df_cleaned['GDP'] / df_cleaned['Area_of_administrative_districts']

/tmp/ipykernel_5364/3615482750.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['EAL'] = df_cleaned['GDP'] / df_cleaned['Area_of_administrative_districts']

In [19]:
df_cleaned['EAL'].describe()

count       291.000000
mean       3847.669403
std        8962.788140
min          12.292246
25%         711.089935
50%        1607.140923
75%        3608.943797
max      124662.774575
Name: EAL, dtype: float64

In [20]:
df_cleaned

,Name_of_Regions,Unnamed: 1,Year,Unnamed: 3,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,Road_Surface_Area_Per_Capita_m2,Unnamed: 8,Population_urbanization,...,CITY,Greening_coverage_in_builtup_areas,Unnamed: 29,Parkland_per_capita,NameofCities,PUI,URI,LUI,EUI,EAL
0,北京,Beijing,2018,北京,1863.40,0.00,1469.05,7.57,北京市,0.8650,...,北京市,48.44,北京市,16.30,北京,0.8650,0.008599,0.089549,0.9961,18482.157086
1,天津,Tianjin,2018,天津,1296.81,0.00,1077.83,11.67,天津市,0.8315,...,天津市,38.03,天津市,9.38,天津,0.8315,0.012692,0.090392,0.9908,15774.605837
3,石家庄,Shijiazhuang,2018,石家庄,281.16,3.15,309.12,21.77,石家庄市,0.6316,...,石家庄市,41.16,石家庄市,16.35,石家庄,0.6316,0.004403,0.021989,0.9309,4326.801821
4,唐山,Tangshan,2018,唐山,193.99,10.18,249.00,18.02,唐山市,0.6314,...,唐山市,41.51,唐山市,15.54,唐山,0.6314,0.002665,0.018033,0.9291,5036.913384
5,秦皇岛,Qinhuangdao,2018,秦皇岛,100.90,32.96,138.43,17.74,秦皇岛市,0.5942,...,秦皇岛市,41.29,秦皇岛市,17.89,秦皇岛,0.5942,0.003048,0.017766,0.8757,2099.028619
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,固原,Guyuan,2018,固原,17.65,10.33,44.10,28.65,固原市,0.3793,...,固原市,36.45,固原市,25.55,固原,0.3793,0.000762,0.004190,0.8093,288.098062
315,中卫,Zhongwei,2018,中卫,17.24,0.94,32.00,31.68,NaN,0.4441,...,中卫市,40.10,中卫市,24.14,中卫,0.4441,0.000422,0.002343,0.8568,295.039681
316,新疆,xinjiang,2018,新疆,590.33,167.23,1312.24,20.34,NaN,0.5091,...,NaN,39.60,NaN,14.31,新疆,0.5091,0.000094,0.000805,0.8610,74.814085
317,乌鲁木齐,Urumuchi,2018,乌鲁木齐,216.98,69.49,458.36,11.76,乌鲁木齐市,0.9015,...,乌鲁木齐市,41.90,乌鲁木齐市,12.70,乌鲁木齐,0.9015,0.002442,0.033231,0.9918,2247.347133
318,克拉玛依,Kelamayi,2018,克拉玛依,30.49,14.76,75.78,27.38,NaN,0.6855,...,克拉玛依市,43.29,克拉玛依市,11.07,克拉玛依,0.6855,0.001680,0.010277,0.9944,1217.984811

In [21]:
# 导入 land_use_intensity_by_city2006.csv 数据
df_land_use = pd.read_csv("data/land_use_intensity_by_city2018.csv", encoding='ISO-8859-1')
df_land_useProvince = pd.read_csv("data/land_use_intensity_by_province2018.csv", encoding='ISO-8859-1')
df_combined = pd.concat([df_land_use, df_land_useProvince], ignore_index=True)

In [22]:
df_combined

     Citycode  Provincecode        Province            City         LUL
0    110000.0      110000.0          ±±¾©ÊÐ          ±±¾©ÊÐ  267.981578
1    120000.0      120000.0          Ìì½òÊÐ          Ìì½òÊÐ  308.834991
2    130100.0      130000.0          ºÓ±±Ê¡        Ê¯¼Ò×¯ÊÐ  289.658663
3    130200.0      130000.0          ºÓ±±Ê¡          ÌÆÉ½ÊÐ  300.846836
4    130300.0      130000.0          ºÓ±±Ê¡        ÇØ»ÊµºÊÐ  266.745952
..        ...           ...             ...             ...         ...
369  820000.0      820000.0  °ÄÃÅÌØ±ðÐÐÕþÇø  °ÄÃÅÌØ±ðÐÐÕþÇø  206.124247
370  460000.0           NaN          hainan             NaN  233.877121
371  630000.0           NaN         qinghai             NaN  140.184778
372  650000.0           NaN        xinjiang             NaN   66.793529
373  540000.0           NaN          xizang             NaN  170.435257

[374 rows x 5 columns]

In [23]:
df_merged = df_cleaned.merge(df_combined[['Citycode', 'LUL']], on='Citycode', how='left')

In [24]:
df_merged

,Name_of_Regions,Unnamed: 1,Year,Unnamed: 3,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,Road_Surface_Area_Per_Capita_m2,Unnamed: 8,Population_urbanization,...,Greening_coverage_in_builtup_areas,Unnamed: 29,Parkland_per_capita,NameofCities,PUI,URI,LUI,EUI,EAL,LUL
0,北京,Beijing,2018,北京,1863.40,0.00,1469.05,7.57,北京市,0.8650,...,48.44,北京市,16.30,北京,0.8650,0.008599,0.089549,0.9961,18482.157086,267.981578
1,天津,Tianjin,2018,天津,1296.81,0.00,1077.83,11.67,天津市,0.8315,...,38.03,天津市,9.38,天津,0.8315,0.012692,0.090392,0.9908,15774.605837,308.834991
2,石家庄,Shijiazhuang,2018,石家庄,281.16,3.15,309.12,21.77,石家庄市,0.6316,...,41.16,石家庄市,16.35,石家庄,0.6316,0.004403,0.021989,0.9309,4326.801821,289.658663
3,唐山,Tangshan,2018,唐山,193.99,10.18,249.00,18.02,唐山市,0.6314,...,41.51,唐山市,15.54,唐山,0.6314,0.002665,0.018033,0.9291,5036.913384,300.846836
4,秦皇岛,Qinhuangdao,2018,秦皇岛,100.90,32.96,138.43,17.74,秦皇岛市,0.5942,...,41.29,秦皇岛市,17.89,秦皇岛,0.5942,0.003048,0.017766,0.8757,2099.028619,266.745952
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,固原,Guyuan,2018,固原,17.65,10.33,44.10,28.65,固原市,0.3793,...,36.45,固原市,25.55,固原,0.3793,0.000762,0.004190,0.8093,288.098062,237.684385
287,中卫,Zhongwei,2018,中卫,17.24,0.94,32.00,31.68,NaN,0.4441,...,40.10,中卫市,24.14,中卫,0.4441,0.000422,0.002343,0.8568,295.039681,211.193633
288,新疆,xinjiang,2018,新疆,590.33,167.23,1312.24,20.34,NaN,0.5091,...,39.60,NaN,14.31,新疆,0.5091,0.000094,0.000805,0.8610,74.814085,66.793529
289,乌鲁木齐,Urumuchi,2018,乌鲁木齐,216.98,69.49,458.36,11.76,乌鲁木齐市,0.9015,...,41.90,乌鲁木齐市,12.70,乌鲁木齐,0.9015,0.002442,0.033231,0.9918,2247.347133,135.718171
290,克拉玛依,Kelamayi,2018,克拉玛依,30.49,14.76,75.78,27.38,NaN,0.6855,...,43.29,克拉玛依市,11.07,克拉玛依,0.6855,0.001680,0.010277,0.9944,1217.984811,70.894451

In [25]:
df_merged['LUL'].describe()

count    291.000000
mean     253.412336
std       45.578063
min       32.649010
25%      227.978040
50%      249.297739
75%      289.657000
max      326.760754
Name: LUL, dtype: float64

In [26]:
# 指定需要检查 NaN 值的列
columns_to_check = ['URI', 'LUI', 'EUI', 'EAL', 'LUL']

# 查找这些列中包含 NaN 值的行
rows_with_nan = df_merged[df_merged[columns_to_check].isna().any(axis=1)]

# 输出包含 NaN 值的行
print(rows_with_nan)

Empty DataFrame
Columns: [Name_of_Regions, Unnamed: 1, Year, Unnamed: 3, UrbanPopulation, UrbanTemporaryPopulation, Surface_Area_of_Built_District, Road_Surface_Area_Per_Capita_m2, Unnamed: 8, Population_urbanization, Unnamed: 10, GDP, Unnamed: 12, First_sector_of_GDP, Unnamed: 14, Unnamed: 15, Citycode, Area_of_administrative_districts, Unnamed: 18, Industrial_wastewater_discharge_(tonnes), Unnamed: 20, Unnamed: 21, Unnamed: 22, Industrial_fume_emissions_(tonnes), 城市, Comprehensive_industrial_solid_waste_utilisation_rate(%), Rate_of_non_hazardous_treatment_of_domestic_waste(%), CITY, Greening_coverage_in_builtup_areas, Unnamed: 29, Parkland_per_capita, NameofCities, PUI, URI, LUI, EUI, EAL, LUL]
Index: []

[0 rows x 38 columns]

In [27]:
# 指定需要检查NaN值的列
columns_to_check1 = ['URI', 'LUI', 'EUI', 'EAL','LUL']

# 去除这些列中包含NaN值的行
data_merged = df_merged.dropna(subset=columns_to_check1)

In [28]:
data_merged

,Name_of_Regions,Unnamed: 1,Year,Unnamed: 3,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,Road_Surface_Area_Per_Capita_m2,Unnamed: 8,Population_urbanization,...,Greening_coverage_in_builtup_areas,Unnamed: 29,Parkland_per_capita,NameofCities,PUI,URI,LUI,EUI,EAL,LUL
0,北京,Beijing,2018,北京,1863.40,0.00,1469.05,7.57,北京市,0.8650,...,48.44,北京市,16.30,北京,0.8650,0.008599,0.089549,0.9961,18482.157086,267.981578
1,天津,Tianjin,2018,天津,1296.81,0.00,1077.83,11.67,天津市,0.8315,...,38.03,天津市,9.38,天津,0.8315,0.012692,0.090392,0.9908,15774.605837,308.834991
2,石家庄,Shijiazhuang,2018,石家庄,281.16,3.15,309.12,21.77,石家庄市,0.6316,...,41.16,石家庄市,16.35,石家庄,0.6316,0.004403,0.021989,0.9309,4326.801821,289.658663
3,唐山,Tangshan,2018,唐山,193.99,10.18,249.00,18.02,唐山市,0.6314,...,41.51,唐山市,15.54,唐山,0.6314,0.002665,0.018033,0.9291,5036.913384,300.846836
4,秦皇岛,Qinhuangdao,2018,秦皇岛,100.90,32.96,138.43,17.74,秦皇岛市,0.5942,...,41.29,秦皇岛市,17.89,秦皇岛,0.5942,0.003048,0.017766,0.8757,2099.028619,266.745952
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,固原,Guyuan,2018,固原,17.65,10.33,44.10,28.65,固原市,0.3793,...,36.45,固原市,25.55,固原,0.3793,0.000762,0.004190,0.8093,288.098062,237.684385
287,中卫,Zhongwei,2018,中卫,17.24,0.94,32.00,31.68,NaN,0.4441,...,40.10,中卫市,24.14,中卫,0.4441,0.000422,0.002343,0.8568,295.039681,211.193633
288,新疆,xinjiang,2018,新疆,590.33,167.23,1312.24,20.34,NaN,0.5091,...,39.60,NaN,14.31,新疆,0.5091,0.000094,0.000805,0.8610,74.814085,66.793529
289,乌鲁木齐,Urumuchi,2018,乌鲁木齐,216.98,69.49,458.36,11.76,乌鲁木齐市,0.9015,...,41.90,乌鲁木齐市,12.70,乌鲁木齐,0.9015,0.002442,0.033231,0.9918,2247.347133,135.718171
290,克拉玛依,Kelamayi,2018,克拉玛依,30.49,14.76,75.78,27.38,NaN,0.6855,...,43.29,克拉玛依市,11.07,克拉玛依,0.6855,0.001680,0.010277,0.9944,1217.984811,70.894451

In [31]:
# 保留所需的列
columns_to_keep = ['Name_of_Regions', 'Year', 'Citycode', 'PUI', 'URI', 'LUI', 'EUI', 'EAL', 'LUL']
ui_index_2018 = data_merged[columns_to_keep]

# 导出为 CSV 文件
ui_index_2018.to_csv('data/UI_index_2018.csv', index=False)

In [32]:
# 将指定列的NaN值转换为0
columns_to_fill = [
    'Industrial_wastewater_discharge_(tonnes)', 
    'Industrial_fume_emissions_(tonnes)', 
    'Comprehensive_industrial_solid_waste_utilisation_rate(%)', 
    'Rate_of_non_hazardous_treatment_of_domestic_waste(%)', 
    'Greening_coverage_in_builtup_areas', 
    'Parkland_per_capita'
]

df_cleaned[columns_to_fill] = df_cleaned[columns_to_fill].fillna(0)

/tmp/ipykernel_5364/1106163433.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[columns_to_fill] = df_cleaned[columns_to_fill].fillna(0)

In [33]:
df_cleaned

,Name_of_Regions,Unnamed: 1,Year,Unnamed: 3,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,Road_Surface_Area_Per_Capita_m2,Unnamed: 8,Population_urbanization,...,CITY,Greening_coverage_in_builtup_areas,Unnamed: 29,Parkland_per_capita,NameofCities,PUI,URI,LUI,EUI,EAL
0,北京,Beijing,2018,北京,1863.40,0.00,1469.05,7.57,北京市,0.8650,...,北京市,48.44,北京市,16.30,北京,0.8650,0.008599,0.089549,0.9961,18482.157086
1,天津,Tianjin,2018,天津,1296.81,0.00,1077.83,11.67,天津市,0.8315,...,天津市,38.03,天津市,9.38,天津,0.8315,0.012692,0.090392,0.9908,15774.605837
3,石家庄,Shijiazhuang,2018,石家庄,281.16,3.15,309.12,21.77,石家庄市,0.6316,...,石家庄市,41.16,石家庄市,16.35,石家庄,0.6316,0.004403,0.021989,0.9309,4326.801821
4,唐山,Tangshan,2018,唐山,193.99,10.18,249.00,18.02,唐山市,0.6314,...,唐山市,41.51,唐山市,15.54,唐山,0.6314,0.002665,0.018033,0.9291,5036.913384
5,秦皇岛,Qinhuangdao,2018,秦皇岛,100.90,32.96,138.43,17.74,秦皇岛市,0.5942,...,秦皇岛市,41.29,秦皇岛市,17.89,秦皇岛,0.5942,0.003048,0.017766,0.8757,2099.028619
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,固原,Guyuan,2018,固原,17.65,10.33,44.10,28.65,固原市,0.3793,...,固原市,36.45,固原市,25.55,固原,0.3793,0.000762,0.004190,0.8093,288.098062
315,中卫,Zhongwei,2018,中卫,17.24,0.94,32.00,31.68,NaN,0.4441,...,中卫市,40.10,中卫市,24.14,中卫,0.4441,0.000422,0.002343,0.8568,295.039681
316,新疆,xinjiang,2018,新疆,590.33,167.23,1312.24,20.34,NaN,0.5091,...,NaN,39.60,NaN,14.31,新疆,0.5091,0.000094,0.000805,0.8610,74.814085
317,乌鲁木齐,Urumuchi,2018,乌鲁木齐,216.98,69.49,458.36,11.76,乌鲁木齐市,0.9015,...,乌鲁木齐市,41.90,乌鲁木齐市,12.70,乌鲁木齐,0.9015,0.002442,0.033231,0.9918,2247.347133
318,克拉玛依,Kelamayi,2018,克拉玛依,30.49,14.76,75.78,27.38,NaN,0.6855,...,克拉玛依市,43.29,克拉玛依市,11.07,克拉玛依,0.6855,0.001680,0.010277,0.9944,1217.984811

In [34]:
df_cleaned['Res1'] = df_cleaned['Industrial_wastewater_discharge_(tonnes)'] / df_cleaned['GDP']

/tmp/ipykernel_5364/2666823736.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Res1'] = df_cleaned['Industrial_wastewater_discharge_(tonnes)'] / df_cleaned['GDP']

In [35]:
df_cleaned['Res1'].describe()

count    291.000000
mean       0.000168
std        0.000184
min        0.000005
25%        0.000077
50%        0.000131
75%        0.000197
max        0.002376
Name: Res1, dtype: float64

In [36]:
df_cleaned['Res2'] = df_cleaned['Industrial_fume_emissions_(tonnes)'] / df_cleaned['GDP']

/tmp/ipykernel_5364/2575824147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Res2'] = df_cleaned['Industrial_fume_emissions_(tonnes)'] / df_cleaned['GDP']

In [37]:
df_cleaned['Res2'].describe()

count    291.000000
mean       0.001041
std        0.001674
min        0.000000
25%        0.000218
50%        0.000440
75%        0.001259
max        0.014386
Name: Res2, dtype: float64

In [38]:
df_cleaned['Ada1'] = df_cleaned['Comprehensive_industrial_solid_waste_utilisation_rate(%)'] 
df_cleaned['Ada1'].describe()

/tmp/ipykernel_5364/526319254.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Ada1'] = df_cleaned['Comprehensive_industrial_solid_waste_utilisation_rate(%)']

count    291.000000
mean      73.821433
std       25.509500
min        0.340000
25%       58.450000
50%       82.870000
75%       95.000000
max      100.000000
Name: Ada1, dtype: float64

In [39]:
# 查找 Ada1 列值大于 100 的行
rows_ada1_above_100 = df_cleaned[df_cleaned['Ada1'] > 100]
rows_ada1_above_100

Empty DataFrame
Columns: [Name_of_Regions, Unnamed: 1, Year, Unnamed: 3, UrbanPopulation, UrbanTemporaryPopulation, Surface_Area_of_Built_District, Road_Surface_Area_Per_Capita_m2, Unnamed: 8, Population_urbanization, Unnamed: 10, GDP, Unnamed: 12, First_sector_of_GDP, Unnamed: 14, Unnamed: 15, Citycode, Area_of_administrative_districts, Unnamed: 18, Industrial_wastewater_discharge_(tonnes), Unnamed: 20, Unnamed: 21, Unnamed: 22, Industrial_fume_emissions_(tonnes), 城市, Comprehensive_industrial_solid_waste_utilisation_rate(%), Rate_of_non_hazardous_treatment_of_domestic_waste(%), CITY, Greening_coverage_in_builtup_areas, Unnamed: 29, Parkland_per_capita, NameofCities, PUI, URI, LUI, EUI, EAL, Res1, Res2, Ada1]
Index: []

[0 rows x 40 columns]

In [40]:
df_cleaned['Ada2'] = df_cleaned['Rate_of_non_hazardous_treatment_of_domestic_waste(%)'] 
df_cleaned['Ada2'].describe()

/tmp/ipykernel_5364/2482281589.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Ada2'] = df_cleaned['Rate_of_non_hazardous_treatment_of_domestic_waste(%)']

count    291.000000
mean      98.206942
std        4.237227
min       68.690000
25%       98.850000
50%      100.000000
75%      100.000000
max      100.000000
Name: Ada2, dtype: float64

In [41]:
rows_ada2_above_100 = df_cleaned[df_cleaned['Ada2'] > 100]
rows_ada2_above_100

Empty DataFrame
Columns: [Name_of_Regions, Unnamed: 1, Year, Unnamed: 3, UrbanPopulation, UrbanTemporaryPopulation, Surface_Area_of_Built_District, Road_Surface_Area_Per_Capita_m2, Unnamed: 8, Population_urbanization, Unnamed: 10, GDP, Unnamed: 12, First_sector_of_GDP, Unnamed: 14, Unnamed: 15, Citycode, Area_of_administrative_districts, Unnamed: 18, Industrial_wastewater_discharge_(tonnes), Unnamed: 20, Unnamed: 21, Unnamed: 22, Industrial_fume_emissions_(tonnes), 城市, Comprehensive_industrial_solid_waste_utilisation_rate(%), Rate_of_non_hazardous_treatment_of_domestic_waste(%), CITY, Greening_coverage_in_builtup_areas, Unnamed: 29, Parkland_per_capita, NameofCities, PUI, URI, LUI, EUI, EAL, Res1, Res2, Ada1, Ada2]
Index: []

[0 rows x 41 columns]

In [42]:
df_cleaned['Rec1'] = df_cleaned['Greening_coverage_in_builtup_areas'] 
df_cleaned['Rec2'] = df_cleaned['Parkland_per_capita']

/tmp/ipykernel_5364/1792138184.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Rec1'] = df_cleaned['Greening_coverage_in_builtup_areas']
/tmp/ipykernel_5364/1792138184.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Rec2'] = df_cleaned['Parkland_per_capita']

In [43]:
df_cleaned['Rec1'].describe()

count    291.000000
mean      40.477457
std        6.702202
min        0.000000
25%       38.715000
50%       41.040000
75%       43.190000
max       93.810000
Name: Rec1, dtype: float64

In [44]:
rows_rec1_above_100 = df_cleaned[df_cleaned['Rec1'] > 100]
rows_rec1_above_100

Empty DataFrame
Columns: [Name_of_Regions, Unnamed: 1, Year, Unnamed: 3, UrbanPopulation, UrbanTemporaryPopulation, Surface_Area_of_Built_District, Road_Surface_Area_Per_Capita_m2, Unnamed: 8, Population_urbanization, Unnamed: 10, GDP, Unnamed: 12, First_sector_of_GDP, Unnamed: 14, Unnamed: 15, Citycode, Area_of_administrative_districts, Unnamed: 18, Industrial_wastewater_discharge_(tonnes), Unnamed: 20, Unnamed: 21, Unnamed: 22, Industrial_fume_emissions_(tonnes), 城市, Comprehensive_industrial_solid_waste_utilisation_rate(%), Rate_of_non_hazardous_treatment_of_domestic_waste(%), CITY, Greening_coverage_in_builtup_areas, Unnamed: 29, Parkland_per_capita, NameofCities, PUI, URI, LUI, EUI, EAL, Res1, Res2, Ada1, Ada2, Rec1, Rec2]
Index: []

[0 rows x 43 columns]

In [45]:
top_10_Rec1 = df_cleaned.nlargest(10, 'Rec1')
top_10_Rec1

,Name_of_Regions,Unnamed: 1,Year,Unnamed: 3,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,Road_Surface_Area_Per_Capita_m2,Unnamed: 8,Population_urbanization,...,URI,LUI,EUI,EAL,Res1,Res2,Ada1,Ada2,Rec1,Rec2
278,丽江,lijiang,2018,丽江,11.89,7.04,24.00,11.00,丽江市,0.4044,...,0.000101,0.001167,0.8496,170.621072,0.000056,0.001098,80.56,100.00,93.81,20.57
221,东莞,Dongguan,2018,东莞,231.58,453.45,1007.76,18.00,东莞市,0.9102,...,0.050329,0.411331,0.9970,33790.171429,0.000234,0.000243,66.32,100.00,53.59,24.06
130,景德镇,Jingdezhen,2018,景德镇,40.88,12.66,86.86,25.76,景德镇市,0.6694,...,0.002622,0.016510,0.9333,1609.196351,0.000321,0.000425,89.18,100.00,51.61,16.74
133,新余,Xinyu,2018,新余,47.60,0.93,80.00,24.32,新余市,0.7003,...,0.003736,0.025324,0.9460,3252.118708,0.000221,0.003371,84.75,100.00,51.00,19.28
135,赣州,Ganzhou,2018,赣州,139.55,39.45,180.25,17.40,赣州市,0.5029,...,0.000791,0.004579,0.8788,713.148359,0.000190,0.000839,86.41,100.00,49.84,13.05
41,本溪,Benxi,2018,本溪,81.64,4.46,109.00,12.64,本溪市,0.7083,...,0.001293,0.012955,0.9393,978.234728,0.000351,0.007586,46.20,100.00,49.76,11.44
208,珠海,Zhuhai,2018,珠海,84.08,193.90,141.31,13.06,珠海市,0.9008,...,0.022992,0.089493,0.9828,18459.373021,0.000147,0.000155,91.57,100.00,49.70,19.90
0,北京,Beijing,2018,北京,1863.40,0.00,1469.05,7.57,北京市,0.8650,...,0.008599,0.089549,0.9961,18482.157086,0.000028,0.000051,68.93,99.94,48.44,16.30
139,上饶,shangrao,2018,上饶,69.86,5.36,81.13,22.51,上饶市,0.5197,...,0.000744,0.003567,0.8859,974.971773,0.000271,0.001125,11.80,100.00,48.13,15.72
132,九江,Jiujiang,2018,九江,73.71,3.78,150.75,21.75,九江市,0.5527,...,0.000883,0.007900,0.9299,1414.968925,0.000335,0.001001,51.30,100.00,47.83,14.58

In [46]:
df_cleaned['Rec2'].describe()

count    291.000000
mean      14.513162
std        4.440609
min        5.460000
25%       11.935000
50%       13.850000
75%       15.885000
max       39.930000
Name: Rec2, dtype: float64

In [47]:
data_merged['Year'] = 2018

In [47]:
df_cleaned

,Name_of_Regions,Unnamed: 1,Year,Unnamed: 3,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,Road_Surface_Area_Per_Capita_m2,Unnamed: 8,Population_urbanization,...,URI,LUI,EUI,EAL,Res1,Res2,Ada1,Ada2,Rec1,Rec2
0,北京,Beijing,2018,北京,1863.40,0.00,1469.05,7.57,北京市,0.8650,...,0.008599,0.089549,0.9961,18482.157086,0.000028,0.000051,68.93,99.94,48.44,16.30
1,天津,Tianjin,2018,天津,1296.81,0.00,1077.83,11.67,天津市,0.8315,...,0.012692,0.090392,0.9908,15774.605837,0.000094,0.000185,98.90,98.37,38.03,9.38
3,石家庄,Shijiazhuang,2018,石家庄,281.16,3.15,309.12,21.77,石家庄市,0.6316,...,0.004403,0.021989,0.9309,4326.801821,0.000109,0.000451,84.00,100.00,41.16,16.35
4,唐山,Tangshan,2018,唐山,193.99,10.18,249.00,18.02,唐山市,0.6314,...,0.002665,0.018033,0.9291,5036.913384,0.000113,0.003276,74.41,100.00,41.51,15.54
5,秦皇岛,Qinhuangdao,2018,秦皇岛,100.90,32.96,138.43,17.74,秦皇岛市,0.5942,...,0.003048,0.017766,0.8757,2099.028619,0.000124,0.001179,77.46,100.00,41.29,17.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,固原,Guyuan,2018,固原,17.65,10.33,44.10,28.65,固原市,0.3793,...,0.000762,0.004190,0.8093,288.098062,0.000035,0.000440,77.19,87.95,36.45,25.55
315,中卫,Zhongwei,2018,中卫,17.24,0.94,32.00,31.68,NaN,0.4441,...,0.000422,0.002343,0.8568,295.039681,0.000362,0.006268,34.50,96.54,40.10,24.14
316,新疆,xinjiang,2018,新疆,590.33,167.23,1312.24,20.34,NaN,0.5091,...,0.000094,0.000805,0.8610,74.814085,0.000187,0.003792,50.10,91.40,39.60,14.31
317,乌鲁木齐,Urumuchi,2018,乌鲁木齐,216.98,69.49,458.36,11.76,乌鲁木齐市,0.9015,...,0.002442,0.033231,0.9918,2247.347133,0.000088,0.000941,84.94,99.97,41.90,12.70
318,克拉玛依,Kelamayi,2018,克拉玛依,30.49,14.76,75.78,27.38,NaN,0.6855,...,0.001680,0.010277,0.9944,1217.984811,0.000195,0.000263,95.93,100.00,43.29,11.07

In [49]:
columns_to_keep = ['Name_of_Regions','Citycode','Year','Res1','Res2','Ada1','Ada2','Rec1','Rec2']
uer_index_2018 = df_cleaned[columns_to_keep]
# 导出为 CSV 文件
uer_index_2018.to_csv('data/UER_index_2018.csv', index=False)

# 熵权法
# 标准化

In [50]:
# Initialize a column for the normalized values
data_merged['X1_star'] = pd.Series(dtype='float')
column_to_normalize = 'PUI'
# Iterate over each year to perform the normalization
for year in range(2018, 2019):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X1_max = year_data[column_to_normalize].max()
    X1_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X1_star'] = (year_data[column_to_normalize] - X1_min) / (X1_max - X1_min)

# Initialize a column for the normalized values
data_merged['X2_star'] = pd.Series(dtype='float')
column_to_normalize = 'URI'
# Iterate over each year to perform the normalization
for year in range(2018, 2019):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X2_max = year_data[column_to_normalize].max()
    X2_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X2_star'] = (year_data[column_to_normalize] - X2_min) / (X2_max - X2_min)

data_merged['X3_star'] = pd.Series(dtype='float')
column_to_normalize = 'LUI'
# Iterate over each year to perform the normalization
for year in range(2018, 2019):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X3_max = year_data[column_to_normalize].max()
    X3_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X3_star'] = (year_data[column_to_normalize] - X3_min) / (X3_max - X3_min)

data_merged['X4_star'] = pd.Series(dtype='float')
column_to_normalize = 'EUI'
# Iterate over each year to perform the normalization
for year in range(2018, 2019):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X4_max = year_data[column_to_normalize].max()
    X4_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X4_star'] = (year_data[column_to_normalize] - X4_min) / (X4_max - X4_min)

data_merged['X5_star'] = pd.Series(dtype='float')
column_to_normalize = 'EAL'
# Iterate over each year to perform the normalization
for year in range(2018, 2019):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X5_max = year_data[column_to_normalize].max()
    X5_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X5_star'] = (year_data[column_to_normalize] - X5_min) / (X5_max - X5_min)


data_merged['X6_star'] = pd.Series(dtype='float')
column_to_normalize = 'LUL'
# Iterate over each year to perform the normalization
for year in range(2018, 2019):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X6_max = year_data[column_to_normalize].max()
    X6_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X6_star'] = (year_data[column_to_normalize] - X6_min) / (X6_max - X6_min)

In [51]:
data_merged

,Name_of_Regions,Unnamed: 1,Year,Unnamed: 3,UrbanPopulation,UrbanTemporaryPopulation,Surface_Area_of_Built_District,Road_Surface_Area_Per_Capita_m2,Unnamed: 8,Population_urbanization,...,LUI,EUI,EAL,LUL,X1_star,X2_star,X3_star,X4_star,X5_star,X6_star
0,北京,Beijing,2018,北京,1863.40,0.00,1469.05,7.57,北京市,0.8650,...,0.089549,0.9961,18482.157086,267.981578,0.829428,0.140779,0.187269,0.993197,0.148173,0.800147
1,天津,Tianjin,2018,天津,1296.81,0.00,1077.83,11.67,天津市,0.8315,...,0.090392,0.9908,15774.605837,308.834991,0.786303,0.207884,0.189034,0.981179,0.126452,0.939051
2,石家庄,Shijiazhuang,2018,石家庄,281.16,3.15,309.12,21.77,石家庄市,0.6316,...,0.021989,0.9309,4326.801821,289.658663,0.528965,0.071994,0.045769,0.845351,0.034613,0.873850
3,唐山,Tangshan,2018,唐山,193.99,10.18,249.00,18.02,唐山市,0.6314,...,0.018033,0.9291,5036.913384,300.846836,0.528708,0.043497,0.037484,0.841270,0.040310,0.911891
4,秦皇岛,Qinhuangdao,2018,秦皇岛,100.90,32.96,138.43,17.74,秦皇岛市,0.5942,...,0.017766,0.8757,2099.028619,266.745952,0.480819,0.049777,0.036924,0.720181,0.016741,0.795946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,固原,Guyuan,2018,固原,17.65,10.33,44.10,28.65,固原市,0.3793,...,0.004190,0.8093,288.098062,237.684385,0.204171,0.012303,0.008491,0.569615,0.002213,0.697134
287,中卫,Zhongwei,2018,中卫,17.24,0.94,32.00,31.68,NaN,0.4441,...,0.002343,0.8568,295.039681,211.193633,0.287590,0.006728,0.004622,0.677324,0.002268,0.607064
288,新疆,xinjiang,2018,新疆,590.33,167.23,1312.24,20.34,NaN,0.5091,...,0.000805,0.8610,74.814085,66.793529,0.371267,0.001365,0.001400,0.686848,0.000502,0.116094
289,乌鲁木齐,Urumuchi,2018,乌鲁木齐,216.98,69.49,458.36,11.76,乌鲁木齐市,0.9015,...,0.033231,0.9918,2247.347133,135.718171,0.876416,0.039857,0.069316,0.983447,0.017931,0.350442
290,克拉玛依,Kelamayi,2018,克拉玛依,30.49,14.76,75.78,27.38,NaN,0.6855,...,0.010277,0.9944,1217.984811,70.894451,0.598352,0.027360,0.021239,0.989342,0.009673,0.130037

In [52]:
columns_to_keep = ['Name_of_Regions','Citycode','Year','X1_star','X2_star','X3_star','X4_star','X5_star','X6_star']
data_process_UI = data_merged[columns_to_keep]

In [53]:
data_process_UI

,Name_of_Regions,Citycode,Year,X1_star,X2_star,X3_star,X4_star,X5_star,X6_star
0,北京,110000.0,2018,0.829428,0.140779,0.187269,0.993197,0.148173,0.800147
1,天津,120000.0,2018,0.786303,0.207884,0.189034,0.981179,0.126452,0.939051
2,石家庄,130100.0,2018,0.528965,0.071994,0.045769,0.845351,0.034613,0.873850
3,唐山,130200.0,2018,0.528708,0.043497,0.037484,0.841270,0.040310,0.911891
4,秦皇岛,130300.0,2018,0.480819,0.049777,0.036924,0.720181,0.016741,0.795946
...,...,...,...,...,...,...,...,...,...
286,固原,640400.0,2018,0.204171,0.012303,0.008491,0.569615,0.002213,0.697134
287,中卫,640500.0,2018,0.287590,0.006728,0.004622,0.677324,0.002268,0.607064
288,新疆,650000.0,2018,0.371267,0.001365,0.001400,0.686848,0.000502,0.116094
289,乌鲁木齐,650100.0,2018,0.876416,0.039857,0.069316,0.983447,0.017931,0.350442
290,克拉玛依,650200.0,2018,0.598352,0.027360,0.021239,0.989342,0.009673,0.130037

In [54]:
#1.7熵权法

def calculate_entropy(indicator_data):
    # Replace zero values to avoid log(0) and negative infinity in entropy calculation
    indicator_data = indicator_data.replace(0, np.finfo(float).eps)  # Use a small number instead of zero
    p_ij = indicator_data / indicator_data.sum()  # Calculate the proportion p_ij
    K = 1 / np.log(291)  # Calculate the constant K
    e_j = -K * (p_ij * np.log(p_ij)).sum()  # Calculate the entropy e_j
    return e_j

# Initialize an empty list to store DataFrames for each year
dataframes_list = []

# Calculate entropies and weights for each year
for year in range(2018, 2019):
    year_data = data_process_UI[data_process_UI['Year'] == year].copy()
    entropies = year_data[['X1_star', 'X2_star', 'X3_star', 'X4_star','X5_star','X6_star']].apply(calculate_entropy, axis=0)
    weights = (1 - entropies) / (1 - entropies).sum()  # Calculate weights, ensuring they sum up to 1 within the year
    for i, indicator in enumerate(['X1_star', 'X2_star', 'X3_star', 'X4_star','X5_star','X6_star']):
        year_data[indicator + '_weighted'] = year_data[indicator] * weights.values[i]  # Apply weights to the indicators
    dataframes_list.append(year_data)  # Append the yearly data to the list

# Concatenate all DataFrames in the list to create the comprehensive_scores DataFrame
UI = pd.concat(dataframes_list, ignore_index=True)

# Now you should have the comprehensive_scores DataFrame with correctly calculated weights per year

In [55]:
UI

,Name_of_Regions,Citycode,Year,X1_star,X2_star,X3_star,X4_star,X5_star,X6_star,X1_star_weighted,X2_star_weighted,X3_star_weighted,X4_star_weighted,X5_star_weighted,X6_star_weighted
0,北京,110000.0,2018,0.829428,0.140779,0.187269,0.993197,0.148173,0.800147,0.021353,0.044613,0.058664,0.009708,0.048219,0.007122
1,天津,120000.0,2018,0.786303,0.207884,0.189034,0.981179,0.126452,0.939051,0.020242,0.065878,0.059217,0.009591,0.041151,0.008358
2,石家庄,130100.0,2018,0.528965,0.071994,0.045769,0.845351,0.034613,0.873850,0.013618,0.022815,0.014338,0.008263,0.011264,0.007778
3,唐山,130200.0,2018,0.528708,0.043497,0.037484,0.841270,0.040310,0.911891,0.013611,0.013784,0.011742,0.008223,0.013118,0.008116
4,秦皇岛,130300.0,2018,0.480819,0.049777,0.036924,0.720181,0.016741,0.795946,0.012378,0.015774,0.011567,0.007040,0.005448,0.007084
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,固原,640400.0,2018,0.204171,0.012303,0.008491,0.569615,0.002213,0.697134,0.005256,0.003899,0.002660,0.005568,0.000720,0.006205
287,中卫,640500.0,2018,0.287590,0.006728,0.004622,0.677324,0.002268,0.607064,0.007404,0.002132,0.001448,0.006621,0.000738,0.005403
288,新疆,650000.0,2018,0.371267,0.001365,0.001400,0.686848,0.000502,0.116094,0.009558,0.000433,0.000439,0.006714,0.000163,0.001033
289,乌鲁木齐,650100.0,2018,0.876416,0.039857,0.069316,0.983447,0.017931,0.350442,0.022562,0.012631,0.021714,0.009613,0.005835,0.003119
290,克拉玛依,650200.0,2018,0.598352,0.027360,0.021239,0.989342,0.009673,0.130037,0.015404,0.008670,0.006653,0.009671,0.003148,0.001157

In [56]:
# Calculate the combined weighted values for Resistance, Adaptability, and Recovery
UI['PU'] = UI['X1_star_weighted'] + UI['X2_star_weighted']
UI['LU'] = UI['X3_star_weighted'] + UI['X6_star_weighted']
#comprehensive_scores['ADA'] = comprehensive_scores['X2_star_weighted'] 
UI['EU'] = UI['X4_star_weighted'] + UI['X5_star_weighted']

# Assuming data_merged is the DataFrame with the standardized 'RES', 'ADA', and 'REC' columns.

# Define a small positive value to add to REC to avoid zero values
small_positive_value = 1e-6

# Replace zero values in REC with the small positive value
UI['PU_adj'] = UI['PU'].replace(0, small_positive_value)
UI['LU_adj'] = UI['LU'].replace(0, small_positive_value)
UI['EU_adj'] = UI['EU'].replace(0, small_positive_value)

# Now, the UER values should not be zero due to REC being zero, since we have adjusted REC values slightly above zero.

# Calculate the Urban Ecological Resilience (UER) for each borough and year
UI['UI'] = UI['PU_adj'] + UI['LU_adj'] + UI['EU_adj']

# Check the result
UI[['Year', 'Name_of_Regions', 'PU', 'LU', 'EU', 'UI']].head()

   Year Name_of_Regions        PU        LU        EU        UI
0  2018              北京  0.065965  0.065786  0.057927  0.189678
1  2018              天津  0.086120  0.067575  0.050741  0.204437
2  2018             石家庄  0.036432  0.022115  0.019527  0.078075
3  2018              唐山  0.027395  0.019858  0.021341  0.068595
4  2018             秦皇岛  0.028152  0.018651  0.012487  0.059291

In [57]:
UI

,Name_of_Regions,Citycode,Year,X1_star,X2_star,X3_star,X4_star,X5_star,X6_star,X1_star_weighted,...,X4_star_weighted,X5_star_weighted,X6_star_weighted,PU,LU,EU,PU_adj,LU_adj,EU_adj,UI
0,北京,110000.0,2018,0.829428,0.140779,0.187269,0.993197,0.148173,0.800147,0.021353,...,0.009708,0.048219,0.007122,0.065965,0.065786,0.057927,0.065965,0.065786,0.057927,0.189678
1,天津,120000.0,2018,0.786303,0.207884,0.189034,0.981179,0.126452,0.939051,0.020242,...,0.009591,0.041151,0.008358,0.086120,0.067575,0.050741,0.086120,0.067575,0.050741,0.204437
2,石家庄,130100.0,2018,0.528965,0.071994,0.045769,0.845351,0.034613,0.873850,0.013618,...,0.008263,0.011264,0.007778,0.036432,0.022115,0.019527,0.036432,0.022115,0.019527,0.078075
3,唐山,130200.0,2018,0.528708,0.043497,0.037484,0.841270,0.040310,0.911891,0.013611,...,0.008223,0.013118,0.008116,0.027395,0.019858,0.021341,0.027395,0.019858,0.021341,0.068595
4,秦皇岛,130300.0,2018,0.480819,0.049777,0.036924,0.720181,0.016741,0.795946,0.012378,...,0.007040,0.005448,0.007084,0.028152,0.018651,0.012487,0.028152,0.018651,0.012487,0.059291
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,固原,640400.0,2018,0.204171,0.012303,0.008491,0.569615,0.002213,0.697134,0.005256,...,0.005568,0.000720,0.006205,0.009155,0.008865,0.006288,0.009155,0.008865,0.006288,0.024308
287,中卫,640500.0,2018,0.287590,0.006728,0.004622,0.677324,0.002268,0.607064,0.007404,...,0.006621,0.000738,0.005403,0.009536,0.006851,0.007359,0.009536,0.006851,0.007359,0.023746
288,新疆,650000.0,2018,0.371267,0.001365,0.001400,0.686848,0.000502,0.116094,0.009558,...,0.006714,0.000163,0.001033,0.009990,0.001472,0.006877,0.009990,0.001472,0.006877,0.018339
289,乌鲁木齐,650100.0,2018,0.876416,0.039857,0.069316,0.983447,0.017931,0.350442,0.022562,...,0.009613,0.005835,0.003119,0.035193,0.024833,0.015448,0.035193,0.024833,0.015448,0.075474
290,克拉玛依,650200.0,2018,0.598352,0.027360,0.021239,0.989342,0.009673,0.130037,0.015404,...,0.009671,0.003148,0.001157,0.024074,0.007811,0.012818,0.024074,0.007811,0.012818,0.044703

In [58]:
columns_to_keep = ['Name_of_Regions','Citycode','Year','Res1','Res2','Ada1','Ada2','Rec1','Rec2']
data_merged = df_cleaned[columns_to_keep]

In [59]:
data_merged

,Name_of_Regions,Citycode,Year,Res1,Res2,Ada1,Ada2,Rec1,Rec2
0,北京,110000.0,2018,0.000028,0.000051,68.93,99.94,48.44,16.30
1,天津,120000.0,2018,0.000094,0.000185,98.90,98.37,38.03,9.38
3,石家庄,130100.0,2018,0.000109,0.000451,84.00,100.00,41.16,16.35
4,唐山,130200.0,2018,0.000113,0.003276,74.41,100.00,41.51,15.54
5,秦皇岛,130300.0,2018,0.000124,0.001179,77.46,100.00,41.29,17.89
...,...,...,...,...,...,...,...,...,...
314,固原,640400.0,2018,0.000035,0.000440,77.19,87.95,36.45,25.55
315,中卫,640500.0,2018,0.000362,0.006268,34.50,96.54,40.10,24.14
316,新疆,650000.0,2018,0.000187,0.003792,50.10,91.40,39.60,14.31
317,乌鲁木齐,650100.0,2018,0.000088,0.000941,84.94,99.97,41.90,12.70
318,克拉玛依,650200.0,2018,0.000195,0.000263,95.93,100.00,43.29,11.07

In [60]:
# Initialize a column for the normalized values
data_merged['X1_star'] = pd.Series(dtype='float')
column_to_normalize = 'Res1'
# Iterate over each year to perform the normalization
for year in range(2018, 2019):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X1_max = year_data[column_to_normalize].max()
    X1_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X1_star'] = (X1_max - year_data[column_to_normalize]) / (X1_max - X1_min)


# Initialize a column for the normalized values
data_merged['X2_star'] = pd.Series(dtype='float')
column_to_normalize = 'Res2'
# Iterate over each year to perform the normalization
for year in range(2018, 2019):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X2_max = year_data[column_to_normalize].max()
    X2_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X2_star'] = (X2_max - year_data[column_to_normalize]) / (X2_max - X2_min)

data_merged['X3_star'] = pd.Series(dtype='float')
column_to_normalize = 'Ada1'
# Iterate over each year to perform the normalization
for year in range(2018, 2019):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X3_max = year_data[column_to_normalize].max()
    X3_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X3_star'] = (year_data[column_to_normalize] - X3_min) / (X3_max - X3_min)

data_merged['X4_star'] = pd.Series(dtype='float')
column_to_normalize = 'Ada2'
# Iterate over each year to perform the normalization
for year in range(2018, 2019):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X4_max = year_data[column_to_normalize].max()
    X4_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X4_star'] = (year_data[column_to_normalize] - X4_min) / (X4_max - X4_min)

data_merged['X5_star'] = pd.Series(dtype='float')
column_to_normalize = 'Rec1'
# Iterate over each year to perform the normalization
for year in range(2018, 2019):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X5_max = year_data[column_to_normalize].max()
    X5_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X5_star'] = (year_data[column_to_normalize] - X5_min) / (X5_max - X5_min)

data_merged['X6_star'] = pd.Series(dtype='float')
column_to_normalize = 'Rec2'
# Iterate over each year to perform the normalization
for year in range(2018, 2019):  # Including 2021
    # Filter the DataFrame for the current year
    year_data = data_merged[data_merged['Year'] == year]
    
    # Calculate the max and min values for the current year
    X6_max = year_data[column_to_normalize].max()
    X6_min = year_data[column_to_normalize].min()
    
    # Apply the normalization formula for the current year
    data_merged.loc[data_merged['Year'] == year, 'X6_star'] = (year_data[column_to_normalize] - X6_min) / (X6_max - X6_min)

/tmp/ipykernel_8750/176800289.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_merged['X1_star'] = pd.Series(dtype='float')
/tmp/ipykernel_8750/176800289.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_merged['X2_star'] = pd.Series(dtype='float')
/tmp/ipykernel_8750/176800289.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_merged['X3_star'] = pd.Series(dtype='float')
/tmp/ipykernel_8750/176800289.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_merged['X4_star'] = pd.Series(dtype='float')
/tmp/ipykernel_8750/176800289.py:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_merged['X5_star'] = pd.Series(dtype='float')
/tmp/ipykernel_8750/176800289.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_merged['X6_star'] = pd.Series(dtype='float')

In [61]:
data_merged

,Name_of_Regions,Citycode,Year,Res1,Res2,Ada1,Ada2,Rec1,Rec2,X1_star,X2_star,X3_star,X4_star,X5_star,X6_star
0,北京,110000.0,2018,0.000028,0.000051,68.93,99.94,48.44,16.30,0.990271,0.996482,0.688240,0.998084,0.516363,0.314476
1,天津,120000.0,2018,0.000094,0.000185,98.90,98.37,38.03,9.38,0.962242,0.987125,0.988962,0.947940,0.405394,0.113722
3,石家庄,130100.0,2018,0.000109,0.000451,84.00,100.00,41.16,16.35,0.955817,0.968664,0.839454,1.000000,0.438759,0.315927
4,唐山,130200.0,2018,0.000113,0.003276,74.41,100.00,41.51,15.54,0.954230,0.772293,0.743227,1.000000,0.442490,0.292428
5,秦皇岛,130300.0,2018,0.000124,0.001179,77.46,100.00,41.29,17.89,0.949832,0.918019,0.773831,1.000000,0.440145,0.360603
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,固原,640400.0,2018,0.000035,0.000440,77.19,87.95,36.45,25.55,0.987242,0.969415,0.771122,0.615139,0.388551,0.582826
315,中卫,640500.0,2018,0.000362,0.006268,34.50,96.54,40.10,24.14,0.849441,0.564264,0.342765,0.889492,0.427460,0.541921
316,新疆,650000.0,2018,0.000187,0.003792,50.10,91.40,39.60,14.31,0.923312,0.736428,0.499298,0.725327,0.422130,0.256745
317,乌鲁木齐,650100.0,2018,0.000088,0.000941,84.94,99.97,41.90,12.70,0.964727,0.934556,0.848886,0.999042,0.446647,0.210038
318,克拉玛依,650200.0,2018,0.000195,0.000263,95.93,100.00,43.29,11.07,0.919970,0.981695,0.959161,1.000000,0.461465,0.162750

In [62]:
columns_to_keep = ['Name_of_Regions','Citycode','Year','X1_star','X2_star','X3_star','X4_star','X5_star','X6_star']
data_process = data_merged[columns_to_keep]

In [63]:
#1.7熵权法

def calculate_entropy(indicator_data):
    # Replace zero values to avoid log(0) and negative infinity in entropy calculation
    indicator_data = indicator_data.replace(0, np.finfo(float).eps)  # Use a small number instead of zero
    p_ij = indicator_data / indicator_data.sum()  # Calculate the proportion p_ij
    K = 1 / np.log(291)  # Calculate the constant K
    e_j = -K * (p_ij * np.log(p_ij)).sum()  # Calculate the entropy e_j
    return e_j

# Initialize an empty list to store DataFrames for each year
dataframes_list = []

# Calculate entropies and weights for each year
for year in range(2018, 2019):
    year_data = data_process[data_process['Year'] == year].copy()
    entropies = year_data[['X1_star', 'X2_star', 'X3_star', 'X4_star','X5_star','X6_star']].apply(calculate_entropy, axis=0)
    weights = (1 - entropies) / (1 - entropies).sum()  # Calculate weights, ensuring they sum up to 1 within the year
    for i, indicator in enumerate(['X1_star', 'X2_star', 'X3_star', 'X4_star','X5_star','X6_star']):
        year_data[indicator + '_weighted'] = year_data[indicator] * weights.values[i]  # Apply weights to the indicators
    dataframes_list.append(year_data)  # Append the yearly data to the list

# Concatenate all DataFrames in the list to create the comprehensive_scores DataFrame
UER = pd.concat(dataframes_list, ignore_index=True)

# Now you should have the comprehensive_scores DataFrame with correctly calculated weights per year

In [64]:
UER

,Name_of_Regions,Citycode,Year,X1_star,X2_star,X3_star,X4_star,X5_star,X6_star,X1_star_weighted,X2_star_weighted,X3_star_weighted,X4_star_weighted,X5_star_weighted,X6_star_weighted
0,北京,110000.0,2018,0.990271,0.996482,0.688240,0.998084,0.516363,0.314476,0.022731,0.047717,0.225438,0.059073,0.040766,0.145750
1,天津,120000.0,2018,0.962242,0.987125,0.988962,0.947940,0.405394,0.113722,0.022088,0.047269,0.323941,0.056106,0.032005,0.052707
2,石家庄,130100.0,2018,0.955817,0.968664,0.839454,1.000000,0.438759,0.315927,0.021940,0.046385,0.274969,0.059187,0.034640,0.146422
3,唐山,130200.0,2018,0.954230,0.772293,0.743227,1.000000,0.442490,0.292428,0.021904,0.036982,0.243449,0.059187,0.034934,0.135531
4,秦皇岛,130300.0,2018,0.949832,0.918019,0.773831,1.000000,0.440145,0.360603,0.021803,0.043960,0.253473,0.059187,0.034749,0.167128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,固原,640400.0,2018,0.987242,0.969415,0.771122,0.615139,0.388551,0.582826,0.022662,0.046421,0.252586,0.036408,0.030676,0.270121
287,中卫,640500.0,2018,0.849441,0.564264,0.342765,0.889492,0.427460,0.541921,0.019498,0.027020,0.112275,0.052646,0.033748,0.251163
288,新疆,650000.0,2018,0.923312,0.736428,0.499298,0.725327,0.422130,0.256745,0.021194,0.035264,0.163548,0.042930,0.033327,0.118993
289,乌鲁木齐,650100.0,2018,0.964727,0.934556,0.848886,0.999042,0.446647,0.210038,0.022145,0.044751,0.278058,0.059130,0.035262,0.097346
290,克拉玛依,650200.0,2018,0.919970,0.981695,0.959161,1.000000,0.461465,0.162750,0.021117,0.047009,0.314180,0.059187,0.036432,0.075429

In [65]:
# Calculate the combined weighted values for Resistance, Adaptability, and Recovery
UER['RES'] = UER['X1_star_weighted'] + UER['X2_star_weighted']
UER['ADA'] = UER['X3_star_weighted'] + UER['X4_star_weighted']
#comprehensive_scores['ADA'] = comprehensive_scores['X2_star_weighted'] 
UER['REC'] = UER['X5_star_weighted'] + UER['X6_star_weighted']

# Assuming data_merged is the DataFrame with the standardized 'RES', 'ADA', and 'REC' columns.

# Define a small positive value to add to REC to avoid zero values
small_positive_value = 1e-6

# Replace zero values in REC with the small positive value
UER['REC_adj'] = UER['REC'].replace(0, small_positive_value)
UER['ADA_adj'] = UER['ADA'].replace(0, small_positive_value)
UER['RES_adj'] = UER['RES'].replace(0, small_positive_value)

# Now, the UER values should not be zero due to REC being zero, since we have adjusted REC values slightly above zero.

# Calculate the Urban Ecological Resilience (UER) for each borough and year
UER['UER'] = (UER['RES_adj'] * UER['ADA_adj'] * UER['REC_adj']) ** (1/3)

# Check the result
UER[['Year', 'Name_of_Regions', 'RES', 'ADA', 'REC', 'UER']].head()

   Year Name_of_Regions       RES       ADA       REC       UER
0  2018              北京  0.070448  0.284511  0.186516  0.155201
1  2018              天津  0.069357  0.380047  0.084712  0.130704
2  2018             石家庄  0.068325  0.334155  0.181062  0.160491
3  2018              唐山  0.058885  0.302636  0.170465  0.144829
4  2018             秦皇岛  0.065763  0.312660  0.201877  0.160711

In [66]:
UER

,Name_of_Regions,Citycode,Year,X1_star,X2_star,X3_star,X4_star,X5_star,X6_star,X1_star_weighted,...,X4_star_weighted,X5_star_weighted,X6_star_weighted,RES,ADA,REC,REC_adj,ADA_adj,RES_adj,UER
0,北京,110000.0,2018,0.990271,0.996482,0.688240,0.998084,0.516363,0.314476,0.022731,...,0.059073,0.040766,0.145750,0.070448,0.284511,0.186516,0.186516,0.284511,0.070448,0.155201
1,天津,120000.0,2018,0.962242,0.987125,0.988962,0.947940,0.405394,0.113722,0.022088,...,0.056106,0.032005,0.052707,0.069357,0.380047,0.084712,0.084712,0.380047,0.069357,0.130704
2,石家庄,130100.0,2018,0.955817,0.968664,0.839454,1.000000,0.438759,0.315927,0.021940,...,0.059187,0.034640,0.146422,0.068325,0.334155,0.181062,0.181062,0.334155,0.068325,0.160491
3,唐山,130200.0,2018,0.954230,0.772293,0.743227,1.000000,0.442490,0.292428,0.021904,...,0.059187,0.034934,0.135531,0.058885,0.302636,0.170465,0.170465,0.302636,0.058885,0.144829
4,秦皇岛,130300.0,2018,0.949832,0.918019,0.773831,1.000000,0.440145,0.360603,0.021803,...,0.059187,0.034749,0.167128,0.065763,0.312660,0.201877,0.201877,0.312660,0.065763,0.160711
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,固原,640400.0,2018,0.987242,0.969415,0.771122,0.615139,0.388551,0.582826,0.022662,...,0.036408,0.030676,0.270121,0.069082,0.288994,0.300797,0.300797,0.288994,0.069082,0.181765
287,中卫,640500.0,2018,0.849441,0.564264,0.342765,0.889492,0.427460,0.541921,0.019498,...,0.052646,0.033748,0.251163,0.046518,0.164921,0.284910,0.284910,0.164921,0.046518,0.129779
288,新疆,650000.0,2018,0.923312,0.736428,0.499298,0.725327,0.422130,0.256745,0.021194,...,0.042930,0.033327,0.118993,0.056458,0.206478,0.152320,0.152320,0.206478,0.056458,0.121093
289,乌鲁木齐,650100.0,2018,0.964727,0.934556,0.848886,0.999042,0.446647,0.210038,0.022145,...,0.059130,0.035262,0.097346,0.066896,0.337188,0.132608,0.132608,0.337188,0.066896,0.144084
290,克拉玛依,650200.0,2018,0.919970,0.981695,0.959161,1.000000,0.461465,0.162750,0.021117,...,0.059187,0.036432,0.075429,0.068126,0.373366,0.111862,0.111862,0.373366,0.068126,0.141702

In [67]:
df_merged1 = pd.merge(UI, UER, on=['Citycode', 'Year'])

In [68]:
df_merged1

,Name_of_Regions_x,Citycode,Year,X1_star_x,X2_star_x,X3_star_x,X4_star_x,X5_star_x,X6_star_x,X1_star_weighted_x,...,X4_star_weighted_y,X5_star_weighted_y,X6_star_weighted_y,RES,ADA,REC,REC_adj,ADA_adj,RES_adj,UER
0,北京,110000.0,2018,0.829428,0.140779,0.187269,0.993197,0.148173,0.800147,0.021353,...,0.059073,0.040766,0.145750,0.070448,0.284511,0.186516,0.186516,0.284511,0.070448,0.155201
1,天津,120000.0,2018,0.786303,0.207884,0.189034,0.981179,0.126452,0.939051,0.020242,...,0.056106,0.032005,0.052707,0.069357,0.380047,0.084712,0.084712,0.380047,0.069357,0.130704
2,石家庄,130100.0,2018,0.528965,0.071994,0.045769,0.845351,0.034613,0.873850,0.013618,...,0.059187,0.034640,0.146422,0.068325,0.334155,0.181062,0.181062,0.334155,0.068325,0.160491
3,唐山,130200.0,2018,0.528708,0.043497,0.037484,0.841270,0.040310,0.911891,0.013611,...,0.059187,0.034934,0.135531,0.058885,0.302636,0.170465,0.170465,0.302636,0.058885,0.144829
4,秦皇岛,130300.0,2018,0.480819,0.049777,0.036924,0.720181,0.016741,0.795946,0.012378,...,0.059187,0.034749,0.167128,0.065763,0.312660,0.201877,0.201877,0.312660,0.065763,0.160711
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,固原,640400.0,2018,0.204171,0.012303,0.008491,0.569615,0.002213,0.697134,0.005256,...,0.036408,0.030676,0.270121,0.069082,0.288994,0.300797,0.300797,0.288994,0.069082,0.181765
287,中卫,640500.0,2018,0.287590,0.006728,0.004622,0.677324,0.002268,0.607064,0.007404,...,0.052646,0.033748,0.251163,0.046518,0.164921,0.284910,0.284910,0.164921,0.046518,0.129779
288,新疆,650000.0,2018,0.371267,0.001365,0.001400,0.686848,0.000502,0.116094,0.009558,...,0.042930,0.033327,0.118993,0.056458,0.206478,0.152320,0.152320,0.206478,0.056458,0.121093
289,乌鲁木齐,650100.0,2018,0.876416,0.039857,0.069316,0.983447,0.017931,0.350442,0.022562,...,0.059130,0.035262,0.097346,0.066896,0.337188,0.132608,0.132608,0.337188,0.066896,0.144084
290,克拉玛依,650200.0,2018,0.598352,0.027360,0.021239,0.989342,0.009673,0.130037,0.015404,...,0.059187,0.036432,0.075429,0.068126,0.373366,0.111862,0.111862,0.373366,0.068126,0.141702

In [69]:
df_result = df_merged1[['Name_of_Regions_x', 'Citycode', 'Year', 'UER', 'UI']]

In [70]:
df_result

    Name_of_Regions_x  Citycode  Year       UER        UI
0                  北京  110000.0  2018  0.155201  0.189678
1                  天津  120000.0  2018  0.130704  0.204437
2                 石家庄  130100.0  2018  0.160491  0.078075
3                  唐山  130200.0  2018  0.144829  0.068595
4                 秦皇岛  130300.0  2018  0.160711  0.059291
..                ...       ...   ...       ...       ...
286                固原  640400.0  2018  0.181765  0.024308
287                中卫  640500.0  2018  0.129779  0.023746
288                新疆  650000.0  2018  0.121093  0.018339
289              乌鲁木齐  650100.0  2018  0.144084  0.075474
290              克拉玛依  650200.0  2018  0.141702  0.044703

[291 rows x 5 columns]

In [71]:
# 定义计算公式
def calculate_C(UI, UER):
    return np.sqrt((UI * UER) / ((UI + UER) / 2)**2)

def calculate_T(UI, UER, mu1=0.5, mu2=0.5):
    return mu1 * UI + mu2 * UER

def calculate_D(C, T):
    return np.sqrt(C * T)

# 计算C耦合度
df_result['C'] = df_result.apply(lambda row: calculate_C(row['UI'], row['UER']), axis=1)

# 计算T协调度
df_result['T'] = df_result.apply(lambda row: calculate_T(row['UI'], row['UER']), axis=1)

# 计算D耦合协调度
df_result['D'] = df_result.apply(lambda row: calculate_D(row['C'], row['T']), axis=1)

/tmp/ipykernel_8750/4091750289.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['C'] = df_result.apply(lambda row: calculate_C(row['UI'], row['UER']), axis=1)
/tmp/ipykernel_8750/4091750289.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['T'] = df_result.apply(lambda row: calculate_T(row['UI'], row['UER']), axis=1)
/tmp/ipykernel_8750/4091750289.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['D'] = df_result.apply(lambda row: calculate_D(row['C'], row['T']), axis=1)

In [72]:
# 定义归一化公式
def normalize(column):
    return (column - column.min()) / (column.max() - column.min())

# 归一化处理
df_result['UI_normalized'] = normalize(df_result['UI'])
df_result['UER_normalized'] = normalize(df_result['UER'])

# 定义计算公式
def calculate_C(UI, UER):
    return np.sqrt((UI * UER) / ((UI + UER) / 2)**2)

def calculate_T(UI, UER, mu1=0.5, mu2=0.5):
    return mu1 * UI + mu2 * UER

def calculate_D(C, T):
    return np.sqrt(C * T)

# 计算C耦合度
df_result['C2'] = df_result.apply(lambda row: calculate_C(row['UI_normalized'], row['UER_normalized']), axis=1)

# 计算T协调度
df_result['T2'] = df_result.apply(lambda row: calculate_T(row['UI_normalized'], row['UER_normalized']), axis=1)

# 计算D耦合协调度
df_result['D2'] = df_result.apply(lambda row: calculate_D(row['C2'], row['T2']), axis=1)

/tmp/ipykernel_8750/3512385329.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['UI_normalized'] = normalize(df_result['UI'])
/tmp/ipykernel_8750/3512385329.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['UER_normalized'] = normalize(df_result['UER'])
/tmp/ipykernel_8750/3512385329.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['C2'] = df_result.apply(lambda row: calculate_C(row['UI_normalized'], row['UER_normalized']), axis=1)
/tmp/ipykernel_8750/3512385329.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['T2'] = df_result.apply(lambda row: calculate_T(row['UI_normalized'], row['UER_normalized']), axis=1)
/tmp/ipykernel_8750/3512385329.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['D2'] = df_result.apply(lambda row: calculate_D(row['C2'], row['T2']), axis=1)

In [73]:
df_result

,Name_of_Regions_x,Citycode,Year,UER,UI,C,T,D,UI_normalized,UER_normalized,C2,T2,D2
0,北京,110000.0,2018,0.155201,0.189678,0.994991,0.172440,0.414217,0.179462,0.694045,0.808060,0.436754,0.594073
1,天津,120000.0,2018,0.130704,0.204437,0.975499,0.167570,0.404308,0.194427,0.536943,0.883559,0.365685,0.568423
2,石家庄,130100.0,2018,0.160491,0.078075,0.938431,0.119283,0.334573,0.066292,0.727973,0.553164,0.397133,0.468700
3,唐山,130200.0,2018,0.144829,0.068595,0.934029,0.106712,0.315708,0.056679,0.627525,0.551279,0.342102,0.434274
4,秦皇岛,130300.0,2018,0.160711,0.059291,0.887402,0.110001,0.312434,0.047245,0.729383,0.478049,0.388314,0.430852
...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,固原,640400.0,2018,0.181765,0.024308,0.645115,0.103036,0.257818,0.011771,0.864404,0.230252,0.438087,0.317601
287,中卫,640500.0,2018,0.129779,0.023746,0.723181,0.076762,0.235612,0.011201,0.531007,0.284474,0.271104,0.277708
288,新疆,650000.0,2018,0.121093,0.018339,0.675956,0.069716,0.217083,0.005719,0.475304,0.216772,0.240511,0.228333
289,乌鲁木齐,650100.0,2018,0.144084,0.075474,0.949921,0.109779,0.322926,0.063655,0.622748,0.580127,0.343201,0.446207
290,克拉玛依,650200.0,2018,0.141702,0.044703,0.853943,0.093203,0.282117,0.032452,0.607476,0.438821,0.319964,0.374709

In [74]:
# 导出comprehensive_scores数据框为Excel文件
output_excel_path = 'data/df_2018_result.xlsx'
df_result.to_excel(output_excel_path, index=False)

In [2]:
#如果未运行以上步骤，导入本年数据
file_path = 'data/df_2018_result.xlsx'
df_result = pd.read_excel(file_path)

In [3]:
file_path = 'data/df_2014_result.xlsx'
df_result_2014 = pd.read_excel(file_path)

In [4]:
df_result_2014

,Name_of_Regions_x,Citycode,Year,UER,UI,C,T,D,UI_normalized,UER_normalized,C2,T2,D2
0,北京,110000,2014,0.161391,0.188319,0.997031,0.174855,0.417536,0.176834,0.747975,0.786510,0.462404,0.603064
1,天津,120000,2014,0.139817,0.191527,0.987747,0.165672,0.404527,0.180092,0.627424,0.832543,0.403758,0.579781
2,石家庄,130100,2014,0.147570,0.071942,0.938775,0.109756,0.320992,0.058646,0.670748,0.543834,0.364697,0.445348
3,唐山,130200,2014,0.132432,0.068280,0.947545,0.100356,0.308370,0.054927,0.586162,0.559776,0.320544,0.423595
4,秦皇岛,130300,2014,0.170453,0.050775,0.841043,0.110614,0.305010,0.037150,0.798608,0.412190,0.417879,0.415025
...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,固原,640400,2014,0.121501,0.024241,0.744748,0.072871,0.232960,0.010203,0.525083,0.273476,0.267643,0.270544
287,中卫,640500,2014,0.122567,0.023381,0.733585,0.072974,0.231371,0.009330,0.531041,0.260518,0.270185,0.265308
288,新疆,650000,2014,0.117719,0.019102,0.693176,0.068411,0.217763,0.004985,0.503949,0.196959,0.254467,0.223874
289,乌鲁木齐,650100,2014,0.134899,0.072407,0.953483,0.103653,0.314375,0.059119,0.599945,0.571505,0.329532,0.433969
290,克拉玛依,650200,2014,0.144934,0.042043,0.834976,0.093488,0.279393,0.028282,0.656017,0.398104,0.342149,0.369068

In [5]:
# 找出 df_result_2010 和 df_result 在 Citycode 列不匹配的行
mismatch_2014 = df_result_2014[~df_result_2014['Citycode'].isin(df_result['Citycode'])]
mismatch_result = df_result[~df_result['Citycode'].isin(df_result_2014['Citycode'])]

# 输出不匹配的行
print("Rows in df_result_2014 not in df_result:")
print(mismatch_2014)

print("\nRows in df_result not in df_result_2014:")
print(mismatch_result)

Rows in df_result_2014 not in df_result:
Empty DataFrame
Columns: [Name_of_Regions_x, Citycode, Year, UER, UI, C, T, D, UI_normalized, UER_normalized, C2, T2, D2]
Index: []

Rows in df_result not in df_result_2014:
Empty DataFrame
Columns: [Name_of_Regions_x, Citycode, Year, UER, UI, C, T, D, UI_normalized, UER_normalized, C2, T2, D2]
Index: []

In [6]:
# 合并数据
df_merged2 = pd.merge(df_result_2014, df_result, left_on='Citycode', right_on='Citycode', suffixes=('_2014', '_2018'))

In [7]:
df_merged2

,Name_of_Regions_x_2014,Citycode,Year_2014,UER_2014,UI_2014,C_2014,T_2014,D_2014,UI_normalized_2014,UER_normalized_2014,...,UER_2018,UI_2018,C_2018,T_2018,D_2018,UI_normalized_2018,UER_normalized_2018,C2_2018,T2_2018,D2_2018
0,北京,110000,2014,0.161391,0.188319,0.997031,0.174855,0.417536,0.176834,0.747975,...,0.155201,0.189678,0.994991,0.172440,0.414217,0.179462,0.694045,0.808060,0.436754,0.594073
1,天津,120000,2014,0.139817,0.191527,0.987747,0.165672,0.404527,0.180092,0.627424,...,0.130704,0.204437,0.975499,0.167570,0.404308,0.194427,0.536943,0.883559,0.365685,0.568423
2,石家庄,130100,2014,0.147570,0.071942,0.938775,0.109756,0.320992,0.058646,0.670748,...,0.160491,0.078075,0.938431,0.119283,0.334573,0.066292,0.727973,0.553164,0.397133,0.468700
3,唐山,130200,2014,0.132432,0.068280,0.947545,0.100356,0.308370,0.054927,0.586162,...,0.144829,0.068595,0.934029,0.106712,0.315708,0.056679,0.627525,0.551279,0.342102,0.434274
4,秦皇岛,130300,2014,0.170453,0.050775,0.841043,0.110614,0.305010,0.037150,0.798608,...,0.160711,0.059291,0.887402,0.110001,0.312434,0.047245,0.729383,0.478049,0.388314,0.430852
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,固原,640400,2014,0.121501,0.024241,0.744748,0.072871,0.232960,0.010203,0.525083,...,0.181765,0.024308,0.645115,0.103036,0.257818,0.011771,0.864404,0.230252,0.438087,0.317601
287,中卫,640500,2014,0.122567,0.023381,0.733585,0.072974,0.231371,0.009330,0.531041,...,0.129779,0.023746,0.723181,0.076762,0.235612,0.011201,0.531007,0.284474,0.271104,0.277708
288,新疆,650000,2014,0.117719,0.019102,0.693176,0.068411,0.217763,0.004985,0.503949,...,0.121093,0.018339,0.675956,0.069716,0.217083,0.005719,0.475304,0.216772,0.240511,0.228333
289,乌鲁木齐,650100,2014,0.134899,0.072407,0.953483,0.103653,0.314375,0.059119,0.599945,...,0.144084,0.075474,0.949921,0.109779,0.322926,0.063655,0.622748,0.580127,0.343201,0.446207
290,克拉玛依,650200,2014,0.144934,0.042043,0.834976,0.093488,0.279393,0.028282,0.656017,...,0.141702,0.044703,0.853943,0.093203,0.282117,0.032452,0.607476,0.438821,0.319964,0.374709

# 计算Tapio脱钩模型

In [8]:
# 计算增长率
df_merged2['Delta_UER'] = (df_merged2['UER_2018'] - df_merged2['UER_2014']) / df_merged2['UER_2014']
df_merged2['Delta_UI'] = (df_merged2['UI_2018'] - df_merged2['UI_2014']) / df_merged2['UI_2014']

# 计算脱钩指数DI
df_merged2['DI'] = df_merged2['Delta_UER'] / df_merged2['Delta_UI']

In [9]:
df_merged2

,Name_of_Regions_x_2014,Citycode,Year_2014,UER_2014,UI_2014,C_2014,T_2014,D_2014,UI_normalized_2014,UER_normalized_2014,...,T_2018,D_2018,UI_normalized_2018,UER_normalized_2018,C2_2018,T2_2018,D2_2018,Delta_UER,Delta_UI,DI
0,北京,110000,2014,0.161391,0.188319,0.997031,0.174855,0.417536,0.176834,0.747975,...,0.172440,0.414217,0.179462,0.694045,0.808060,0.436754,0.594073,-0.038355,0.007216,-5.315521
1,天津,120000,2014,0.139817,0.191527,0.987747,0.165672,0.404527,0.180092,0.627424,...,0.167570,0.404308,0.194427,0.536943,0.883559,0.365685,0.568423,-0.065173,0.067401,-0.966951
2,石家庄,130100,2014,0.147570,0.071942,0.938775,0.109756,0.320992,0.058646,0.670748,...,0.119283,0.334573,0.066292,0.727973,0.553164,0.397133,0.468700,0.087559,0.085250,1.027081
3,唐山,130200,2014,0.132432,0.068280,0.947545,0.100356,0.308370,0.054927,0.586162,...,0.106712,0.315708,0.056679,0.627525,0.551279,0.342102,0.434274,0.093608,0.004606,20.321578
4,秦皇岛,130300,2014,0.170453,0.050775,0.841043,0.110614,0.305010,0.037150,0.798608,...,0.110001,0.312434,0.047245,0.729383,0.478049,0.388314,0.430852,-0.057152,0.167709,-0.340784
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,固原,640400,2014,0.121501,0.024241,0.744748,0.072871,0.232960,0.010203,0.525083,...,0.103036,0.257818,0.011771,0.864404,0.230252,0.438087,0.317601,0.495995,0.002763,179.491176
287,中卫,640500,2014,0.122567,0.023381,0.733585,0.072974,0.231371,0.009330,0.531041,...,0.076762,0.235612,0.011201,0.531007,0.284474,0.271104,0.277708,0.058838,0.015596,3.772512
288,新疆,650000,2014,0.117719,0.019102,0.693176,0.068411,0.217763,0.004985,0.503949,...,0.069716,0.217083,0.005719,0.475304,0.216772,0.240511,0.228333,0.028665,-0.039943,-0.717649
289,乌鲁木齐,650100,2014,0.134899,0.072407,0.953483,0.103653,0.314375,0.059119,0.599945,...,0.109779,0.322926,0.063655,0.622748,0.580127,0.343201,0.446207,0.068088,0.042354,1.607583
290,克拉玛依,650200,2014,0.144934,0.042043,0.834976,0.093488,0.279393,0.028282,0.656017,...,0.093203,0.282117,0.032452,0.607476,0.438821,0.319964,0.374709,-0.022296,0.063271,-0.352385

In [10]:
def classify_decoupling(row):
    Delta_ER = row['Delta_UER']
    Delta_UI = row['Delta_UI']
    DI = row['DI']
    
    if Delta_ER < 0 and Delta_UI < 0 and 1.2 <= DI < float('inf'):
        return 'Recession decoupling / Decoupling'
    elif Delta_ER < 0 and Delta_UI > 0 and float('-inf') < DI <= 0:
        return 'Strong decoupling / Decoupling'
    elif Delta_ER > 0 and Delta_UI > 0 and 0 <= DI <= 0.8:
        return 'Weak decoupling / Decoupling'
    elif Delta_ER > 0 and Delta_UI > 0 and 0.8 < DI <= 1.2:
        return 'Expansion connection / Connection'
    elif Delta_ER < 0 and Delta_UI < 0 and 0.8 < DI <= 1.2:
        return 'Recession connection / Connection'
    elif Delta_ER > 0 and Delta_UI > 0 and 1.2 <= DI < float('inf'):
        return 'Negative decoupling of expansion / Negative decoupling'
    elif Delta_ER > 0 and Delta_UI < 0 and float('-inf') < DI <= 0:
        return 'Strong negative decoupling / Negative decoupling'
    elif Delta_ER < 0 and Delta_UI < 0 and 0 <= DI <= 0.8:
        return 'Weak negative decoupling / Negative decoupling'
    else:
        return 'Unknown'

# Apply the function to the DataFrame
df_merged2['DI_Category'] = df_merged2.apply(classify_decoupling, axis=1)

In [11]:
df_merged2

,Name_of_Regions_x_2014,Citycode,Year_2014,UER_2014,UI_2014,C_2014,T_2014,D_2014,UI_normalized_2014,UER_normalized_2014,...,D_2018,UI_normalized_2018,UER_normalized_2018,C2_2018,T2_2018,D2_2018,Delta_UER,Delta_UI,DI,DI_Category
0,北京,110000,2014,0.161391,0.188319,0.997031,0.174855,0.417536,0.176834,0.747975,...,0.414217,0.179462,0.694045,0.808060,0.436754,0.594073,-0.038355,0.007216,-5.315521,Strong decoupling / Decoupling
1,天津,120000,2014,0.139817,0.191527,0.987747,0.165672,0.404527,0.180092,0.627424,...,0.404308,0.194427,0.536943,0.883559,0.365685,0.568423,-0.065173,0.067401,-0.966951,Strong decoupling / Decoupling
2,石家庄,130100,2014,0.147570,0.071942,0.938775,0.109756,0.320992,0.058646,0.670748,...,0.334573,0.066292,0.727973,0.553164,0.397133,0.468700,0.087559,0.085250,1.027081,Expansion connection / Connection
3,唐山,130200,2014,0.132432,0.068280,0.947545,0.100356,0.308370,0.054927,0.586162,...,0.315708,0.056679,0.627525,0.551279,0.342102,0.434274,0.093608,0.004606,20.321578,Negative decoupling of expansion / Negative de...
4,秦皇岛,130300,2014,0.170453,0.050775,0.841043,0.110614,0.305010,0.037150,0.798608,...,0.312434,0.047245,0.729383,0.478049,0.388314,0.430852,-0.057152,0.167709,-0.340784,Strong decoupling / Decoupling
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,固原,640400,2014,0.121501,0.024241,0.744748,0.072871,0.232960,0.010203,0.525083,...,0.257818,0.011771,0.864404,0.230252,0.438087,0.317601,0.495995,0.002763,179.491176,Negative decoupling of expansion / Negative de...
287,中卫,640500,2014,0.122567,0.023381,0.733585,0.072974,0.231371,0.009330,0.531041,...,0.235612,0.011201,0.531007,0.284474,0.271104,0.277708,0.058838,0.015596,3.772512,Negative decoupling of expansion / Negative de...
288,新疆,650000,2014,0.117719,0.019102,0.693176,0.068411,0.217763,0.004985,0.503949,...,0.217083,0.005719,0.475304,0.216772,0.240511,0.228333,0.028665,-0.039943,-0.717649,Strong negative decoupling / Negative decoupling
289,乌鲁木齐,650100,2014,0.134899,0.072407,0.953483,0.103653,0.314375,0.059119,0.599945,...,0.322926,0.063655,0.622748,0.580127,0.343201,0.446207,0.068088,0.042354,1.607583,Negative decoupling of expansion / Negative de...
290,克拉玛依,650200,2014,0.144934,0.042043,0.834976,0.093488,0.279393,0.028282,0.656017,...,0.282117,0.032452,0.607476,0.438821,0.319964,0.374709,-0.022296,0.063271,-0.352385,Strong decoupling / Decoupling

In [12]:
df_merged2['Citycode'] = df_merged2['Citycode'].astype('object')

In [13]:
df_merged2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 291 entries, 0 to 290
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name_of_Regions_x_2014  291 non-null    object
 1   Citycode                291 non-null    object
 2   Year_2014               291 non-null    int64
 3   UER_2014                291 non-null    float64
 4   UI_2014                 291 non-null    float64
 5   C_2014                  291 non-null    float64
 6   T_2014                  291 non-null    float64
 7   D_2014                  291 non-null    float64
 8   UI_normalized_2014      291 non-null    float64
 9   UER_normalized_2014     291 non-null    float64
 10  C2_2014                 291 non-null    float64
 11  T2_2014                 291 non-null    float64
 12  D2_2014                 291 non-null    float64
 13  Name_of_Regions_x_2018  291 non-null    object
 14  Year_2018               291 non-null    int64
 15  UER_2018                291 non-null    float64
 16  UI_2018                 291 non-null    float64
 17  C_2018                  291 non-null    float64
 18  T_2018                  291 non-null    float64
 19  D_2018                  291 non-null    float64
 20  UI_normalized_2018      291 non-null    float64
 21  UER_normalized_2018     291 non-null    float64
 22  C2_2018                 291 non-null    float64
 23  T2_2018                 291 non-null    float64
 24  D2_2018                 291 non-null    float64
 25  Delta_UER               291 non-null    float64
 26  Delta_UI                291 non-null    float64
 27  DI                      291 non-null    float64
 28  DI_Category             291 non-null    object
dtypes: float64(23), int64(2), object(4)
memory usage: 66.1+ KB

In [14]:
# 读取shapefile
shapefile_path = 'data/Chinamap_2019/Merged_Municipalities.shp'
gdf = gpd.read_file(shapefile_path)

In [15]:
gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 317 entries, 0 to 316
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Prvnc_c   317 non-null    float64
 1   City_cd   317 non-null    object
 2   Area      317 non-null    object
 3   Name      286 non-null    object
 4   geometry  317 non-null    geometry
dtypes: float64(1), geometry(1), object(3)
memory usage: 12.5+ KB

In [16]:
df_merged2['Citycode'] = df_merged2['Citycode'].astype(float)
gdf['City_cd'] = gdf['City_cd'].astype(float)

In [17]:
# 根据Citycode和市代码进行连接，保留不匹配的行
data_merged3 = gdf.merge(df_merged2, left_on='City_cd', right_on='Citycode', how='outer')

In [18]:
data_merged3.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 323 entries, 0 to 322
Data columns (total 34 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Prvnc_c                 317 non-null    float64
 1   City_cd                 317 non-null    float64
 2   Area                    317 non-null    object
 3   Name                    286 non-null    object
 4   geometry                317 non-null    geometry
 5   Name_of_Regions_x_2014  291 non-null    object
 6   Citycode                291 non-null    float64
 7   Year_2014               291 non-null    float64
 8   UER_2014                291 non-null    float64
 9   UI_2014                 291 non-null    float64
 10  C_2014                  291 non-null    float64
 11  T_2014                  291 non-null    float64
 12  D_2014                  291 non-null    float64
 13  UI_normalized_2014      291 non-null    float64
 14  UER_normalized_2014     291 non-null    float64
 15  C2_2014                 291 non-null    float64
 16  T2_2014                 291 non-null    float64
 17  D2_2014                 291 non-null    float64
 18  Name_of_Regions_x_2018  291 non-null    object
 19  Year_2018               291 non-null    float64
 20  UER_2018                291 non-null    float64
 21  UI_2018                 291 non-null    float64
 22  C_2018                  291 non-null    float64
 23  T_2018                  291 non-null    float64
 24  D_2018                  291 non-null    float64
 25  UI_normalized_2018      291 non-null    float64
 26  UER_normalized_2018     291 non-null    float64
 27  C2_2018                 291 non-null    float64
 28  T2_2018                 291 non-null    float64
 29  D2_2018                 291 non-null    float64
 30  Delta_UER               291 non-null    float64
 31  Delta_UI                291 non-null    float64
 32  DI                      291 non-null    float64
 33  DI_Category             291 non-null    object
dtypes: float64(28), geometry(1), object(5)
memory usage: 85.9+ KB

In [19]:
# 查找 Name_of_Regions_x_2010 有值但是 Name 列无值的行
rows_with_value_in_Regions_but_not_in_Name = data_merged3[(data_merged3['Name_of_Regions_x_2014'].notna()) & (data_merged3['Name'].isna())]

# 输出符合条件的行
print(rows_with_value_in_Regions_but_not_in_Name)

     Prvnc_c  City_cd Area Name geometry Name_of_Regions_x_2014  Citycode  \
317      NaN      NaN  NaN  NaN     None                     海口  460100.0
318      NaN      NaN  NaN  NaN     None                     三亚  460200.0
319      NaN      NaN  NaN  NaN     None                     拉萨  540100.0
320      NaN      NaN  NaN  NaN     None                     西宁  630100.0
321      NaN      NaN  NaN  NaN     None                   乌鲁木齐  650100.0
322      NaN      NaN  NaN  NaN     None                   克拉玛依  650200.0

     Year_2014  UER_2014   UI_2014  ...    D_2018  UI_normalized_2018  \
317     2014.0  0.149405  0.161383  ...  0.389582            0.171384
318     2014.0  0.161247  0.061102  ...  0.336275            0.068589
319     2014.0  0.087690  0.024916  ...  0.188535            0.011178
320     2014.0  0.135966  0.048140  ...  0.295745            0.042801
321     2014.0  0.134899  0.072407  ...  0.322926            0.063655
322     2014.0  0.144934  0.042043  ...  0.282117            0.032452

     UER_normalized_2018   C2_2018   T2_2018   D2_2018  Delta_UER  Delta_UI  \
317             0.511700  0.867059  0.341542  0.544185  -0.151513  0.125967
318             0.719475  0.563771  0.394032  0.471321  -0.012906  0.314831
319             0.040279  0.824720  0.025728  0.145667  -0.392634 -0.047901
320             0.592229  0.501426  0.317515  0.399012   0.024703  0.140598
321             0.622748  0.580127  0.343201  0.446207   0.068088  0.042354
322             0.607476  0.438821  0.319964  0.374709  -0.022296  0.063271

           DI                                        DI_Category
317 -1.202801                     Strong decoupling / Decoupling
318 -0.040992                     Strong decoupling / Decoupling
319  8.196853                  Recession decoupling / Decoupling
320  0.175700                       Weak decoupling / Decoupling
321  1.607583  Negative decoupling of expansion / Negative de...
322 -0.352385                     Strong decoupling / Decoupling

[6 rows x 34 columns]

In [20]:
# 删除 geometry 列为空值的行
data_merged3 = data_merged3.dropna(subset=['geometry'])

In [21]:
# 查找 geometry 列为空值的行
rows_with_nan_in_geometry = data_merged3[data_merged3['geometry'].isna()]

# 输出包含 geometry 列为空值的行
print(rows_with_nan_in_geometry)

Empty GeoDataFrame
Columns: [Prvnc_c, City_cd, Area, Name, geometry, Name_of_Regions_x_2014, Citycode, Year_2014, UER_2014, UI_2014, C_2014, T_2014, D_2014, UI_normalized_2014, UER_normalized_2014, C2_2014, T2_2014, D2_2014, Name_of_Regions_x_2018, Year_2018, UER_2018, UI_2018, C_2018, T_2018, D_2018, UI_normalized_2018, UER_normalized_2018, C2_2018, T2_2018, D2_2018, Delta_UER, Delta_UI, DI, DI_Category]
Index: []

[0 rows x 34 columns]

In [22]:
# 修改列名称“省代码”为“province”
data_merged3 = data_merged3.rename(columns={'省代码': 'Provincecode'})
# 修改列名称“省代码”为“province”
data_merged3 = data_merged3.rename(columns={'省': 'Province'})
# 修改列名称“省代码”为“province”
data_merged3 = data_merged3.rename(columns={'市代码': 'Citycode1'})
data_merged3 = data_merged3.rename(columns={'市': 'City'})
data_merged3 = data_merged3.rename(columns={'类型': 'Type'})

In [23]:
# 将data_merged导出为新的shapefile
output_shapefile_path = 'data/Chinamap_2019/CouplingValue_20142018.shp'
data_merged3.to_file(output_shapefile_path, driver='ESRI Shapefile')

/tmp/ipykernel_31177/2206065427.py:3: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  data_merged3.to_file(output_shapefile_path, driver='ESRI Shapefile')